// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*  $NetBSD: gzip.c,v 1.116 2018/10/27 11:39:12 skrll Exp $  */

/*-
 * SPDX-License-Identifier: BSD-2-Clause-NetBSD
 *
 * Copyright (c) 1997, 1998, 2003, 2004, 2006, 2008, 2009, 2010, 2011, 2015, 2017
 *    Matthew R. Green
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

import CMigration
import Darwin
import zlib

func got_siginfo(_ signo : Int32) {
  print_info = true
}

func got_sigint(_ signo : Int32)  {

  if remove_file != nil {
    unlink(remove_file)
  }

  /*
   * Re-raise the signal to get the exit status right for conformance
   * purposes.
   */
  signal(signo, SIG_DFL)
  raise(signo);

}

extension gzip {
  /*
   * uncompress input to output then close the input.  return the
   * uncompressed size written, and put the compressed sized read
   * into `*gsizep'.
   */
  func gz_uncompress(_ inx : FileDescriptor, _ out : FileDescriptor, _ pre : [UInt8], _ filename : String) -> (UInt, UInt)? {
    //    z_stream z;
    //    char *outbufp, *inbufp;
    //    uint32_t out_sub_tot = 0;
    enum GZstate{
      case MAGIC0
      case MAGIC1
      case METHOD
      case FLAGS
      case SKIPPING
      case EXTRA
      case EXTRA2
      case EXTRA3
      case ORIGNAME
      case COMMENT
      case HEAD_CRC1
      case HEAD_CRC2
      case INIT
      case READ
      case CRC
      case LEN
    }

    var state = GZstate.MAGIC0
    var flags = 0
    var skip_count = 0
    var error = Z_STREAM_ERROR
    var done_reading = false
    var crc = UInt(0)
//    var wr : ssize_t = 0
    var needmore = false
    var out_sub_tot = UInt(0)

    //    #define ADVANCE()       { z.next_in++; z.avail_in--; }

    let outbufp = UnsafeMutablePointer<UInt8>.allocate(capacity: Self.BUFLEN)
    let inbufp = UnsafeMutablePointer<UInt8>.allocate(capacity: Self.BUFLEN)

    var z = z_stream()
    z.avail_in = UInt32(pre.count)
    z.next_in = inbufp // use next_in as an index into pre (as opposed to a pointer starting at pre)
    z.avail_out = UInt32(Self.BUFLEN)
    z.next_out = outbufp
    z.zalloc = nil
    z.zfree = nil
    z.opaque = nil

    z.next_in.update(from: pre, count: pre.count)
    z.next_in += pre.count

    defer {
      outbufp.deallocate()
      inbufp.deallocate()
      if state == .READ || state == .CRC || state == .LEN {
        inflateEnd(&z)
      }
    }

    var in_tot = UInt(pre.count)
    var out_tot : UInt = 0

  outer:
    while true {
      check_siginfo()
      if (z.avail_in == 0 || needmore) && !done_reading {
        guard let in_size = try? inx.read(into: UnsafeMutableRawBufferPointer(start: z.next_in, count: Self.BUFLEN - Int(z.avail_in))) else {
          maybe_warn("failed to read stdin")
          return nil
//          break outer
        }
        if in_size == 0 {
          done_reading = true
        }

        r.infile_current += UInt(in_size)

        z.avail_in += UInt32(in_size)
        z.next_in += in_size

        needmore = false
        in_tot += UInt(in_size)
      }
      if (z.avail_in == 0) {
        if done_reading && state != .MAGIC0 {
          maybe_warnx("\(filename): unexpected end of file")
          return nil
        }
        break outer;
      }
      switch state {
        case .MAGIC0:
          if pre[0] != GZIP_MAGIC0 {
            if in_tot > 0 {
              maybe_warnx("\(filename): trailing garbage ignored")
              r.exit_value = 2
              break outer
            }
            maybe_warnx("input not gziped (MAGIC0)")
            return nil
          }
          z.next_in += 1
          z.avail_in -= 1
          state = .MAGIC1
          out_sub_tot = 0
          crc = crc32(0, nil, 0)

        case .MAGIC1:
          if z.next_in.pointee != GZIP_MAGIC1 && z.next_in.pointee != GZIP_OMAGIC1 {
            maybe_warnx("input not gziped (MAGIC1)");
            return nil
          }
          z.next_in += 1
          z.avail_in -= 1
          state = .METHOD

        case .METHOD:
          if z.next_in.pointee != Z_DEFLATED {
            maybe_warnx("unknown compression method")
            return nil
          }
          z.next_in += 1
          z.avail_in -= 1
          state = .FLAGS

        case .FLAGS:
          flags = Int(z.next_in.pointee)
          z.next_in += 1
          z.avail_in -= 1
          skip_count = 6;
          state = .SKIPPING

        case .SKIPPING:
          if (skip_count > 0) {
            skip_count -= 1
            z.next_in += 1
            z.avail_in -= 1
          } else {
            state = .EXTRA
          }

        case .EXTRA:
          if ((flags & EXTRA_FIELD) == 0) {
            state = .ORIGNAME;
            break;
          }
          skip_count = Int(z.next_in.pointee)
          z.next_in += 1
          z.avail_in -= 1
          state = .EXTRA2

        case .EXTRA2:
          skip_count |= Int(z.next_in.pointee) << 8
          z.next_in += 1
          z.avail_in -= 1
          state = .EXTRA3

        case .EXTRA3:
          if (skip_count > 0) {
            skip_count -= 1
            z.next_in += 1
            z.avail_in -= 1
          } else {
            state = .ORIGNAME
          }

        case .ORIGNAME:
          if ((flags & ORIG_NAME) == 0) {
            state = .COMMENT
            break;
          }
          if z.next_in.pointee == 0 {
            state = .COMMENT
          }
          z.next_in += 1
          z.avail_in -= 1

        case .COMMENT:
          if ((flags & COMMENT) == 0) {
            state = .HEAD_CRC1
            break;
          }
          if z.next_in.pointee == 0 {
            state = .HEAD_CRC1
          }
          z.next_in += 1
          z.avail_in -= 1

        case .HEAD_CRC1:
          if 0 != (flags & HEAD_CRC) {
            skip_count = 2
          }
          else {
            skip_count = 0
          }
          state = .HEAD_CRC2

        case .HEAD_CRC2:
          if (skip_count > 0) {
            skip_count -= 1
            z.next_in += 1
            z.avail_in -= 1
          } else {
            state = .INIT
          }

        case .INIT:
          if inflateInit2_(&z, -MAX_WBITS, ZLIB_VERSION, Int32(MemoryLayout<z_stream>.size)) != Z_OK {
            maybe_warnx("failed to inflateInit");
            return nil
          }
          state = .READ

        case .READ:
          let error = inflate(&z, Z_FINISH)
          switch error {
              /* Z_BUF_ERROR goes with Z_FINISH... */
            case Z_BUF_ERROR:
              if (z.avail_out > 0 && !done_reading) {
                continue;
              }

            case Z_STREAM_END, Z_OK:
              break;

            case Z_NEED_DICT:
              maybe_warnx("Z_NEED_DICT error");
              return nil
            case Z_DATA_ERROR:
              maybe_warnx("data stream error");
              return nil
            case Z_STREAM_ERROR:
              maybe_warnx("internal stream error");
                return nil
            case Z_MEM_ERROR:
              maybe_warnx("memory allocation error");
              return nil

            default:
              maybe_warn("unknown error from inflate(): \(error)")
          }
          let wr = Self.BUFLEN - Int(z.avail_out)

          if wr != 0 {
            crc = crc32(crc, outbufp, UInt32(wr))
            if !options.tflag,               /* don't write anything with -t */
               let z = try? out.write( UnsafeMutableRawBufferPointer(start: outbufp, count: wr)) {
              maybe_warn("error writing to output")
              return nil
            }

            out_tot += UInt(wr)
            out_sub_tot += UInt(wr)
          }

          if (error == Z_STREAM_END) {
            inflateEnd(&z);
            state = .CRC
          }

          z.next_out = outbufp
          z.avail_out = UInt32(Self.BUFLEN)

        case .CRC:

            if z.avail_in < 4 {
              if !done_reading {
                needmore = true
                continue;
              }
              maybe_warnx("truncated input")
              return nil
            }
          let origcrc = le32dec( UnsafeMutableBufferPointer(start: z.next_in, count: 4) )
            if (origcrc != crc) {
              maybe_warnx("invalid compressed data--crc error")
              return nil
            }


          z.avail_in -= 4
          z.next_in += 4

          if 0 == z.avail_in && done_reading {
            break outer
          }
          state = .LEN

        case .LEN:

            if (z.avail_in < 4) {
              if (!done_reading) {
                needmore = true
                continue;
              }
              maybe_warnx("truncated input");
              return nil
            }
          let origlen = le32dec(UnsafeMutableBufferPointer(start: z.next_in, count: 4))

            if (origlen != out_sub_tot) {
              maybe_warnx("invalid compressed data--length error")
              return nil
            }

          z.avail_in -= 4;
          z.next_in += 4;

          if (error < 0) {
            maybe_warnx("decompression error");
            return nil
          }
          state = .MAGIC0
      }
      continue
    }
    return (out_tot, in_tot)
  }

  /*
   * set the owner, mode, flags & utimes using the given file descriptor.
   * file is only used in possible warning messages.
   */
  func copymodes(_ fd : FileDescriptor, _ sbp : FileMetadata?, _ file : String)  {
//    struct timespec times[2];
//    struct stat sb;

    /*
     * If we have no info on the input, give this file some
     * default values and return..
     */
    let DEFFILEMODE : FilePermissions = [.ownerRead, .ownerWrite, .groupRead, .groupWrite, .otherRead, .otherWrite ]

    guard let sbp else {
      let mask = umask(022);
      fchmod(fd.rawValue, DEFFILEMODE.rawValue & ~mask)
      umask(mask)
      return
    }

    var pp = sbp.permissions
    /* if the chown fails, remove set-id bits as-per compress(1) */
    if (fchown(fd.rawValue, UInt32(sbp.userId), UInt32(sbp.groupId) ) < 0) {
      if (errno != EPERM) {
        maybe_warn("couldn't fchown: \(file)")
      }
      pp.remove([.setUserID, .setGroupID])
    }

    /* we only allow set-id and the 9 normal permission bits */
//    sbp.permissions &= S_ISUID | S_ISGID | S_IRWXU | S_IRWXG | S_IRWXO;
    if (fchmod(fd.rawValue, pp.rawValue) < 0) {
      maybe_warn("couldn't fchmod: \(file)")
    }

    let timesx = (sbp.lastAccess.timespec, sbp.lastWrite.timespec)
    if (futimens(fd, timesx) < 0) {
      maybe_warn("couldn't futimens: \(file)")
    }

    /* only try flags if they exist already */
    if !sbp.flags.isEmpty && fchflags(fd.rawValue, sbp.flags.rawValue) < 0 {
      maybe_warn("couldn't fchflags: \(file)")
    }
  }

  /* what sort of file is this? */
  func file_gettype(_ buf : [UInt8]) -> filetype {

    if (buf[0] == GZIP_MAGIC0 &&
        (buf[1] == GZIP_MAGIC1 || buf[1] == GZIP_OMAGIC1)) {
      return .GZIP
    }
    else if (memcmp(buf, BZIP2_MAGIC, 3) == 0 && "0123456789".utf8.contains(buf[3])) {
      return .BZIP2
    }
    else if (memcmp(buf, Z_MAGIC, 2) == 0) {
      return .Z
    }
    else if (memcmp(buf, PACK_MAGIC, 2) == 0) {
      return .PACK
    }
    else if (memcmp(buf, XZ_MAGIC, 4) == 0) {  /* XXX: We only have 4 bytes */
      return .XZ
    }
    else if (memcmp(buf, LZ_MAGIC, 4) == 0) {
      return .LZ
    }
    else {
      return .UNKNOWN
    }
  }

  /* check the outfile is OK. */
  func check_outfile(_ outfile : String) -> Bool {
    //    struct stat sb;
    var ok = true
    var stderr = FileDescriptor.standardError

    if !options.lflag,
       let sb = try? FileMetadata(for: outfile) {
      if options.fflag {
        unlink(outfile)
      }
      else if 0 != isatty(STDIN_FILENO) {
        print("\(outfile) already exists -- do you wish to overwrite (y or n)? ", terminator: "", to: &stderr)
        let ans = readLine() ?? "\n"
        if ans.first != "y" && ans.first != "Y" {
          print("\tnot overwriting", to: &stderr)
          ok = false
        } else {
          unlink(outfile)
        }
      } else {
        maybe_warnx("\(outfile) already exists -- skipping")
        ok = false
      }
    }
    return ok
  }

  func unlink_input(_ file : String, _ sb : FileMetadata) {
    if options.kflag {
      return
    }
    guard let nsb = try? FileMetadata(for: file) else {
      /* Must be gone already */
      return
    }
    if nsb.device != sb.device || nsb.inode != sb.inode {
      /* Definitely a different file */
      return
    }
    unlink(file)
  }


  func setup_signals() {

    signal(SIGINFO, got_siginfo )

    // FIXME: what should this do?
//    if signal(SIGINT, SIG_IGN) != SIG_IGN {
    signal(SIGINT, got_sigint )
// }
  }

  func infile_newdata(_ newdata : size_t) {
    r.infile_current += UInt(newdata)
  }

  func check_suffix(_ file : String) -> String?  {
    if !options.suffix.isEmpty && file.hasSuffix(options.suffix) {
      return options.suffix
    }
    for s in suffixes {
      if !s.zipped.isEmpty && file.hasSuffix(s.zipped) {
        return s.zipped
      }
    }
    return nil
  }

  func clear_type_and_creator(_ fd : FileDescriptor) {
    var alist = attrlist()
    struct Abuf {
      var length : UInt32 = 0
      var info : (CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
                  CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
                  CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
                  CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,) = ( 0, 0, 0, 0, 0, 0, 0, 0,
                                                                               0, 0, 0, 0, 0, 0, 0, 0,
                                                                               0, 0, 0, 0, 0, 0, 0, 0,
                                                                               0, 0, 0, 0, 0, 0, 0, 0,)
    }

    var abuf = Abuf()

    alist.bitmapcount = UInt16(ATTR_BIT_MAP_COUNT)
    alist.commonattr = UInt32(ATTR_CMN_FNDRINFO)

    let z = fgetattrlist(fd.rawValue, &alist, &abuf, MemoryLayout<Abuf>.size, 0)

    if z == 0 && abuf.length == MemoryLayout<Abuf>.size {
      abuf.info = ( 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0,)
      fsetattrlist(fd.rawValue, &alist, &abuf.info, MemoryLayout.size(ofValue: abuf.info), 0)
    }
  }
}

