// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*	$NetBSD: gzip.c,v 1.116 2018/10/27 11:39:12 skrll Exp $	*/

/*-
 * SPDX-License-Identifier: BSD-2-Clause-NetBSD
 *
 * Copyright (c) 1997, 1998, 2003, 2004, 2006, 2008, 2009, 2010, 2011, 2015, 2017
 *    Matthew R. Green
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

import CMigration
import Darwin

@main struct gzip : ShellCommand {

  let unix2003 = true

  /*
   * gzip.c -- GPL free gzip using zlib.
   *
   * RFC 1950 covers the zlib format
   * RFC 1951 covers the deflate format
   * RFC 1952 covers the gzip format
   *
   * TODO:
   *	- use mmap where possible
   *	- make bzip2/compress -v/-t/-l support work as well as possible
   */

  /*
   #ifdef __APPLE__
   /* from sys/param.h */
   #define	nitems(x)	(sizeof((x)) / sizeof((x)[0]))

   /* from sys/endian.h */
   static __inline uint32_t
   le32dec(const void *pp)
   {
   uint8_t const *p = (uint8_t const *)pp;

   return (((unsigned)p[3] << 24) | (p[2] << 16) | (p[1] << 8) | p[0]);
   }
   #endif /* __APPLE__ */
   */

  /*
   import lzma
   import bz2
   */

  /* what type of file are we dealing with */
  enum filetype {
    case GZIP
    case BZIP2
    case Z
    case PACK
    case XZ
    case LZ
    case LAST
    case UNKNOWN
  }


  static let BZ2_SUFFIX = ".bz2"
  let BZIP2_MAGIC = "BZh"

  static let Z_SUFFIX = ".Z"
  let Z_MAGIC : [UInt8]	= [0o037, 0o235]

  let PACK_MAGIC : [UInt8] = [0o037, 0o036]

  static let XZ_SUFFIX = ".xz"
  let XZ_MAGIC : [UInt8] = [0o375] + "7zXZ".map { $0.asciiValue! }

  static let LZ_SUFFIX = ".lz"
  let LZ_MAGIC = "LZIP"

  static let GZ_SUFFIX = ".gz"
  static let BUFLEN = 64 * 1024

  let GZIP_MAGIC0 = 0x1F
  let GZIP_MAGIC1 = 0x8B
  let GZIP_OMAGIC1 = 0x9E

  let GZIP_TIMESTAMP = 4
  let GZIP_ORIGNAME	= 10

  let HEAD_CRC = 0x02
  let EXTRA_FIELD = 0x04
  let ORIG_NAME = 0x08
  let COMMENT = 0x10

  let OS_CODE = 3	/* Unix */

  struct suffixes_t {
    var zipped : String
    var normal : String	/* for unzip - must not be longer than zipped */

    init(_ z : String, _ n : String) {
      zipped = z
      normal = n
    }
  }
  var suffixes : [suffixes_t] = [
    .init(GZ_SUFFIX,	""),	/* Overwritten by -S .xxx */

      .init(GZ_SUFFIX,	""),
    .init(".z",		""),
    .init("-gz",		""),
    .init("-z",		""),
    .init("_z",		""),
    .init(".taz",		".tar"),
    .init(".tgz",		".tar"),

      .init(BZ2_SUFFIX,	""),
    .init(".tbz",		".tar"),
    .init(".tbz2",		".tar"),


      .init(Z_SUFFIX,	""),


      .init(XZ_SUFFIX,	""),


      .init(LZ_SUFFIX,	""),

      .init(GZ_SUFFIX,	""),	/* Overwritten by -S "" */
  ]

  // #define NUM_SUFFIXES (nitems(suffixes))
  static let SUFFIX_MAXLEN = 30

  static let GZIP_APPLE_VERSION = 475

   var	gzip_version = "Apple gzip \(GZIP_APPLE_VERSION)"
/*   #else
   static	const char	gzip_version[] = "FreeBSD gzip 20190107";
   #endif
   */

  /*
   static	const char	gzip_copyright[] = \
   "   Copyright (c) 1997, 1998, 2003, 2004, 2006 Matthew R. Green\n"
   "   All rights reserved.\n"
   "\n"
   "   Redistribution and use in source and binary forms, with or without\n"
   "   modification, are permitted provided that the following conditions\n"
   "   are met:\n"
   "   1. Redistributions of source code must retain the above copyright\n"
   "      notice, this list of conditions and the following disclaimer.\n"
   "   2. Redistributions in binary form must reproduce the above copyright\n"
   "      notice, this list of conditions and the following disclaimer in the\n"
   "      documentation and/or other materials provided with the distribution.\n"
   "\n"
   "   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR\n"
   "   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\n"
   "   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.\n"
   "   IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
   "   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
   "   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
   "   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED\n"
   "   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
   "   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
   "   OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
   "   SUCH DAMAGE.";
   #endif
   */

  static var print_info : sig_atomic_t = 0

  struct CommandOptions {

    var cflag = false			/* stdout mode */
    var dflag = false			/* decompress mode */
    var lflag = false			/* list mode */
    var numflag = 6		/* gzip -1..-9 value */

    var remove_file : String? = nil	/* file to be removed upon SIGINT */

    var fflag = false			/* force mode */

    var kflag = false			/* don't delete input files */
    var nflag = false			/* don't save name/timestamp */
    var Nflag = false			/* don't restore name/timestamp */
    var qflag = false			/* quiet mode */
    var rflag = false			/* recursive mode */
    var tflag = false			/* test */
    var vflag = false			/* verbose mode */

    var zcat = false

    var args : [String] = []
  }

  /*
   static	int	exit_value = 0;		/* exit value */

   static	const char *infile;		/* name of file coming in */

   static	off_t	infile_total;		/* total expected to read/write */
   static	off_t	infile_current;		/* current read/write */
   */

  var longopts : [CMigration.option] = [
    .init("stdout",	.no_argument), //		0,	'c' },
    .init("to-stdout",		.no_argument) // ,		0,	'c' },
      .init( "decompress",		.no_argument), //		0,	'd' },
    .init( "uncompress",		.no_argument), //		0,	'd' },
    .init( "force",		.no_argument), //		0,	'f' },
    .init( "help",		.no_argument), //		0,	'h' },
    .init( "keep",		.no_argument), //		0,	'k' },
    .init( "list",		.no_argument), //		0,	'l' },
    .init( "no-name.", .no_argument), //		no_argument,		0,	'n' },
    .init( "name",		.no_argument), //		0,	'N' },
    .init( "quiet",		.no_argument), //		0,	'q' },
    .init( "recursive",		.no_argument), //		0,	'r' },
    .init( "suffix",		.required_argument), //	0,	'S' },
    .init( "test",		.no_argument), //		0,	't' },
    .init( "verbose",		.no_argument), //		0,	'v' },
    .init( "version",		.no_argument), //		0,	'V' },
    .init( "fast",		.no_argument), //		0,	'1' },
    .init( "best",		.no_argument), //		0,	'9' },
    .init( "ascii",		.no_argument), //		0,	'a' },
    .init( "license",		.no_argument), //		0,	'L' },
    .init( "zcat", .no_argument),
  ]

  var options : CommandOptions!

  func parseOptions() throws(CmdErr) -> CommandOptions {
    var options = CommandOptions()

    setup_signals();

    var prepend : [String] = []

    if let gzip = Environment["GZIP"] {
      prepend = prepend_gzip(gzip)
    }

    /*
     * XXX
     * handle being called `gunzip', `zcat' and `gzcat'
     */
    if programName == "gunzip" {
      options.dflag = true
    }
    else if programName == "zcat" || programName == "gzcat" {
      options.dflag = true
      options.cflag = true
    }

    if programName == "zcat" {
      options.zcat = true
    }


    let OPT_LIST = "123456789acdfhklLNnqrS:tVv"

    let go = BSDGetopt_long(OPT_LIST, longopts, prepend + CommandLine.arguments.dropFirst() )
    while let (k, v) = try go.getopt_long() {
      switch k {
        case "1", "2", "3", "4", "5", "6", "7", "8", "9":
          options.numflag = Int(k)!
        case "c", "stdout", "to-stdout":
          options.cflag = true
        case "d", "decompress", "uncompress":
          options.dflag = true
        case "l", "list":
          options.lflag = true
          options.dflag = true
        case "V", "version":
          display_version()
          fatalError()

        case "a", "ascii":
          warnx("option --ascii ignored on this system")
        case "f", "force":
          options.fflag = true
        case "k", "keep":
          options.kflag = true
        case "L", "license":
          display_license();
          fatalError()
        case "N", "name":
          options.nflag = false
          options.Nflag = true
        case "n", "no-name":
          options.nflag = true
          options.Nflag = false
        case "q", "quiet":
          options.qflag = true
        case "r", "recursive":
          options.rflag = true
        case "S":
          let len = v.count
          if len != 0 {
            if len > Self.SUFFIX_MAXLEN {
              errx(1, "incorrect suffix: '\(v)': too long")
            }
            // FIXME: what is this:
            suffixes[0].zipped = v
          } else {
            suffixes[NUM_SUFFIXES - 1].zipped = "";
          }
        case "t", "test":
          optioins.cflag = true
          options.tflag = true
          options.dflag = true
        case "v", "verbose":
          options.vflag = true
        case "zcat":
          options.zcat = true
          options.dflag = true
          options.cflag = true

        default:
          throw CmdErr(1)
      }
    }
    options.args = go.remaining

    return options
  }

  func runCommand() async throws(CmdErr) {
    if options.args.isEmpty {
      if options.dflag {	/* stdin mode */
        handle_stdin()
      }
      else {		/* stdout mode */
        handle_stdout()
      }
    } else {
      for argv in options.args {
        handle_pathname(argv)
      }
    }

    if !options.qflag && options.lflag && options.args.count > 1 {
      print_list(-1, 0, "(totals)", 0);
    }
    if (exit_value == 0 && (ferror(stdout) != 0 || fflush(stdout) != 0)) {
      err(1, "stdout")
    }
    exit(exit_value)
  }

  /* maybe print a warning */
  func maybe_warn(_ fmt : String, _ ap : CVarArg...) {
    if !options.qflag {
      withVaList(ap) {
        vwarn(fmt, $0)
      }
    }
    if exit_value == 0 {
      exit_value = 1
    }
  }

  /* ... without an errno. */
  func maybe_warnx(_ fmt : String, _ ap : CVarArg...) {

    if !options.qflag {
      withVaList(ap) {
        vwarnx(fmt, $0)
      }
    }
    if exit_value == 0 {
      exit_value = 1
    }
  }

  /* maybe print an error */
  func maybe_err(_ fmt : String, _ ap : CVarArg...) {
    withVaList(ap) {
      if !options.qflag {
        vwarn(fmt, $0);
      }
    }
    exit(2)
  }

  /* ... without an errno. */
  func maybe_errx(_ fmt : String, _ ap : CVarArg...) {
    withVaList(ap) {
      if !options.qflag {
        vwarnx(fmt, $0);
      }
    }
    exit(2)
  }

  /* split up $GZIP and prepend it to the argument list */
  func prepend_gzip(_ gzip : String) -> [String] {
    return gzip.replacing("\t", with: " ").split(separator: " ", omittingEmptySubsequences: true)
  }

  /* compress input to output. Return bytes read, -1 on error */
  func gz_compress(_ inx : FileDescriptor, _ out : FileDescriptor, _ gsizep : inout off_t, _ origname : String, _ mtime : UInt32) -> off_t {
    z_stream z;
    char *outbufp, *inbufp;
    off_t in_tot = 0, out_tot = 0;
    ssize_t in_size;
    int i, error;
    uLong crc;

    outbufp = malloc(BUFLEN);
    inbufp = malloc(BUFLEN);
    if (outbufp == NULL || inbufp == NULL) {
      maybe_err("malloc failed");
      goto out;
    }

    memset(&z, 0, sizeof z);
    z.zalloc = Z_NULL;
    z.zfree = Z_NULL;
    z.opaque = 0;

    if (nflag != 0) {
      mtime = 0;
      origname = "";
    }

    i = snprintf(outbufp, BUFLEN, "%c%c%c%c%c%c%c%c%c%c%s",
                 GZIP_MAGIC0, GZIP_MAGIC1, Z_DEFLATED,
                 *origname ? ORIG_NAME : 0,
                 mtime & 0xff,
                 (mtime >> 8) & 0xff,
                 (mtime >> 16) & 0xff,
                 (mtime >> 24) & 0xff,
                 numflag == 1 ? 4 : numflag == 9 ? 2 : 0,
                 OS_CODE, origname);
    if (i >= BUFLEN) {
      /* this need PATH_MAX > BUFLEN ... */
      maybe_err("snprintf");
    }
    if (*origname) {
      i++;
    }

    z.next_out = (unsigned char *)outbufp + i;
    z.avail_out = BUFLEN - i;

    error = deflateInit2(&z, numflag, Z_DEFLATED,
                         (-MAX_WBITS), 8, Z_DEFAULT_STRATEGY);
    if (error != Z_OK) {
      maybe_warnx("deflateInit2 failed");
      in_tot = -1;
      goto out;
    }

    crc = crc32(0L, Z_NULL, 0);
    for (;;) {
      if (z.avail_out == 0) {
        if (write_retry(out, outbufp, Self.BUFLEN) != Self.BUFLEN) {
          maybe_warn("write");
          out_tot = -1;
          goto out;
        }

        out_tot += Self.BUFLEN
        z.next_out = (unsigned char *)outbufp;
        z.avail_out = Self.BUFLEN;
      }

      if (z.avail_in == 0) {
        in_size = read(in, inbufp, Self.BUFLEN);
        if (in_size < 0) {
          maybe_warn("read");
          in_tot = -1;
          goto out;
        }
        if (in_size == 0) {
          break;
        }
        infile_newdata(in_size);

        crc = crc32(crc, (const Bytef *)inbufp, (unsigned)in_size);
        in_tot += in_size;
        z.next_in = (unsigned char *)inbufp;
        z.avail_in = in_size;
      }

      error = deflate(&z, Z_NO_FLUSH);
      if (error != Z_OK && error != Z_STREAM_END) {
        maybe_warnx("deflate failed");
        in_tot = -1;
        goto out;
      }
    }

    /* clean up */
    for (;;) {
      size_t len;
      ssize_t w;

      error = deflate(&z, Z_FINISH);
      if (error != Z_OK && error != Z_STREAM_END) {
        maybe_warnx("deflate failed");
        in_tot = -1;
        goto out;
      }

      len = (char *)z.next_out - outbufp;

      w = write_retry(out, outbufp, len);
      if (w == -1 || (size_t)w != len) {
        maybe_warn("write");
        out_tot = -1;
        goto out;
      }
      out_tot += len;
      z.next_out = (unsigned char *)outbufp;
      z.avail_out = BUFLEN;

      if (error == Z_STREAM_END) {
        break;
      }
    }

    if (deflateEnd(&z) != Z_OK) {
      maybe_warnx("deflateEnd failed");
      in_tot = -1;
      goto out;
    }

    i = snprintf(outbufp, BUFLEN, "%c%c%c%c%c%c%c%c",
                 (int)crc & 0xff,
                 (int)(crc >> 8) & 0xff,
                 (int)(crc >> 16) & 0xff,
                 (int)(crc >> 24) & 0xff,
                 (int)in_tot & 0xff,
                 (int)(in_tot >> 8) & 0xff,
                 (int)(in_tot >> 16) & 0xff,
                 (int)(in_tot >> 24) & 0xff);
    if (i != 8) {
      maybe_err("snprintf");
    }
    if (write_retry(out, outbufp, i) != i) {
      maybe_warn("write");
      in_tot = -1;
    } else {
      out_tot += i;
    }

  out:
    if (inbufp != NULL) {
      free(inbufp);
    }
    if (outbufp != NULL) {
      free(outbufp);
    }
    if (gsizep) {
      *gsizep = out_tot;
    }
    return in_tot;
  }

  /*
   * uncompress input to output then close the input.  return the
   * uncompressed size written, and put the compressed sized read
   * into `*gsizep'.
   */
  func gz_uncompress(_ inx : FileDescriptor, _ out : FileDescriptor, _ pre : [UInt8], _ gsizep : inout off_t, _ filename : String) -> off_t {
    //    z_stream z;
    //    char *outbufp, *inbufp;
    //    uint32_t out_sub_tot = 0;
    enum GZstate{
      case MAGIC0
      case MAGIC1
      case METHOD
      case FLAGS
      case SKIPPING
      case EXTRA
      case EXTRA2
      case EXTRA3
      case ORIGNAME
      case COMMENT
      case HEAD_CRC1
      case HEAD_CRC2
      case INIT
      case READ
      case CRC
      case LEN
    }

    var state = GZstate.MAGIC0
    var flags = 0
    var skip_count = 0
    var error = Z_STREAM_ERROR
    var done_reading = 0
    var crc = 0
    var wr : ssize_t = 0
    var needmore = 0

    //    #define ADVANCE()       { z.next_in++; z.avail_in--; }

    if ((outbufp = malloc(BUFLEN)) == NULL) {
      maybe_err("malloc failed");
      goto out2;
    }
    if ((inbufp = malloc(BUFLEN)) == NULL) {
      maybe_err("malloc failed");
      goto out1;
    }

    var z = z_stream()
    //    z.avail_in = prelen
    z.next_in = 0 // use next_in as an index into pre (as opposed to a pointer starting at pre)
    z.avail_out = BUFLEN
    z.next_out = outbufp
    z.zalloc = nil
    z.zfree = nil
    z.opaque = 0

    var in_tot = prelen
    var out_tot = 0

  outer:
    while true {
      check_siginfo();
      if (z.avail_in == 0 || needmore) && done_reading == 0 {
        ssize_t in_size;

        if (z.avail_in > 0) {
          memmove(inbufp, z.next_in, z.avail_in);
        }
        z.next_in = (unsigned char *)inbufp;
        in_size = read(in, z.next_in + z.avail_in,
                       BUFLEN - z.avail_in);

        if (in_size == -1) {
          maybe_warn("failed to read stdin");
          out_tot = -1
          break outer
        } else if (in_size == 0) {
          done_reading = 1;
        }
        infile_newdata(in_size);

        z.avail_in += in_size;
        needmore = 0;

        in_tot += in_size;
      }
      if (z.avail_in == 0) {
        if (done_reading && state != .MAGIC0) {
          maybe_warnx("%s: unexpected end of file",
                      filename);
          out_tot = -1
          break outer
        }
        break outer;
      }
      switch state {
        case .MAGIC0:
          if pre[z.next_in] != GZIP_MAGIC0 {
            if (in_tot > 0) {
              maybe_warnx("\(filename): trailing garbage ignored")
              exit_value = 2
              break outer
            }
            maybe_warnx("input not gziped (MAGIC0)")
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1
          out_sub_tot = 0;
          crc = crc32(0, Z_NULL, 0);

        case .MAGIC1:
          if pre[z.next_in] != GZIP_MAGIC1 && pre[z.next_in] != GZIP_OMAGIC1 {
            maybe_warnx("input not gziped (MAGIC1)");
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1

        case .METHOD:
          if pre[z.next_in] != Z_DEFLATED {
            maybe_warnx("unknown compression method");
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1

        case .FLAGS:
          flags = pre[z.next_in]
          z.next_in += 1
          skip_count = 6;
          state += 1

        case .SKIPPING:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .EXTRA:
          if ((flags & EXTRA_FIELD) == 0) {
            state = .ORIGNAME;
            break;
          }
          skip_count = pre[z.next_in]
          z.next_in += 1
          state += 1

        case .EXTRA2:
          skip_count |= (pre[z.next_in] << 8)
          z.next_in += 1
          state += 1

        case .EXTRA3:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .ORIGNAME:
          if ((flags & ORIG_NAME) == 0) {
            state += 1
            break;
          }
          if pre[z.next_in] == 0 {
            state += 1
          }
          z.next_in += 1

        case .COMMENT:
          if ((flags & COMMENT) == 0) {
            state += 1
            break;
          }
          if pre[z.next_in] == 0 {
            state += 1
          }
          z.next_in += 1

        case .HEAD_CRC1:
          if (flags & HEAD_CRC) {
            skip_count = 2;
          }
          else {
            skip_count = 0;
          }
          state++;

        case .HEAD_CRC2:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .INIT:
          if (inflateInit2(&z, -MAX_WBITS) != Z_OK) {
            maybe_warnx("failed to inflateInit");
            out_tot = -1
            break outer
          }
          state += 1

        case .READ:
          error = inflate(&z, Z_FINISH);
          switch (error) {
              /* Z_BUF_ERROR goes with Z_FINISH... */
            case Z_BUF_ERROR:
              if (z.avail_out > 0 && !done_reading) {
                continue;
              }

            case Z_STREAM_END:
            case Z_OK:
              break;

            case Z_NEED_DICT:
              maybe_warnx("Z_NEED_DICT error");
              out_tot = -1
              break outer
            case Z_DATA_ERROR:
              maybe_warnx("data stream error");
              out_tot = -1
              break outer
            case Z_STREAM_ERROR:
              maybe_warnx("internal stream error");
              out_tot = -1
              break outer
            case Z_MEM_ERROR:
              maybe_warnx("memory allocation error");
              out_tot = -1
              break outer

            default:
              maybe_warn("unknown error from inflate(): %d",
                         error);
          }
          wr = BUFLEN - z.avail_out;

          if (wr != 0) {
            crc = crc32(crc, (const Bytef *)outbufp, (unsigned)wr);
            if (

              /* don't write anything with -t */
              tflag == 0 &&

              write_retry(out, outbufp, wr) != wr) {
              maybe_warn("error writing to output");
              out_tot = -1
              break outer
            }

            out_tot += wr;
            out_sub_tot += wr;
          }

          if (error == Z_STREAM_END) {
            inflateEnd(&z);
            state += 1
          }

          z.next_out = (unsigned char *)outbufp;
          z.avail_out = BUFLEN;

        case .CRC:
          {
            uLong origcrc;

            if (z.avail_in < 4) {
              if (!done_reading) {
                needmore = 1;
                continue;
              }
              maybe_warnx("truncated input");
              out_tot = -1
              break outer
            }
            origcrc = le32dec(&z.next_in[0]);
            if (origcrc != crc) {
              maybe_warnx("invalid compressed data--crc error")
              out_tot = -1
              break outer
            }
          }

          z.avail_in -= 4;
          z.next_in += 4;

          if (!z.avail_in && done_reading) {
            break outer
          }
          state += 1

        case .LEN:
          {
            uLong origlen;

            if (z.avail_in < 4) {
              if (!done_reading) {
                needmore = 1;
                continue;
              }
              maybe_warnx("truncated input");
              out_tot = -1
              break outer
            }
            origlen = le32dec(&z.next_in[0]);

            if (origlen != out_sub_tot) {
              maybe_warnx("invalid compressed data--length error")
              out_tot = -1
              break outer
            }
          }

          z.avail_in -= 4;
          z.next_in += 4;

          if (error < 0) {
            maybe_warnx("decompression error");
            out_tot = -1
            break outer
          }
          state = .MAGIC0
      }
      continue
    }
    if (state > .INIT) {
      inflateEnd(&z);
    }

    free(inbufp);
  out1:
    free(outbufp);
  out2:
    if (gsizep) {
      *gsizep = in_tot;
    }
    return (out_tot);
  }

  /*
   * set the owner, mode, flags & utimes using the given file descriptor.
   * file is only used in possible warning messages.
   */
  func copymodes(_ fd : FileDescriptor, _ sbp : FileMetadata, _ file : String)  {
    struct timespec times[2];
    struct stat sb;

    /*
     * If we have no info on the input, give this file some
     * default values and return..
     */
    if (sbp == NULL) {
      mode_t mask = umask(022);

      fchmod(fd, DEFFILEMODE & ~mask);
      umask(mask);
      return;
    }
    sb = *sbp;

    /* if the chown fails, remove set-id bits as-per compress(1) */
    if (fchown(fd, sb.st_uid, sb.st_gid) < 0) {
      if (errno != EPERM) {
        maybe_warn("couldn't fchown: %s", file);
      }
      sb.st_mode &= ~(S_ISUID|S_ISGID);
    }

    /* we only allow set-id and the 9 normal permission bits */
    sb.st_mode &= S_ISUID | S_ISGID | S_IRWXU | S_IRWXG | S_IRWXO;
    if (fchmod(fd, sb.st_mode) < 0) {
      maybe_warn("couldn't fchmod: %s", file);
    }

    times[0] = sb.st_atim;
    times[1] = sb.st_mtim;
    if (futimens(fd, times) < 0) {
      maybe_warn("couldn't futimens: %s", file);
    }

    /* only try flags if they exist already */
    if (sb.st_flags != 0 && fchflags(fd, sb.st_flags) < 0) {
      maybe_warn("couldn't fchflags: %s", file);
    }
  }

  /* what sort of file is this? */
  func file_gettype(_ buf : [UInt8]) -> filetype {

    if (buf[0] == GZIP_MAGIC0 &&
        (buf[1] == GZIP_MAGIC1 || buf[1] == GZIP_OMAGIC1)) {
      return .GZIP
    }
    else if (memcmp(buf, BZIP2_MAGIC, 3) == 0 &&
             buf[3] >= '0' && buf[3] <= '9') {
      return .BZIP2
    }
    else if (memcmp(buf, Z_MAGIC, 2) == 0) {
      return .Z
    }
    else if (memcmp(buf, PACK_MAGIC, 2) == 0) {
      return .PACK
    }
    else if (memcmp(buf, XZ_MAGIC, 4) == 0) {	/* XXX: We only have 4 bytes */
      return .XZ
    }
    else if (memcmp(buf, LZ_MAGIC, 4) == 0) {
      return .LZ
    }
    else {
      return .UNKNOWN
    }
  }

  /* check the outfile is OK. */
  func check_outfile(_ outfile : String) -> Bool {
//    struct stat sb;
    var ok = true
    var stderr = FileDescriptor.standardError

    if !options.lflag,
       let sb = try? FileMetadata(for: outfile) {
      if options.fflag {
        unlink(outfile)
      }
      else if 0 != isatty(STDIN_FILENO) {
        print("\(outfile) already exists -- do you wish to overwrite (y or n)? ", terminator: "", to: &stderr)
        let ans = readLine() ?? "\n"
        if ans.first != "y" && ans.first != "Y" {
          print("\tnot overwriting", to: &stderr)
          ok = false
        } else {
          unlink(outfile)
        }
      } else {
        maybe_warnx("\(outfile) already exists -- skipping")
        ok = false
      }
    }
    return ok
  }

  func unlink_input(_ file : String, _ sb : FileMetadata) {
    struct stat nsb;

    if options.kflag {
      return;
    }
    bzero(&nsb, sizeof(nsb));
    if (stat(file, &nsb) != 0) {
      /* Must be gone already */
      return;
    }
    if (nsb.st_dev != sb->st_dev || nsb.st_ino != sb->st_ino) {
      /* Definitely a different file */
      return;
    }
    unlink(file);
  }

  func got_sigint(_ signo : Int32)  {

    if (remove_file != NULL) {
      unlink(remove_file);
    }

    /*
     * Re-raise the signal to get the exit status right for conformance
     * purposes.
     */
    signal(signo, SIG_DFL);
    raise(signo);

  }

  func got_siginfo(_ signo : Int32) {

    print_info = 1;
  }

  func setup_signals() {

    signal(SIGINFO, got_siginfo);

    if (signal(SIGINT, SIG_IGN) != SIG_IGN) {
      signal(SIGINT, got_sigint);
    }
  }

  func infile_newdata(_ newdata : size_t) {

    infile_current += newdata;
  }

  func infile_set(_ newinfile : String, _ total : off_t) {
    if (newinfile) {
      infile = newinfile;
    }

    infile_total = total;
  }

  func infile_clear() {

    infile = NULL;

    infile_total = infile_current = 0;
  }

  func check_suffix(char *file, int xlate) -> [suffixes_t]?  {
    const suffixes_t *s;
    int len = strlen(file);
    char *sp;

    for (s = suffixes; s != suffixes + NUM_SUFFIXES; s++) {
      /* if it doesn't fit in "a.suf", don't bother */
      if (s->ziplen >= len) {
        continue;
      }
      sp = file + len - s->ziplen;
      if (strcmp(s->zipped, sp) != 0) {
        continue;
      }
      if (xlate) {
        strcpy(sp, s->normal);
      }
      return s;
    }
    return NULL;
  }

  func clear_type_and_creator(_ fd : FileDescriptor) {
    struct attrlist alist;
    struct {
      u_int32_t length;
      char info[32];
    } abuf;

    memset(&alist, 0, sizeof(alist));
    alist.bitmapcount = ATTR_BIT_MAP_COUNT;
    alist.commonattr = ATTR_CMN_FNDRINFO;

    if (!fgetattrlist(fd, &alist, &abuf, sizeof(abuf), 0) && abuf.length == sizeof(abuf)) {
      memset(abuf.info, 0, 8);
      fsetattrlist(fd, &alist, abuf.info, sizeof(abuf.info), 0);
    }
  }

  /*
   * compress the given file: create a corresponding .gz file and remove the
   * original.
   */
  func file_compress(_ file : String, _ outfile : String, _ outsize : size_t) -> off_t {
 //   int in;
//    int out;
//    off_t size, in_size;

//    struct stat isb, osb;
//    const suffixes_t *suff;

    guard let inx = try? FileDescriptor.open(file, .readOnly) else {
      maybe_warn("can't open \(file)")
      return -1
    }

    defer { try? inx.close() }

//    bzero(&isb, sizeof(isb));
    guard let isb = try? FileMetadata(for: inx) else {
      maybe_warn("couldn't stat: \(file)")
      return -1
    }

    infile_set(file, isb.size)

    if !options.cflag {
      if isb.links > 1 && !options.fflag {
        maybe_warnx("\(file) has \(isb.links-1) other link\(isb.links == 2 ? "" : "s") -- skipping")
        return -1
      }

      if (!options.fflag && (suff = check_suffix(file, 0)) &&
          suff->zipped[0] != 0) {
        maybe_warnx("\(file) already has \(suff.zipped) suffix -- unchanged")
        return -1
      }

      /* Add (usually) .gz to filename */
      if ((size_t)snprintf(outfile, outsize, "%s%s",
                           file, suffixes[0].zipped) >= outsize) {
        memcpy(outfile + outsize - suffixes[0].ziplen - 1,
               suffixes[0].zipped, suffixes[0].ziplen + 1);
      }

      if (check_outfile(outfile) == 0) {
        return -1
      }
    }

    if (!options.cflag) {
      out = open(outfile, O_WRONLY | O_CREAT | O_EXCL, 0600);
      if (out == -1) {
        maybe_warn("could not create output: %s", outfile);
        fclose(stdin);
        return (-1);
      }

      remove_file = outfile;
    } else {
      out = STDOUT_FILENO;
    }

    in_size = gz_compress(in, out, &size, basename(file), (uint32_t)isb.st_mtime);

    /*
     * If there was an error, in_size will be -1.
     * If we compressed to stdout, just return the size.
     * Otherwise stat the file and check it is the correct size.
     * We only blow away the file if we can stat the output and it
     * has the expected size.
     */
    if options.cflag {
      return in_size == -1 ? -1 : size;
    }

    if (fstat(out, &osb) != 0) {
      maybe_warn("couldn't stat: %s", outfile);
      goto bad_outfile;
    }

    if (osb.st_size != size) {
      maybe_warnx("output file: %s wrong size (%ju != %ju), deleting",
                  outfile, (uintmax_t)osb.st_size, (uintmax_t)size);
      goto bad_outfile;
    }

    fcopyfile(in, out, 0, COPYFILE_ACL | COPYFILE_XATTR);
    clear_type_and_creator(out);

    copymodes(out, &isb, outfile);
    remove_file = NULL;

    close(in);
    if (close(out) == -1) {
      maybe_warn("couldn't close output");
    }

    /* output is good, ok to delete input */
    unlink_input(file, &isb);
    return (size);

  bad_outfile:
    if (close(out) == -1) {
      maybe_warn("couldn't close output");
    }

    maybe_warnx("leaving original \(file)")
    unlink(outfile)
    return (size)
  }

  /* uncompress the given file and remove the original */
  func file_uncompress(_ file : String, _ outfile : String, _ outsize : size_t) -> off_t {
/*    struct stat isb, osb;
    off_t size;
    ssize_t rbytes;
    unsigned char fourbytes[4];
    enum filetype method;
    int fd, ofd, zfd = -1;
    int error;
    size_t in_size;

    ssize_t rv;
    time_t timestamp = 0;
    char name[PATH_MAX + 1];
*/

    /* gather the old name info */

    guard let fd = try? FileDescriptor.open(file, .readOnly) else {
      maybe_warn("can't open \(file)")
      return -1
    }
    defer { try? fd.close() }

    guard let isb = try? FileMetadata(for: fd) else {
      maybe_warn("can't stat \(file)")
      return -1
    }

    var in_size = isb.filetype == .regular ? isb.size : 0
    infile_set(file, Int64(in_size))

    strlcpy(outfile, file, outsize);
    if (check_suffix(outfile, 1) == NULL && !(options.cflag || options.lflag)) {
      maybe_warnx("%s: unknown suffix -- ignored", file);
      goto lose;
    }

    let fourbytes = try? fd.readUpToCount(4)
    if fourbytes?.count ?? -1 != 4 {
      /* we don't want to fail here. */

      if options.fflag {
        return -1
      }
      if fourbytes == nil {
        maybe_warn("can't read \(file)")
      }
      else {
        goto unexpected_EOF;
      }
      return -1
    }
    infile_newdata(rbytes);

    let method = file_gettype(fourbytes);

    if (!options.fflag && method == .UNKNOWN) {
      maybe_warnx("%s: not in gzip format", file);
      goto lose;
    }

    if (method == .GZIP && options.Nflag) {
      unsigned char ts[4];	/* timestamp */

      rv = pread(fd, ts, sizeof ts, GZIP_TIMESTAMP);
      if (rv >= 0 && rv < (ssize_t)(sizeof ts)) {
        goto unexpected_EOF;
      }
      if (rv == -1) {
        if (!options.fflag) {
          maybe_warn("can't read %s", file);
        }
        goto lose;
      }
      infile_newdata(rv);
      timestamp = le32dec(&ts[0]);

      if (fourbytes[3] & ORIG_NAME) {
        rbytes = pread(fd, name, sizeof(name) - 1, GZIP_ORIGNAME);
        if (rbytes < 0) {
          maybe_warn("can't read %s", file);
          goto lose;
        }
        if (name[0] != '\0') {
          char *dp, *nf;

          /* Make sure that name is NUL-terminated */
          name[rbytes] = '\0';

          /* strip saved directory name */
          nf = strrchr(name, '/');
          if (nf == NULL) {
            nf = name;
          }
          else {
            nf++;
          }

          /* preserve original directory name */
          dp = strrchr(file, '/');
          if (dp == NULL) {
            dp = file;
          }
          else {
            dp++;
          }
          snprintf(outfile, outsize, "%.*s%.*s",
                   (int) (dp - file),
                   file, (int) rbytes, nf);
        }
      }
    }

    lseek(fd, 0, SEEK_SET);

    if (!options.cflag || options.lflag) {

      if (isb.st_nlink > 1 && !options.lflag && !options.fflag) {
        maybe_warnx("%s has %ju other links -- skipping",
                    file, (uintmax_t)isb.st_nlink - 1);
        goto lose;
      }
      if (!options.nflag && timestamp) {
        isb.st_mtime = timestamp;
      }
      if (check_outfile(outfile) == 0) {
        goto lose;
      }
    }

    if (options.cflag) {
      zfd = STDOUT_FILENO;
    }
    else if (options.lflag) {
      zfd = -1;
    }
    else {
      zfd = open(outfile, O_WRONLY|O_CREAT|O_EXCL, 0600);
      if (zfd == STDOUT_FILENO) {
        /* We won't close STDOUT_FILENO later... */
        zfd = dup(zfd);
        close(STDOUT_FILENO);
      }
      if (zfd == -1) {
        maybe_warn("can't open %s", outfile);
        goto lose;
      }
      remove_file = outfile;
    }

    switch (method) {

      case .BZIP2:
        /* XXX */
        if (options.lflag) {
          maybe_warnx("no -l with bzip2 files");
          goto lose;
        }

        size = unbzip2(fd, zfd, NULL, 0, NULL);
        break;

      case .Z: {
        FILE *in, *out;

        /* XXX */
        if (options.lflag) {
          maybe_warnx("no -l with Lempel-Ziv files");
          goto lose;
        }

        if ((in = zdopen(fd)) == NULL) {
          maybe_warn("zdopen for read: %s", file);
          goto lose;
        }

        out = fdopen(dup(zfd), "w");
        if (out == NULL) {
          maybe_warn("fdopen for write: %s", outfile);
          fclose(in);
          goto lose;
        }

        size = zuncompress(in, out, NULL, 0, NULL);
        /* need to fclose() if ferror() is true... */
        error = ferror(in);
        if (error | fclose(in)) {
          if (error) {
            maybe_warn("failed infile");
          }
          else {
            maybe_warn("failed infile fclose");
          }
          if (!options.cflag) {
            unlink(outfile);
          }
          fclose(out);
          goto lose;
        }
        if (fclose(out) != 0) {
          maybe_warn("failed outfile fclose");
          if (!options.cflag) {
            unlink(outfile);
          }
          goto lose;
        }
        break;
      }

      case .PACK:
        if (options.lflag) {
          maybe_warnx("no -l with packed files");
          goto lose;
        }

        size = unpack(fd, zfd, NULL, 0, NULL);
        break;

      case .XZ:
        if (options.lflag) {
          size = unxz_len(fd);
          if (!options.tflag) {
            print_list_out(in_size, size, file);
            close(fd);
            return -1;
          }
        } else {
          size = unxz(fd, zfd, NULL, 0, NULL);
        }
        break;

      case .LZ:
        if (options.lflag) {
          maybe_warnx("no -l with lzip files");
          goto lose;
        }
        size = unlz(fd, zfd, NULL, 0, NULL);
        break;

      case .UNKNOWN:
        if (options.lflag) {
          maybe_warnx("no -l for unknown filetypes");
          goto lose;
        }
        size = cat_fd(NULL, 0, NULL, fd);
        break;

      default:
        if (options.lflag) {
          print_list(fd, in_size, outfile, isb.st_mtime);
          if (!options.tflag) {
            close(fd);
            return -1;	/* XXX */
          }
        }

        size = gz_uncompress(fd, zfd, NULL, 0, NULL, file);
        break;
    }

    if (close(fd) != 0) {
      maybe_warn("couldn't close input");
    }
    if (zfd != STDOUT_FILENO && close(zfd) != 0) {
      maybe_warn("couldn't close output");
    }

    if (size == -1) {
      if (!options.cflag) {
        unlink(outfile);
      }
      maybe_warnx("%s: uncompress failed", file);
      return -1;
    }

    /* if testing, or we uncompressed to stdout, this is all we need */

    if (options.tflag) {
      return size;
    }

    /* if we are uncompressing to stdin, don't remove the file. */
    if (options.cflag) {
      return size;
    }

    /*
     * if we create a file...
     */
    /*
     * if we can't stat the file don't remove the file.
     */

    ofd = open(outfile, O_RDWR, 0);
    if (ofd == -1) {
      maybe_warn("couldn't open (leaving original): %s",
                 outfile);
      return -1;
    }
    if (fstat(ofd, &osb) != 0) {
      maybe_warn("couldn't stat (leaving original): %s",
                 outfile);
      close(ofd);
      return -1;
    }
    if (osb.st_size != size) {
      maybe_warnx("stat gave different size: %ju != %ju (leaving original)",
                  (uintmax_t)size, (uintmax_t)osb.st_size);
      close(ofd);
      unlink(outfile);
      return -1;
    }

    copymodes(ofd, &isb, outfile);
    remove_file = NULL;

    close(ofd);
    unlink_input(file, &isb);
    return size;

  unexpected_EOF:
    maybe_warnx("%s: unexpected end of file", file);
  lose:
    if (fd != -1) {
      close(fd);
    }
    if (zfd != -1 && zfd != STDOUT_FILENO) {
      close(zfd);
    }
    return -1;
  }

  func check_siginfo() {
    if (print_info == 0) {
      return;
    }
    if (infile) {
      if (infile_total) {
        int pcent = (int)((100.0 * infile_current) / infile_total);

        fprintf(stderr, "%s: done %llu/%llu bytes %d%%\n",
                infile, (unsigned long long)infile_current,
                (unsigned long long)infile_total, pcent);
      } else {
        fprintf(stderr, "%s: done %llu bytes\n",
                infile, (unsigned long long)infile_current);
      }
    }
    print_info = 0;
  }

  func cat_fd(_ prepend : [UInt8], _ count : size_t, _ gsizep : inout off_t, _ fd : FileDescriptor) -> off_t {
    char buf[BUFLEN];
    off_t in_tot;
    ssize_t w;

    in_tot = count;
    w = write_retry(STDOUT_FILENO, prepend, count);
    if (w == -1 || (size_t)w != count) {
      maybe_warn("write to stdout");
      return -1;
    }
    while true {
      let rv = read(fd, buf, sizeof buf);
      if (rv == 0) {
        break;
      }
      if (rv < 0) {
        maybe_warn("read from fd \(fd.rawValue)")
        break;
      }
      infile_newdata(rv);

      if (write_retry(STDOUT_FILENO, buf, rv) != rv) {
        maybe_warn("write to stdout");
        break;
      }
      in_tot += rv;
    }

    if (gsizep) {
      *gsizep = in_tot;
    }
    return (in_tot);
  }

  func handle_stdin() {
    /*    struct stat isb;
     unsigned char fourbytes[4];
     size_t in_size;
     off_t usize, gsize;
     enum filetype method;
     ssize_t bytes_read;

     FILE *in;
     */

    defer { infile_clear() }

    if !options.fflag && !options.lflag && isatty(STDIN_FILENO) {
      maybe_warnx("standard input is a terminal -- ignoring")
      return
    }

    if (fstat(STDIN_FILENO, &isb) < 0) {
      maybe_warn("fstat");
      return
    }
    if (S_ISREG(isb.st_mode)) {
      in_size = isb.st_size;
    }
    else {
      in_size = 0;
    }
    infile_set("(stdin)", in_size);

    if (options.lflag) {
      print_list(STDIN_FILENO, in_size, infile, isb.st_mtime);
      return
    }

    guard let fourbytes = try? read_retry(STDIN_FILENO, 4) else {
      maybe_warn("can't read stdin");
      return
    }
    if fourbytes.count != 4 {
      maybe_warnx("(stdin): unexpected end of file")
      return
    }

    let method = file_gettype(fourbytes)
    switch method {
      case .GZIP:
        usize = gz_uncompress(FileDescriptor.standardInput, FileDescriptor.standardOutput, fourbytes, &gsize, "(stdin)");

      case .BZIP2:
        usize = unbzip2(STDIN_FILENO, STDOUT_FILENO, fourbytes, &gsize);

      case .Z:
        if ((inx = zdopen(STDIN_FILENO)) == NULL) {
          maybe_warnx("zopen of stdin");
          return
        }

        usize = zuncompress(inx, stdout, fourbytes, &gsize);
        fclose(inx);

      case .PACK:
        usize = unpack(STDIN_FILENO, STDOUT_FILENO, fourbytes, &gsize);

      case .XZ:
        usize = unxz(STDIN_FILENO, STDOUT_FILENO, fourbytes, &gsize);

      case .LZ:
        usize = unlz(STDIN_FILENO, STDOUT_FILENO, fourbytes, &gsize);
      default:

        if (!options.fflag) {
          maybe_warnx("unknown compression format");
          return
        }
        usize = cat_fd(fourbytes, &gsize, STDIN_FILENO);

    }

    if options.vflag && !options.tflag && usize != -1 && gsize != -1 {
      print_verbage(NULL, NULL, usize, gsize);
    }
    if options.vflag && options.tflag {
      print_test("(stdin)", usize != -1);
    }

  }

  func handle_stdout() {
    /*    off_t gsize;

     off_t usize;
     time_t systime;
     int ret;
     */

    infile_set("(stdout)", 0);

    if !options.fflag && 0 != isatty(STDOUT_FILENO) {
      maybe_warnx("standard output is a terminal -- ignoring");
      return;
    }

    /* If stdin is a file use its mtime, otherwise use current time */
    guard let sb = try? FileMetadata(for: FileDescriptor.standardInput) else {
      maybe_warn("Can't stat stdin")
      return;
    }

    var mtime : UInt32
    if sb.filetype == .regular {
      infile_set("(stdout)", sb.size);
      mtime = sb.lastWrite
    } else {
      let systime = Darwin.time(nil)
      if (systime == -1) {
        maybe_warn("time")
        return;
      }
      mtime = systime
    }

    let usize = gz_compress(FileDescriptor.standardInput, FileDescriptor.standardOutput, &gsize, "", mtime)

    if options.vflag && !options.tflag && usize != -1 && gsize != -1 {
      print_verbage(nil, nil, usize, gsize);
    }

  }

  /* do what is asked for, for the path name */
  func handle_pathname(_ path : String) {
    /*    char *opath = path, *s = NULL;
     ssize_t len;
     int slen;
     struct stat sb;
     */
    /* check for stdout/stdin */
    if path == "-" {
      if options.dflag {
        handle_stdin();
      }
      else {
        handle_stdout()
      }
      return
    }

    if options.zcat && !options.fflag && unix2003 {
      if let p = path.matches(of: /\.[^.\/]$/), !p.isEmpty, p[0].0 == Z_SUFFIX {
      } else {
        path.append(Z_SUFFIX)
      }
    }

    var sb : FileMetadata?
  retry:
    while true {
      sb = try? FileMetadata(for: path)
      if nil == sb || (!options.fflag && !options.cflag && nil == (sb = try? FileMetadata(for: path, followSymlinks: false), sb).1 ) {

        /* lets try <path>.gz if we're decompressing */
        if options.dflag && s == NULL && errno == ENOENT {
          path.append(suffixes[0].zipped)
          continue retry
        }

        /* Include actual path for clarity. */
        maybe_warn("can't stat: %s (%s)", opath, path);

        return
      }
      break
    }
    if sb.filetype == .directory {
      if options.rflag {
        handle_dir(path)
      }
      else {
        maybe_warnx("\(path) is a directory")
      }
      return
    }

    if sb.filetype == .regular {
      handle_file(path, sb)
    }
    else {
      maybe_warnx("\(path) is not a regular file")
    }
  }

  /* compress/decompress a file */
  func handle_file(_ file : String, _ sbp : FileMetadata) {
    off_t usize, gsize;
    char	outfile[PATH_MAX];

    infile_set(file, sbp->st_size);
    if (options.dflag) {
      usize = file_uncompress(file, outfile, sizeof(outfile));

      if (options.vflag && options.tflag) {
        print_test(file, usize != -1);
      }

      if (usize == -1) {
        return;
      }
      gsize = sbp->st_size;
    } else {
      gsize = file_compress(file, outfile, sizeof(outfile));
      if (gsize == -1) {
        return;
      }
      usize = sbp->st_size;
    }
    infile_clear();

    if (options.vflag && !options.tflag) {
      print_verbage(file, (options.cflag) ? NULL : outfile, usize, gsize);
    }

  }

  /* this is used with -r to recursively descend directories */
  func handle_dir(_ dir : String) {
    guard let fts = try? FTSWalker(path: [dir], options: [.PHYSICAL,  .NOCHDIR], sort: nil) else {
      warn("couldn't fts_open \(dir)")
      return
    }

    for entry in fts {
      switch entry.info {
        case .D, .DP:
          continue

        case .DNR, .ERR, .NS:
          maybe_warn(entry.path)
          continue
        case .F:
          handle_file(entry.path, entry.statp)
      }
    }
    if (errno != 0) {
      warn("error with fts_read \(dir)")
    }
  }

  /* print a ratio - size reduction as a fraction of uncompressed size */
  func print_ratio(_ inx : off_t, _ out : off_t, _ wherex : FileDescriptor) {
    int percent10;	/* 10 * percent */
    off_t diff;
    char buff[8];
    int len;

    diff = in - out/2;
    if (in == 0 && out == 0) {
      percent10 = 0;
    }
    else if (diff < 0) {
      /*
       * Output is more than double size of input! print -99.9%
       * Quite possibly we've failed to get the original size.
       */
      percent10 = -999;
    }
    else {
      /*
       * We only need 12 bits of result from the final division,
       * so reduce the values until a 32bit division will suffice.
       */
      while (in > 0x100000) {
        diff >>= 1;
        in >>= 1;
      }
      if (in != 0) {
        percent10 = ((u_int)diff * 2000) / (u_int)in - 1000;
      }
      else {
        percent10 = 0;
      }
    }

    len = snprintf(buff, sizeof buff, "%2.2d.", percent10);
    /* Move the '.' to before the last digit */
    buff[len - 1] = buff[len - 2];
    buff[len - 2] = '.';
    fprintf(where, "%5s%%", buff);
  }

  /* print compression statistics, and the new name (if there is one!) */
  func print_verbage(_ file : String, _ nfile : String, _ usize : off_t, _ gsize : off_t) {
    if (file) {
      fprintf(stderr, "%s:%s  ", file,
              strlen(file) < 7 ? "\t\t" : "\t");
    }
    print_ratio(usize, gsize, stderr);
    if (nfile) {
      fprintf(stderr, " -- replaced with %s", nfile);
    }
    fprintf(stderr, "\n");
    fflush(stderr);
  }

  /* print test results */
  func print_test(_ file : String, _ ok : Int) {

    if (exit_value == 0 && ok == 0) {
      exit_value = 1;
    }
    fprintf(stderr, "%s:%s  %s\n", file,
            strlen(file) < 7 ? "\t\t" : "\t", ok ? "OK" : "NOT OK");
    fflush(stderr);
  }

  /* print a file's info ala --list */
  /* eg:
   compressed uncompressed  ratio uncompressed_name
   354841      1679360  78.8% /usr/pkgsrc/distfiles/libglade-2.0.1.tar
   */
  func print_list(_ fd : FileDescriptor, _ out : off_t, _ outfile : String, _ ts : time_t) {
    static int first = 1;

    static off_t in_tot, out_tot;
    uint32_t crc = 0;

    off_t in = 0, rv;

    if (first) {

      if (options.vflag) {
        printf("method  crc     date  time  ");
      }

      if (!options.qflag) {
        printf("  compressed uncompressed  "
               "ratio uncompressed_name\n");
      }
    }
    first = 0;

    /* print totals? */

    if (fd == -1) {
      in = in_tot;
      out = out_tot;
    } else

    {
      /* read the last 4 bytes - this is the uncompressed size */
      rv = lseek(fd, (off_t)(-8), SEEK_END);
      if (rv != -1) {
        unsigned char buf[8];
        uint32_t usize;

        rv = read(fd, (char *)buf, sizeof(buf));
        if (rv == -1) {
          maybe_warn("read of uncompressed size");
        }
        else if (rv != sizeof(buf)) {
          maybe_warnx("read of uncompressed size");
        }

        else {
          usize = le32dec(&buf[4]);
          in = (off_t)usize;

          crc = le32dec(&buf[0]);

        }
      }
    }

    if (options.vflag && fd == -1) {
      printf("                            ");
    }
    else if (options.vflag) {
      char *date = ctime(&ts);

      /* skip the day, 1/100th second, and year */
      date += 4;
      date[12] = 0;
      printf("%5s %08x %11s ", "defla"/*XXX*/, crc, date);
    }
    in_tot += in;
    out_tot += out;

    print_list_out(out, in, outfile);
  }

  func print_list_out(_ out : off_t, _ inx : off_t, _ outfile : String) {
    printf("%12llu %12llu ", (unsigned long long)out, (unsigned long long)in);
    print_ratio(in, out, stdout);
    printf(" %s\n", outfile);
  }

  /* display the usage of NetBSD gzip */
  var usage : String { get { """
\(gzip_version)
usage: \(programName) [-123456789acdfhklLNnqrtVv] [-S .suffix] [<file> [<file> ...]]
 -1 --fast            fastest (worst) compression
 -2 .. -8             set compression level
 -9 --best            best (slowest) compression
 -c --stdout          write to stdout, keep original files
    --to-stdout
 -d --decompress      uncompress files
    --uncompress\n"
 -f --force           force overwriting & compress links
 -h --help            display this help
 -k --keep            don't delete input files during operation
 -l --list            list compressed file contents
 -N --name            save or restore original file name and time stamp
 -n --no-name         don't save original file name or time stamp
 -q --quiet           output no warnings
 -r --recursive       recursively compress files in directories
 -S .suf              use suffix .suf instead of .gz
    --suffix .suf
 -t --test            test compressed file
 -V --version         display program version
 -v --verbose         print extra statistics
"""
  }
  }


  /* display the license information of FreeBSD gzip */
  func display_license() {
    fprintf(stderr,
            "%s (based on FreeBSD gzip 20190107, NetBSD gzip 20150113)\n",
            gzip_version);

    fprintf(stderr, "%s\n", gzip_copyright);
    exit(0);
  }

  /* display the version of NetBSD gzip */
  func display_version() {
    var stderr = FileDescriptor.standardError
    print(gzip_version, to: &stderr)
    exit(0)
  }

  func read_retry(_ fd : FileDescriptor, _ sz: size_t) throws -> [UInt8] {
    var left = min(sz, SSIZE_MAX)
    var cp = [UInt8]()
    while cp.count < sz {
      let ret = fd.readUpToCount(sz)
      if ret.isEmpty { break } // EOF
      cp += ret
    }
    return cp
  }

  func write_retry(_ fd : FileDescriptor, _ buf : [UInt8], _ sz : size_t) -> ssize_t {
    const char *cp = buf;
    size_t left = MIN(sz, (size_t) SSIZE_MAX);

    while (left > 0) {
      ssize_t ret;

      ret = write(fd, cp, left);
      if (ret == -1) {
        return ret;
      } else if (ret == 0) {
        abort();	/* Can't happen */
      }
      cp += ret;
      left -= ret;
    }

    return sz - left;
  }
}
