// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*  $NetBSD: gzip.c,v 1.116 2018/10/27 11:39:12 skrll Exp $  */

/*-
 * SPDX-License-Identifier: BSD-2-Clause-NetBSD
 *
 * Copyright (c) 1997, 1998, 2003, 2004, 2006, 2008, 2009, 2010, 2011, 2015, 2017
 *    Matthew R. Green
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

import CMigration
import Darwin
import zlib

extension gzip {
  /*
   * uncompress input to output then close the input.  return the
   * uncompressed size written, and put the compressed sized read
   * into `*gsizep'.
   */
  func gz_uncompress(_ inx : FileDescriptor, _ out : FileDescriptor, _ pre : [UInt8], _ gsizep : inout off_t, _ filename : String) -> off_t {
    //    z_stream z;
    //    char *outbufp, *inbufp;
    //    uint32_t out_sub_tot = 0;
    enum GZstate{
      case MAGIC0
      case MAGIC1
      case METHOD
      case FLAGS
      case SKIPPING
      case EXTRA
      case EXTRA2
      case EXTRA3
      case ORIGNAME
      case COMMENT
      case HEAD_CRC1
      case HEAD_CRC2
      case INIT
      case READ
      case CRC
      case LEN
    }

    var state = GZstate.MAGIC0
    var flags = 0
    var skip_count = 0
    var error = Z_STREAM_ERROR
    var done_reading = 0
    var crc = 0
    var wr : ssize_t = 0
    var needmore = 0

    //    #define ADVANCE()       { z.next_in++; z.avail_in--; }

    if ((outbufp = malloc(BUFLEN)) == NULL) {
      maybe_err("malloc failed");
      goto out2;
    }
    if ((inbufp = malloc(BUFLEN)) == NULL) {
      maybe_err("malloc failed");
      goto out1;
    }

    var z = z_stream()
    //    z.avail_in = prelen
    z.next_in = 0 // use next_in as an index into pre (as opposed to a pointer starting at pre)
    z.avail_out = BUFLEN
    z.next_out = outbufp
    z.zalloc = nil
    z.zfree = nil
    z.opaque = 0

    var in_tot = prelen
    var out_tot = 0

  outer:
    while true {
      check_siginfo();
      if (z.avail_in == 0 || needmore) && done_reading == 0 {
        ssize_t in_size;

        if (z.avail_in > 0) {
          memmove(inbufp, z.next_in, z.avail_in);
        }
        z.next_in = (unsigned char *)inbufp;
        in_size = read(in, z.next_in + z.avail_in,
                       BUFLEN - z.avail_in);

        if (in_size == -1) {
          maybe_warn("failed to read stdin");
          out_tot = -1
          break outer
        } else if (in_size == 0) {
          done_reading = 1;
        }

        r.infile_current += in_size

        z.avail_in += in_size;
        needmore = 0;

        in_tot += in_size;
      }
      if (z.avail_in == 0) {
        if (done_reading && state != .MAGIC0) {
          maybe_warnx("%s: unexpected end of file",
                      filename);
          out_tot = -1
          break outer
        }
        break outer;
      }
      switch state {
        case .MAGIC0:
          if pre[z.next_in] != GZIP_MAGIC0 {
            if (in_tot > 0) {
              maybe_warnx("\(filename): trailing garbage ignored")
              r.lexit_value = 2
              break outer
            }
            maybe_warnx("input not gziped (MAGIC0)")
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1
          out_sub_tot = 0;
          crc = crc32(0, Z_NULL, 0);

        case .MAGIC1:
          if pre[z.next_in] != GZIP_MAGIC1 && pre[z.next_in] != GZIP_OMAGIC1 {
            maybe_warnx("input not gziped (MAGIC1)");
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1

        case .METHOD:
          if pre[z.next_in] != Z_DEFLATED {
            maybe_warnx("unknown compression method");
            out_tot = -1
            break outer
          }
          z.next_in += 1
          state += 1

        case .FLAGS:
          flags = pre[z.next_in]
          z.next_in += 1
          skip_count = 6;
          state += 1

        case .SKIPPING:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .EXTRA:
          if ((flags & EXTRA_FIELD) == 0) {
            state = .ORIGNAME;
            break;
          }
          skip_count = pre[z.next_in]
          z.next_in += 1
          state += 1

        case .EXTRA2:
          skip_count |= (pre[z.next_in] << 8)
          z.next_in += 1
          state += 1

        case .EXTRA3:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .ORIGNAME:
          if ((flags & ORIG_NAME) == 0) {
            state += 1
            break;
          }
          if pre[z.next_in] == 0 {
            state += 1
          }
          z.next_in += 1

        case .COMMENT:
          if ((flags & COMMENT) == 0) {
            state += 1
            break;
          }
          if pre[z.next_in] == 0 {
            state += 1
          }
          z.next_in += 1

        case .HEAD_CRC1:
          if (flags & HEAD_CRC) {
            skip_count = 2;
          }
          else {
            skip_count = 0;
          }
          state++;

        case .HEAD_CRC2:
          if (skip_count > 0) {
            skip_count--;
            z.next_in += 1
          } else {
            state += 1
          }

        case .INIT:
          if (inflateInit2(&z, -MAX_WBITS) != Z_OK) {
            maybe_warnx("failed to inflateInit");
            out_tot = -1
            break outer
          }
          state += 1

        case .READ:
          let error = inflate(&z, Z_FINISH)
          switch error {
              /* Z_BUF_ERROR goes with Z_FINISH... */
            case Z_BUF_ERROR:
              if (z.avail_out > 0 && !done_reading) {
                continue;
              }

            case Z_STREAM_END:
            case Z_OK:
              break;

            case Z_NEED_DICT:
              maybe_warnx("Z_NEED_DICT error");
              out_tot = -1
              break outer
            case Z_DATA_ERROR:
              maybe_warnx("data stream error");
              out_tot = -1
              break outer
            case Z_STREAM_ERROR:
              maybe_warnx("internal stream error");
              out_tot = -1
              break outer
            case Z_MEM_ERROR:
              maybe_warnx("memory allocation error");
              out_tot = -1
              break outer

            default:
              maybe_warn("unknown error from inflate(): %d",
                         error);
          }
          wr = BUFLEN - z.avail_out;

          if (wr != 0) {
            crc = crc32(crc, (const Bytef *)outbufp, (unsigned)wr);
            if (

              /* don't write anything with -t */
              tflag == 0 &&

              write_retry(out, outbufp, wr) != wr) {
              maybe_warn("error writing to output");
              out_tot = -1
              break outer
            }

            out_tot += wr;
            out_sub_tot += wr;
          }

          if (error == Z_STREAM_END) {
            inflateEnd(&z);
            state += 1
          }

          z.next_out = (unsigned char *)outbufp;
          z.avail_out = BUFLEN;

        case .CRC:
          {
            uLong origcrc;

            if (z.avail_in < 4) {
              if (!done_reading) {
                needmore = 1;
                continue;
              }
              maybe_warnx("truncated input");
              out_tot = -1
              break outer
            }
            origcrc = le32dec(&z.next_in[0]);
            if (origcrc != crc) {
              maybe_warnx("invalid compressed data--crc error")
              out_tot = -1
              break outer
            }
          }

          z.avail_in -= 4;
          z.next_in += 4;

          if (!z.avail_in && done_reading) {
            break outer
          }
          state += 1

        case .LEN:
          {
            uLong origlen;

            if (z.avail_in < 4) {
              if (!done_reading) {
                needmore = 1;
                continue;
              }
              maybe_warnx("truncated input");
              out_tot = -1
              break outer
            }
            origlen = le32dec(&z.next_in[0]);

            if (origlen != out_sub_tot) {
              maybe_warnx("invalid compressed data--length error")
              out_tot = -1
              break outer
            }
          }

          z.avail_in -= 4;
          z.next_in += 4;

          if (error < 0) {
            maybe_warnx("decompression error");
            out_tot = -1
            break outer
          }
          state = .MAGIC0
      }
      continue
    }
    if (state > .INIT) {
      inflateEnd(&z);
    }

    free(inbufp);
  out1:
    free(outbufp);
  out2:
    if (gsizep) {
      *gsizep = in_tot;
    }
    return (out_tot);
  }

  /*
   * set the owner, mode, flags & utimes using the given file descriptor.
   * file is only used in possible warning messages.
   */
  func copymodes(_ fd : FileDescriptor, _ sbp : FileMetadata, _ file : String)  {
    struct timespec times[2];
    struct stat sb;

    /*
     * If we have no info on the input, give this file some
     * default values and return..
     */
    if (sbp == NULL) {
      mode_t mask = umask(022);

      fchmod(fd, DEFFILEMODE & ~mask);
      umask(mask);
      return;
    }
    sb = *sbp;

    /* if the chown fails, remove set-id bits as-per compress(1) */
    if (fchown(fd, sb.st_uid, sb.st_gid) < 0) {
      if (errno != EPERM) {
        maybe_warn("couldn't fchown: %s", file);
      }
      sb.st_mode &= ~(S_ISUID|S_ISGID);
    }

    /* we only allow set-id and the 9 normal permission bits */
    sb.st_mode &= S_ISUID | S_ISGID | S_IRWXU | S_IRWXG | S_IRWXO;
    if (fchmod(fd, sb.st_mode) < 0) {
      maybe_warn("couldn't fchmod: %s", file);
    }

    times[0] = sb.st_atim;
    times[1] = sb.st_mtim;
    if (futimens(fd, times) < 0) {
      maybe_warn("couldn't futimens: %s", file);
    }

    /* only try flags if they exist already */
    if (sb.st_flags != 0 && fchflags(fd, sb.st_flags) < 0) {
      maybe_warn("couldn't fchflags: %s", file);
    }
  }

  /* what sort of file is this? */
  func file_gettype(_ buf : [UInt8]) -> filetype {

    if (buf[0] == GZIP_MAGIC0 &&
        (buf[1] == GZIP_MAGIC1 || buf[1] == GZIP_OMAGIC1)) {
      return .GZIP
    }
    else if (memcmp(buf, BZIP2_MAGIC, 3) == 0 &&
             buf[3] >= '0' && buf[3] <= '9') {
      return .BZIP2
    }
    else if (memcmp(buf, Z_MAGIC, 2) == 0) {
      return .Z
    }
    else if (memcmp(buf, PACK_MAGIC, 2) == 0) {
      return .PACK
    }
    else if (memcmp(buf, XZ_MAGIC, 4) == 0) {  /* XXX: We only have 4 bytes */
      return .XZ
    }
    else if (memcmp(buf, LZ_MAGIC, 4) == 0) {
      return .LZ
    }
    else {
      return .UNKNOWN
    }
  }

  /* check the outfile is OK. */
  func check_outfile(_ outfile : String) -> Bool {
    //    struct stat sb;
    var ok = true
    var stderr = FileDescriptor.standardError

    if !options.lflag,
       let sb = try? FileMetadata(for: outfile) {
      if options.fflag {
        unlink(outfile)
      }
      else if 0 != isatty(STDIN_FILENO) {
        print("\(outfile) already exists -- do you wish to overwrite (y or n)? ", terminator: "", to: &stderr)
        let ans = readLine() ?? "\n"
        if ans.first != "y" && ans.first != "Y" {
          print("\tnot overwriting", to: &stderr)
          ok = false
        } else {
          unlink(outfile)
        }
      } else {
        maybe_warnx("\(outfile) already exists -- skipping")
        ok = false
      }
    }
    return ok
  }

  func unlink_input(_ file : String, _ sb : FileMetadata) {
    struct stat nsb;

    if options.kflag {
      return;
    }
    bzero(&nsb, sizeof(nsb));
    if (stat(file, &nsb) != 0) {
      /* Must be gone already */
      return;
    }
    if (nsb.st_dev != sb->st_dev || nsb.st_ino != sb->st_ino) {
      /* Definitely a different file */
      return;
    }
    unlink(file);
  }

  func got_sigint(_ signo : Int32)  {

    if (remove_file != NULL) {
      unlink(remove_file);
    }

    /*
     * Re-raise the signal to get the exit status right for conformance
     * purposes.
     */
    signal(signo, SIG_DFL);
    raise(signo);

  }

  func got_siginfo(_ signo : Int32) {

    print_info = 1;
  }

  func setup_signals() {

    signal(SIGINFO, got_siginfo);

    if (signal(SIGINT, SIG_IGN) != SIG_IGN) {
      signal(SIGINT, got_sigint);
    }
  }

  func infile_newdata(_ newdata : size_t) {

    infile_current += newdata;
  }

  func check_suffix(char *file, int xlate) -> [suffixes_t]?  {
    const suffixes_t *s;
    int len = strlen(file);
    char *sp;

    for (s = suffixes; s != suffixes + NUM_SUFFIXES; s++) {
      /* if it doesn't fit in "a.suf", don't bother */
      if (s->ziplen >= len) {
        continue;
      }
      sp = file + len - s->ziplen;
      if (strcmp(s->zipped, sp) != 0) {
        continue;
      }
      if (xlate) {
        strcpy(sp, s->normal);
      }
      return s;
    }
    return NULL;
  }

  func clear_type_and_creator(_ fd : FileDescriptor) {
    struct attrlist alist;
    struct {
      u_int32_t length;
      char info[32];
    } abuf;

    memset(&alist, 0, sizeof(alist));
    alist.bitmapcount = ATTR_BIT_MAP_COUNT;
    alist.commonattr = ATTR_CMN_FNDRINFO;

    if (!fgetattrlist(fd, &alist, &abuf, sizeof(abuf), 0) && abuf.length == sizeof(abuf)) {
      memset(abuf.info, 0, 8);
      fsetattrlist(fd, &alist, abuf.info, sizeof(abuf.info), 0);
    }
  }
}

