// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using an LLM
// from a file containing the following notice:

/*	$NetBSD: zuncompress.c,v 1.11 2011/08/16 13:55:02 joerg Exp $ */

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1985, 1986, 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Diomidis Spinellis and James A. Woods, derived from original
 * work by Spencer Thomas and Joseph Orost.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * from: NetBSD: zopen.c,v 1.8 2003/08/07 11:13:29 agc Exp
 * $FreeBSD$
 */

/* This file is #included by gzip.c */

import CMigration
import Darwin

//  static off_t total_compressed_bytes;
//  static size_t compressed_prelen;
//  static char *compressed_pre;

class s_zstate {
  var gzip : gzip
  var fp : FileDescriptor			/* File stream for I/O */
  var mode : Character = "r"    			/* r or w */
  var n_bits : Int = 0			/* Number of bits/code. */
  var maxbits : Int = 0			/* User settable max # bits/code. */
  var maxcode : code_int = 0 /* Maximum code, given n_bits. */
  var maxmaxcode : code_int = 0 /* Should NEVER generate this code. */
  var htab = Array(repeating: UInt8(0), count: HSIZE)
  var codetab = Array(repeating: UInt16(0), count: HSIZE)
  var hsize : code_int = 0		/* For dynamic table sizing. */
  var free_ent : code_int		/* First unused entry. */
  /*
   * Block compression parameters -- after all codes are used up,
   * and compression rate changes, start over.
   */
  var block_compress : Bool = false
  var clear_flg = false
  var ratio : Int = 0
  var checkpoint : count_int = 0
  var offset : Int = 0
  var in_count : Int = 0	/* Length of input. */
  var bytes_out : Int = 0	/* Length of compressed output. */
  var out_count : Int = 0	/* # of codes output (for debugging). */
  var buf = Array(repeating: UInt8(0), count: BITS)

  // write parameters
  var fcode : Int = 0
  var ent : code_int = 0
  var hsize_reg : code_int = 0
  var hshift : Int = 0

  // read parameters
  var stackp : Int = 0
  var finchar : UInt8 = 0
  var code : code_int = 0
  var oldcode : code_int?
  var incode : code_int = 0
  var roffset : Int = 0
  var size : Int = 0
  var state : State 

  var gbuf = Array(repeating: UInt8(0), count: BITS)

  var compressed_pre : [UInt8] = []
  var total_compressed_bytes : UInt = 0

  // iinstance variables above, constants below

  static let BITS = 16    /* Default bits. */
  static let HSIZE = 69001    /* 95% occupancy */ /* XXX may not need HSIZE */
  let BIT_MASK = 0x1f    /* Defines for third byte of header. */
  let BLOCK_MASK = 0x80
  let CHECK_GAP = 10000    /* Ratio check interval. */
  let BUFSIZE = 64 * 1024

  /*
   * Masks 0x40 and 0x20 are free.  I think 0x20 should mean that there is
   * a fourth header byte (for expansion).
   */
  let INIT_BITS = 9  /* Initial number of bits/code. */

  /*
   * the next two codes should not be changed lightly, as they must not
   * lie within the contiguous general code space.
   */
  let FIRST = 257    /* First free entry. */
  let CLEAR = 256    /* Table clear output code. */


  func MAXCODE(_ n_bits : Int) -> Int { return  (1 << n_bits) - 1 }

  typealias code_int = Int
  typealias count_int = Int

  let magic_header : [UInt8] = [0x1f, 0x9d]

  let rmask : [UInt8] = [0x00, 0x01, 0x03, 0x07, 0x0f, 0x1f, 0x3f, 0x7f, 0xff]

  enum State {   /* State of computation */
    case START
    case MIDDLE
    case END
  }







  func zuncompress(_ out : FileDescriptor, _ pre : [UInt8]) -> (UInt, UInt)? {

    var bout = UInt(0)

    /* XXX */
    compressed_pre = pre

    while true {
      let buf = UnsafeMutableRawBufferPointer.allocate(byteCount: BUFSIZE, alignment: 8)
      defer { buf.deallocate() }
      guard let bin = try? fp.read(into: buf) else {
        return nil
      }
      if bin == 0 { break }
      guard gzip.options.tflag else {
        return nil
      }

      guard let _ = try? out.write( buf[0..<bin] ) else {
        return nil
      }
      bout += UInt(bin)
    }

    let compressed_bytes = total_compressed_bytes
    return (bout, compressed_bytes)
  }

  func zclose() -> Int {
    /* We leave the caller to close the fd passed to zdopen() */
    return 0;
  }

  static func zdopen( _ gzip : gzip, _ fd : FileDescriptor) -> s_zstate {
    return s_zstate(gzip, fd)
    //      return funopen(zs, zread, nil, nil, zclose);
  }

  init(_ gzip : gzip, _ fd : FileDescriptor) {
    state = .START

    self.gzip = gzip

    /* XXX we can get rid of some of these */
    hsize = Self.HSIZE			/* For dynamic table sizing. */
    free_ent = 0			/* First unused entry. */
    block_compress = true
    clear_flg = false			/* XXX we calloc()'d this structure why = 0? */
    ratio = 0
    checkpoint = CHECK_GAP
    in_count = 1			/* Length of input. */
    out_count = 0			/* # of codes output (for debugging). */

    roffset = 0
    size = 0

    /*
     * Layering compress on top of stdio in order to provide buffering,
     * and ensure that reads and write work with the data specified.
     */


    fp = fd
  }

  /*
   * Decompress read.  This routine adapts to the codes in the file building
   * the "string" table on-the-fly; requiring no table to be stored in the
   * compressed file.  The tables used herein are shared with those of the
   * compress() routine.  See the definitions above.
   */
  func zread(_ rbp : inout [UInt8], _ num : Int) -> Int? {
    //    u_int count, i;
    //    u_char *bp, header[3];

    if (num == 0) {
      return (0);
    }

    var count = num;
    var bp = 0
    var gotomiddle = state == .MIDDLE
    switch state {
      case .START:
        state = .MIDDLE
        break;
      case .MIDDLE:
        gotomiddle = true
      case .END:
        return num - count
    }



    if !gotomiddle {

      var header = compressed_pre.prefix(3)
      compressed_pre.removeFirst(header.count)
      /* Check the magic number */

      if header.count < 3 {
        guard let header2 = try? fp.readUpToCount(3-header.count) else {
          errno = EFTYPE
          return nil
        }
        header.append(contentsOf: header2)
      }

      guard Array(header.prefix(magic_header.count)) == magic_header else {
        errno = EFTYPE
        return nil
      }

      total_compressed_bytes = 0
      maxbits = Int(header[magic_header.count]);	/* Set -b from file. */
      block_compress = 0 != (maxbits & BLOCK_MASK)
      maxbits &= BIT_MASK;
      maxmaxcode = 1 << maxbits;
      if (maxbits > Self.BITS || maxbits < 12) {
        errno = EFTYPE;
        return (-1);
      }
      /* As above, initialize the first 256 entries in the table. */
      n_bits = INIT_BITS
      maxcode = MAXCODE(n_bits)
      for i in 0..<256 {
        codetab[i] = 0
        htab[i] = UInt8(i)
      }
      free_ent = block_compress ? FIRST : 256

      oldcode = nil
      stackp = 1 << Self.BITS // de_stack
    }

    while true {

      if !gotomiddle {
        guard var code = getcode() else {
          break
        }

        if code == CLEAR && block_compress {
          for i in 0..<256 {
            codetab[i] = 0
          }
          clear_flg = true
          free_ent = FIRST
          oldcode = nil
          continue
        }
        incode = code;

        /* Special case for KwKwK string. */
        if code >= free_ent {
          // FIXME: is this right?
          guard code <= free_ent else {
            /* Bad stream. */
            errno = EFTYPE
            return nil
          }
          guard let oldcode else {
            errno = EFTYPE
            return nil
          }
          htab[stackp] = finchar // *stackp++ = finchar;
          stackp += 1
          code = oldcode
        }
        /*
         * The above condition ensures that code < free_ent.
         * The construction of tab_prefixof in turn guarantees that
         * each iteration decreases code and therefore stack usage is
         * bound by 1 << BITS - 256.
         */

        /* Generate output characters in reverse order. */
        while (code >= 256) {
          htab[stackp] = htab[code]
          stackp += 1
          code = s_zstate.code_int(codetab[code])
        }
        htab[stackp] = htab[code]
        finchar = htab[code]
        stackp += 1
      }
      /* And put them out in forward order.  */
    middle:
      repeat {
        if count == 0 {
          return num
        }
        count -= 1
        stackp -= 1
        rbp[bp] = htab[stackp]
        bp += 1
      } while stackp > (1 << Self.BITS) // de_stack

      /* Generate the new entry. */
      code = free_ent
      if let oldcode, code < maxmaxcode {
        codetab[code] = UInt16(oldcode)
        htab[code] = UInt8(finchar)
        free_ent = code + 1;
      }

      /* Remember previous code. */
      oldcode = incode
    }
    state = .END

    return (num - count);
  }

  /*-
   * Read one code from the standard input.  If EOF, return -1.
   * Inputs:
   * 	stdin
   * Outputs:
   * 	code or -1 is returned.
   */
  func getcode() -> code_int? {
    //    code_int gcode;
    //    int r_off, bits, i;
    //    char_type *bp;

    var bp = 0
    if clear_flg || roffset >= size || free_ent > maxcode {
      /*
       * If the next entry will be too big for the current gcode
       * size, then we must increase the size.  This implies reading
       * a new buffer full, too.
       */
      if free_ent > maxcode {
        n_bits += 1
        if (n_bits == maxbits) {	/* Won't get any bigger now. */
          maxcode = maxmaxcode
        }
        else {
          maxcode = MAXCODE(n_bits)
        }
      }
      if clear_flg {
        n_bits = INIT_BITS
        maxcode = MAXCODE(n_bits)
        clear_flg = false
      }
      /* XXX */
      var i = 0
      while i < n_bits && compressed_pre.count != 0 {
        gbuf[i] = compressed_pre.removeFirst()
      }
      guard let s = try? fp.read(into: withUnsafeMutableBytes(of: &gbuf[i...]) { $0 } ) else {
        return nil
      }
      size = s + i
      roffset = 0

      total_compressed_bytes += UInt(size)

      /* Round size down to integral number of codes. */
      size = (size << 3) - (n_bits - 1)
    }
    var r_off = roffset
    var bits = n_bits

    /* Get to the first byte. */
    bp += (r_off >> 3)
    r_off &= 7;

    /* Get first part (low order bits). */
    var gcode = Int(gbuf[bp]) >> r_off
    bp += 1

    bits -= (8 - r_off);
    r_off = 8 - r_off;	/* Now, roffset into gcode word. */

    /* Get any 8 bit parts in the middle (<=1 for up to 16 bits). */
    if (bits >= 8) {
      gcode |= Int(gbuf[bp]) << r_off
      bp += 1
      r_off += 8
      bits -= 8
    }

    /* High order bits. */
    gcode |= Int(gbuf[bp] & rmask[bits]) << r_off
    roffset += n_bits;

    return gcode
  }
}
