// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using an LLM
// from a file containing the following notice:

/*

 Copyright (c) 2017 Dell EMC
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.
*/

import ShellTesting
import CMigration
import Darwin

struct statTest : ShellTest {
  var cmd = "stat"
  var suiteBundle = "file_cmds_statTest"

  @Test("Verify the output format for -F") func F_flag() async throws {
    let a = try tmpfile("a", "")
    let b = try tmpdir("b")
    let c = try tmpfile("c", "") // ??
    let d = try tmpfile("d")
    let f = try tmpfile("f")

    try d.createSymbolicLink(to: a)

    mkfifo(f.string, 0777)

    defer { rm(a,b,c,d,f) }

    try await run(output: /a$/, args: ["-Fn", a] )
    try await run(output: /b\/$/, args: ["-Fn", b] )
    try await run(output: /c$/, args: ["-Fn", c] )
    try await run(output: /d@ ->\ /, args: ["-Fn", d] )
    try await run(output: /f\|$/, args: ["-Fn", f] )
  }

  @Test("Verify that -n suppresses newline output for lines") func n_flag() async throws {
    let a = try tmpfile("a3", "")
    let b = try tmpfile("b3", "")
    defer { rm(a,b) }
    let po = try await DarwinProcess().run("/usr/bin/stat", args: a,b)
    #expect (po.code == 0)
    let oo = try po.string(encoded: .utf8).replacing("\n", with: "")
    try await run(output: oo, args: "-n", a, b)
  }

  @Test("Verify the output format for -l") func l_flag() async throws {
    let a = try tmpfile("a2", "")
    let b = try tmpfile("b2")
    rm(b)
    try b.createHardLink(to: a)
    let c = try tmpfile("c2", "")
    let d = try tmpdir("d2")

    defer { rm(a,b,c,d) }

    for x in [a,b,c,d] {
      let po1 = try await DarwinProcess().run("/bin/ls", args: "-ldT", x)
      try await run(args: "-l", x) { po2 in
        let s = try po1.string(encoded: .utf8)
        let t = try po2.string(encoded: .utf8)
        #expect (s.replacing( /[:space:]+/, with: " ") ==
                 t.replacing( /[:space:]+/, with: " ") )
        #expect (po1.code == po2.code)
      }
    }
  }

  @Test("Verify that -q suppresses error message from l?stat(2)") func q_flag() async throws {
    let nonexistent = try tmpfile("nonexistent")
    let broken = try tmpfile("broken-link")
    defer { rm(nonexistent, broken) }
    try broken.createSymbolicLink(to: nonexistent)
    try await run(status: 1, args: "-q", nonexistent)
    try await run(output: /.+/, args: "-q", broken)
    try await run(output: /.+/, args: "-qL", broken)
  }

  @Test("Verify that -r display output in 'raw mode'") func r_flag() async throws {
    let a = try tmpfile("a5", "")
    defer { rm(a) }
    try await run(output: /((\d)+ ){15}/, args: "-r", a)
  }

  @Test("Verify the output format for -s") func s_flag() async throws {
    let a = try tmpfile("a4", "")
    let b = try tmpfile("b4")
    rm(b)
    try b.createHardLink(to: a)
    let c = try tmpfile("c4")
    try c.createSymbolicLink(to: a)
    let d = try tmpdir("d4")
    defer { rm(a, b, c, d) }
    let otp = /(st_dev=\d+ st_ino=\d+ st_mode=\d+ st_nlink=\d+ st_uid=\d+ st_gid=\d+ st_rdev=\d+ st_size=\d+ st_atime=\d+ st_mtime=\d+ st_ctime=\d+ st_birthtime=\d+ st_blksize=\d+ st_blocks=\d+ st_flags=\d+\n){4}/
    try await run(output: otp, args: "-s", a, b, c, d)
  }

  @Test("Verify the output format for -t") func t_flag() async throws {

    let foo = try tmpfile("foo", "")
    defer { rm(foo) }
    // FIXME: the defaultl timezone is not handled properly?
    let po = try await DarwinProcess().run("/usr/bin/touch", args: "-d", "1970-01-01T00:00:42", foo, env: ["TZ": "America/NewYork"])

    try await run(output: "1970-01-01 00:00:42\n", args: "-t", "%F %H:%M:%S", "-f", "%Sa", foo, env: ["TZ": "America/NewYork"])
    // FIXME: this test fails because the ShellProcess (touch) and the stat executable are not using the same timezone for times
    // however, the above command works properly -- so the time formatting is handling the discrepancy?

    try await run(output: "42\n", args: "-t", "%s", "-f", "%a", foo, env: ["TZ": "America/NewYork"  ] )
  }

  @Test("Verify the output format for -x") func x_flag() async throws {
    let a = try tmpfile("a6", "")
    let b = try tmpfile("b6")
    rm(b)
    try b.createHardLink(to: a)
    let c = try tmpfile("c6")
    try c.createSymbolicLink(to: a)
    let d = try tmpdir("d6")
    defer { rm(a, b, c, d) }

    // FIXME: the cheat here is to compare the command built by the project ot the installed command
    // the original command basically formatted the resault using the stat command for each element.
    // as long as you're assuming the stat command is installed, just compare to its output?
    for i in [a,b,c,d] {
      // FIXME: I need to do the relativePath thingy because `run` resolves URLs that way -- but ShellProcess doesn't resolve URLs in arguments
      // Need to make them the same
      // FIXME: i.relativePath
      let po = try await DarwinProcess().run("/usr/bin/stat", args: "-x", i, cd: a.removingLastComponent() )
      try await run(output: po.string(encoded: .utf8), args: "-x", i)
    }


  }
}

// =============================================================================================

// FIXME: use this instead of the 'touch' command above?
func touchDate(
    _ path: String,
    seconds: Int,
    nanoseconds: Int = 0
) throws {
    var times = [
        timespec(tv_sec: seconds, tv_nsec: nanoseconds), // atime
        timespec(tv_sec: seconds, tv_nsec: nanoseconds)  // mtime
    ]

    if utimensat(AT_FDCWD, path, &times, 0) != 0 {
        throw POSIXErrno(errno)
    }
}
