// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2012, 2013 SRI International
 * Copyright (c) 1987, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin
import CommonCrypto

extension xinstall {
/*
 * compare --
 *  Compare two files; non-zero means files differ.
 *  Compute digest and return its address in *dresp
 *  unless it points to pre-computed digest.
 */
func compare(_ from_fd : FileDescriptor, _ from_name : String, _ from_len : size_t,
             _ to_fd : FileDescriptor, _ to_name : String, _ to_len : size_t,
             _ dresp : inout String)
{
  int rv;
  int do_digest;
  DIGEST_CTX ctx;

  if (from_len != to_len) {
    return 1;
  }

  do_digest = (digesttype != DIGEST_NONE && dresp != NULL &&
               *dresp == NULL);
  if (from_len <= MAX_CMP_SIZE) {
    static char *buf, *buf1, *buf2;
    static size_t bufsize;
    int n1, n2;

    if (do_digest) {
      digest_init(&ctx);
    }

    if (buf == NULL) {
      /*
       * Note that buf and bufsize are static. If
       * malloc() fails, it will fail at the start
       * and not copy only some files.
       */
      if (sysconf(_SC_PHYS_PAGES) > PHYSPAGES_THRESHOLD) {
        bufsize = MIN(BUFSIZE_MAX, MAXPHYS * 8);
      }
      else {
        bufsize = BUFSIZE_SMALL;
      }
      buf = malloc(bufsize * 2);
      if (buf == NULL) {
        err(1, "Not enough memory");
      }
      buf1 = buf;
      buf2 = buf + bufsize;
    }
    rv = 0;
    lseek(from_fd, 0, SEEK_SET);
    lseek(to_fd, 0, SEEK_SET);
    while (rv == 0) {
      n1 = read(from_fd, buf1, bufsize);
      if (n1 == 0){
        break;    /* EOF */
      }
      else if (n1 > 0) {
        n2 = read(to_fd, buf2, n1);
        if (n2 == n1) {
          rv = memcmp(buf1, buf2, n1);
        }
        else {
          rv = 1;  /* out of sync */
        }
      } else {
        rv = 1;    /* read failure */
      }
      if (do_digest) {
        digest_update(&ctx, buf1, n1);
      }
    }
    lseek(from_fd, 0, SEEK_SET);
    lseek(to_fd, 0, SEEK_SET);
  } else {
    rv = 1;  /* don't bother in this case */
  }

  if (do_digest) {
    if (rv == 0) {
      *dresp = digest_end(&ctx, NULL);
    }
    else {
      (void)digest_end(&ctx, NULL);
    }
  }

  return rv;
}

/*
 * create_tempfile --
 *  create a temporary file based on path and open it
 */
func create_tempfile(_ path : String, _ temp : String, _ tsize : size_t) {
  char *p;

  (void)strncpy(temp, path, tsize);
  temp[tsize - 1] = '\0';
  if ((p = strrchr(temp, '/')) != NULL) {
    p++;
  }
  else {
    p = temp;
  }
  (void)strncpy(p, "INS@XXXXXX", &temp[tsize - 1] - p);
  temp[tsize - 1] = '\0';
  return (mkstemp(temp));
}

/*
 * copy --
 *  copy from one file to another
 */
func copy(_ from_fd : FileDescriptor, _ from_name : String, _ to_fd : FileDescriptor, _ to_name : String, _ size : off_t) -> [UInt8] {
  static char *buf = NULL;
  static size_t bufsize;
  int nr, nw;
  int serrno;
  //    #ifndef BOOTSTRAP_XINSTALL
  ssize_t ret;
  // #endif
  DIGEST_CTX ctx;

  /* Rewind file descriptors. */
  if (lseek(from_fd, 0, SEEK_SET) < 0) {
    err(EX_OSERR, "lseek: %s", from_name);
  }
  if (lseek(to_fd, 0, SEEK_SET) < 0) {
    err(EX_OSERR, "lseek: %s", to_name);
  }

  //    #ifndef BOOTSTRAP_XINSTALL
  /* Try copy_file_range() if no digest is requested */
  if (digesttype == DIGEST_NONE) {

    ret = fcopyfile(from_fd, to_fd, NULL,
                    COPYFILE_DATA | COPYFILE_DATA_SPARSE);

    if (ret == 0) {
      goto done;
    }

    if (errno != ENOTSUP) {

      serrno = errno;
      (void)unlink(to_name);
      errno = serrno;
      err(EX_OSERR, "%s", to_name);
    }
    /* Fall back */
  }
  // #endif
  digest_init(&ctx);

  if (buf == NULL) {
    /*
     * Note that buf and bufsize are static. If
     * malloc() fails, it will fail at the start
     * and not copy only some files.
     */
    if (sysconf(_SC_PHYS_PAGES) > PHYSPAGES_THRESHOLD) {
      bufsize = MIN(BUFSIZE_MAX, MAXPHYS * 8);
    }
    else {
      bufsize = BUFSIZE_SMALL;
    }
    buf = malloc(bufsize);
    if (buf == NULL) {
      err(1, "Not enough memory");
    }
  }
  while ((nr = read(from_fd, buf, bufsize)) > 0) {
    if ((nw = write(to_fd, buf, nr)) != nr) {
      serrno = errno;
      (void)unlink(to_name);
      if (nw >= 0) {
        errx(EX_OSERR,
             "short write to %s: %jd bytes written, "
             "%jd bytes asked to write",
             to_name, (uintmax_t)nw,
             (uintmax_t)size);
      } else {
        errno = serrno;
        err(EX_OSERR, "%s", to_name);
      }
    }
    digest_update(&ctx, buf, nr);
  }
  if (nr != 0) {
    serrno = errno;
    (void)unlink(to_name);
    errno = serrno;
    err(EX_OSERR, "%s", from_name);
  }
done:
  if (safecopy && fsync(to_fd) == -1) {
    serrno = errno;
    (void)unlink(to_name);
    errno = serrno;
    err(EX_OSERR, "fsync failed for %s", to_name);
  }
  return (digest_end(&ctx, NULL));
}

/*
 * strip --
 *  Use strip(1) to strip the target file.
 *  Just invoke strip(1) on to_name if from_name is NULL, else try
 *  to run "strip -o to_name from_name" and return 0 on failure.
 *  Return 1 on success and assign result of digest_file(to_name)
 *  to *dresp.
 */
func strip(_ to_name : String, _ to_fd : FileDescriptor, _ from_name : String?, _ dresp : inout String) -> Bool {
  const char *stripbin;
  const char *args[5];
  char *prefixed_from_name;
  pid_t pid;
  int error, serrno, status;

  prefixed_from_name = NULL;
  stripbin = Environment["STRIPBIN"] ?? "strip"

  args[0] = stripbin;
  if (from_name == NULL) {
    args[1] = to_name;
    args[2] = NULL;
  } else {
    args[1] = "-o";
    args[2] = to_name;

    /* Prepend './' if from_name begins with '-' */
    if (from_name[0] == '-') {
      if (asprintf(&prefixed_from_name, "./%s", from_name) == -1) {
        return (0);
      }
      args[3] = prefixed_from_name;
    } else {
      args[3] = from_name;
    }
    args[4] = NULL;
  }
  error = posix_spawnp(&pid, stripbin, NULL, NULL,
                       __DECONST(char **, args), environ);
  if (error != 0) {
    unlink(to_name)
    errc(error == EAGAIN || error == EPROCLIM || error == ENOMEM ?
         EX_TEMPFAIL : EX_OSERR, error, "spawn %s", stripbin);
  }
  free(prefixed_from_name);
  if (waitpid(pid, &status, 0) == -1) {
    error = errno;
    (void)unlink(to_name);
    errc(EX_SOFTWARE, error, "wait");
    /* NOTREACHED */
  }
  if (status != 0) {
    if let from_name {
      return false
    }
    unlink(to_name)
    errx(Int(EX_SOFTWARE), "strip command \(stripbin) failed on \(to_name)")
  }
  if let from_name, safecopy, fsync(to_fd) == -1 {
    let serrno = errno
    unlink(to_name)
    errno = serrno
    err(Int(EX_OSERR), "fsync failed for \(to_name)")
  }
  if (dresp != nil) {
    *dresp = digest_file(to_name);
  }
  return true
}

/*
 * install_dir --
 *  build directory hierarchy
 */
func install_dir(_ pathx : String) {

  var path = ""
  for p in pathx.split(separator: "/") {
    var tried_mkdir = false
    path.append("/")
    path.append(contentsOf: p)
  again:
    while true {
      do {
        let sb = try FileMetadata(for: path)
        if sb.filetype == .directory {
          errx(Int(EX_OSERR), "\(path) exists but is not a directory")
        }
      } catch(let e) {
        if e.code != ENOENT || tried_mkdir {
          err(Int(EX_OSERR), "stat \(path)")
        }
        if (mkdir(path, 0o0755) < 0) {
          tried_mkdir = true
          if errno == EEXIST {
            continue again
          }
          err(Int(EX_OSERR), "mkdir \(path)")
        }
        if options.verbose != 0 {
          print("install: mkdir \(path)")
        }
      }
      break again
    }
  }

  if !options.dounpriv {
    let u = options.uid == nil ? -1 : uid_t(options.uid!)
    let g = options.gid == nil ? -1 : gid_t(options.gid!)

    if (options.gid != nil || options.uid != nil) && 0 != chown(path, u, g) {
      warn("chown \(u):\(g) \(path)")
    }
    /* XXXBED: should we do the chmod in the dounpriv case? */
    if (chmod(path, mode)) {
      warn("chmod %o \(path)", mode)
    }
  }
  metadata_log(path, "dir", nil, nil, nil, 0);
}

/*
 * metadata_log --
 *  if metafp is not NULL, output mtree(8) full path name and settings to
 *  metafp, to allow permissions to be set correctly by other tools,
 *  or to allow integrity checks to be performed.
 */
func metadata_log(_ path : String, _ type : String, _ ts : timespec?,
                  _ slink : String? , _ digestresult : [UInt8]?, _ size : off_t) {
  let extra = [ " ", "\t", "\n", "\\", "#", "\0"]

  /*    const char *p;
   char *buf;
   size_t buflen, destlen;
   struct flock metalog_lock;
   */

  guard var metafp = options.metafp else {
    return
  }

  /* Buffer for strsnvis(3), used for both path and slink. */
  buflen = strlen(path);
  if (slink && strlen(slink) > buflen) {
    buflen = strlen(slink);
  }
  buflen = 4 * buflen + 1;
  if ((buf = malloc(buflen)) == NULL) {
    warn(NULL);
    return;
  }

  /* Lock log file. */
  metalog_lock.l_start = 0;
  metalog_lock.l_len = 0;
  metalog_lock.l_whence = SEEK_SET;
  metalog_lock.l_type = F_WRLCK;
  if (fcntl(fileno(metafp), F_SETLKW, &metalog_lock) == -1) {
    warn("can't lock %s", metafile);
    free(buf);
    return;
  }

  /* Remove destdir. */
  p = path;
  if (destdir) {
    destlen = strlen(destdir);
    if (strncmp(p, destdir, destlen) == 0 &&
        (p[destlen] == '/' || p[destlen] == '\0')) {
      p += destlen;
    }
  }
  while (*p && *p == '/') {
    p++;
  }
  strsnvis(buf, buflen, p, VIS_OCTAL, extra);
  p = buf;
  /* Print details. */
  fprintf(metafp, ".%s%s type=%s", *p ? "/" : "", p, type);
  if (owner) {
    fprintf(metafp, " uname=%s", owner);
  }
  if (group) {
    fprintf(metafp, " gname=%s", group);
  }
  fprintf(metafp, " mode=%#o", mode);
  if (slink) {
    strsnvis(buf, buflen, slink, VIS_CSTYLE, extra);
    fprintf(metafp, " link=%s", buf);
  }
  if (*type == 'f') { /* type=file */
    fprintf(metafp, " size=%lld", (long long)size);
  }
  if (ts != NULL && dopreserve) {
    fprintf(metafp, " time=%lld.%09ld",
            (long long)ts[1].tv_sec, ts[1].tv_nsec);
  }
  if (digestresult && digest) {
    fprintf(metafp, " \(digest)=\(digestresult)")
  }
  if (fflags) {
    fprintf(metafp, " flags=\(fflags)")
  }
  if (tags) {
    fprintf(metafp, " tags=\(tags)")
  }
  print("", to: &metafp)
  /* Flush line. */
//    fflush(metafp);

  /* Unlock log file. */
  metalog_lock.l_type = F_UNLCK;
  if (fcntl(fileno(metafp), F_SETLKW, &metalog_lock) == -1) {
    warn("can't unlock %s", metafile);
  }
  free(buf);
}

}
