// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2012, 2013 SRI International
 * Copyright (c) 1987, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin
import CommonCrypto


let BACKUP_SUFFIX = ".old"

@main struct xinstall : ShellCommand {

  /*
   * Memory strategy threshold, in pages: if physmem is larger than this, use a
   * large buffer.
   */
  let PHYSPAGES_THRESHOLD = 32*1024

  /* Maximum buffer size in bytes - do not allow it to grow larger than this. */
  let BUFSIZE_MAX = 2*1024*1024

  /*
   * Small (default) buffer size in bytes. It's inefficient for this to be
   * smaller than MAXPHYS.
   */
  let BUFSIZE_SMALL = MAXPHYS

  /*
   * We need to build xinstall during the bootstrap stage when building on a
   * non-FreeBSD system. Linux does not have the st_flags and st_birthtime
   * members in struct stat so we need to omit support for changing those fields.
   */

  let MAX_CMP_SIZE = 16 * 1024 * 1024

  struct LinkTypes : OptionSet {
    var rawValue : UInt32

    static var ABSOLUTE = Self(rawValue: 0x01)
    static var RELATIVE = Self(rawValue: 0x02)
    static var HARD = Self(rawValue: 0x04)
    static var SYMBOLIC = Self(rawValue: 0x08)
    static var MIXED = Self(rawValue: 0x10)
  }

  let DIRECTORY : UInt32 = 0x01		/* Tell install it's a directory. */
  let SETFLAGS	: UInt32 = 0x02		/* Tell install to set flags. */
  let NOCHANGEBITS : FileFlags = [.UF_IMMUTABLE, .UF_APPEND, .SF_IMMUTABLE, .SF_APPEND]

  /*
   typedef union {
   #ifdef WITH_DIGESTS
   #ifdef WITH_MD5
   MD5_CTX		MD5;
   #endif
   #ifdef WITH_RIPEMD160
   RIPEMD160_CTX	RIPEMD160;
   #endif
   SHA1_CTX	SHA1;
   SHA256_CTX	SHA256;
   SHA512_CTX	SHA512;
   #endif /* WITH_DIGESTS */
   }	DIGEST_CTX;
   */

  enum Digest : Int32 {
    case NONE = 0
    case SHA1
    case SHA256
    case SHA512

    init?(_ s : String) {
      switch s {
        case "none": self = .NONE
        case "sha1": self = .SHA1
        case "sha256": self = .SHA256
        case "sha512": self = .SHA512
        default: return nil
      }
    }
  }

  struct CommandOptions {
    var gid : UInt?
    var uid : UInt?
    var dobackup = false
    var docompare = false
    var dodir = false
    var dolink = LinkTypes()
    var dopreserve = false
    var dostrip = false
    var dounpriv = false
    var safecopy = false
    var verbose = 0

    var haveopt_f = false
    var haveopt_g = false
    var haveopt_m = false
    var haveopt_o = false

    var digesttype = Digest.NONE

    var owner : String?
    var group : String?
    var digest : String?
    var fflags : String?
    var metafile : String?
    var tags : String?

    var destdir : String?
    var suffix = BACKUP_SUFFIX

    var metafp : FileDescriptor?


    var args : [String] = []
  }
  /*
   static FILE *metafp;
   static const char *group, *owner;
   #ifdef WITH_DIGESTS
   static char *destdir, *digest, *fflags, *metafile, *tags;
   #else
   static char *destdir, *fflags, *metafile, *tags;
   #endif
   */


  /*
   * Replace the digest_* functions with the DIGEST_NONE equivalents.  init and
   * update will do nothing, while end returns NULL.
   */

  /* Uses param to avoid warnings. */
  /*
   #define	digest_init(c)		((void)c)
   #define	digest_update(c, d, l)
   #define	digest_file(n)		(NULL)
   #define	digest_end(c, b)	(NULL)
   #endif
   */

  func uid_from_user(_ name : String) -> UInt? {
    if let pp = getpwnam(name) {
      return UInt(pp.pointee.pw_uid)
    }
    /* The caller will attempt numeric conversion. */
    return nil
  }

  func gid_from_group(_ name : String) -> UInt? {
    if let gp = getgrnam(name) {
      return UInt(gp.pointee.gr_gid)
    }
    /* The caller will attempt numeric conversion. */
    return nil
  }

  var options : CommandOptions!

  func parseOptions() throws(CmdErr) -> CommandOptions {
    /*    struct stat from_sb, to_sb;
     mode_t *set;
     u_long fset;
     int ch, no_target;
     u_int iflags;
     char *p;
     const char *to_name;

     fset = 0;
     iflags = 0;
     set = NULL;
     group = owner = NULL;
     */

    var setx : UnsafeMutableRawPointer?

    var options = CommandOptions()
    let go = BSDGetopt("B:bCcD:df:g:h:l:M:m:N:o:pSsT:Uv")
    while let (k,v) = try go.getopt() {
      switch k {
        case "B":
          options.suffix = v
          fallthrough
        case "b":
          options.dobackup = true

        case "C":
          options.docompare = true
        case "c":
          /* For backwards compatibility. */
          break
        case "D":
          options.destdir = v
        case "d":
          options.dodir = true
        case "f":
          options.haveopt_f = true
          options.fflags = v
        case "g":
          options.haveopt_g = true
          options.group = v
        case "h":
          options.digest = v
        case "l":
          for p in v {
            switch p {
              case "s":
                options.dolink.remove([.HARD, .MIXED])
                options.dolink.insert(.SYMBOLIC)
              case "h":
                options.dolink.remove([.SYMBOLIC, .MIXED])
                options.dolink.insert(.HARD)
              case "m":
                options.dolink.remove([.SYMBOLIC, .HARD])
                options.dolink.insert(.MIXED)
              case "a":
                options.dolink.remove(.RELATIVE)
                options.dolink.insert(.ABSOLUTE)
              case "r":
                options.dolink.remove(.ABSOLUTE)
                options.dolink.insert(.RELATIVE)
              default:
                errx(1, "\(p): invalid link type")
            }
          }
        case "M":
          options.metafile = v
        case "m":
          options.haveopt_m = true
          guard let s = setmode(v) else {
            errx(Int(EX_USAGE), "invalid file mode: \(v)")
          }
          setx = s

        case "o":
          options.haveopt_o = true
          options.owner = v
        case "p":
          options.docompare = true
          options.dopreserve = true
        case "S":
          options.safecopy = true
        case "s":
          options.dostrip = true
        case "T":
          options.tags = v
        case "U":
          options.dounpriv = true
        case "v":
          options.verbose = 1
        case "?":
          fallthrough
        default:
          throw CmdErr(1)
      }
    }
    options.args = go.remaining

    /* some options make no sense when creating directories */
    if options.dostrip && options.dodir {
      throw CmdErr(1, "-d and -s may not be specified together")
    }

    /*
     * Default permissions based on whether we're a directory or not, since
     * an +X may mean that we need to set the execute bit.
     */
    if let setx {
      mode = getmode(setx, options.dodir ? FileType.directory.rawValue : 0) // & ~S_IFDIR;
    }
    free(setx)

    if let _ = Environment["DONTSTRIP"] {
      warnx("DONTSTRIP set - will not strip installed binaries");
      options.dostrip = false
    }

    /* must have at least two arguments, except when creating directories */
    if options.args.isEmpty || (options.args.count == 1 && !options.dodir) {
      throw CmdErr(1)
    }


    if let d = options.digest {
      if let x = Digest(d) {
        options.digesttype = x
      } else {
        throw CmdErr(1, "unknown digest '\(d)'")
      }
    }


    /* get group and owner id's */
    if let g = options.group,
       !options.dounpriv {
      if let gid = gid_from_group(g) {
        options.gid = gid
      } else {
        guard let id = parseid(g) else {
          errx(1, "unknown group \(g)")
          fatalError()
        }
        options.gid = id
      }
    } else {
      options.gid = nil
    }

    if let o = options.owner,
       !options.dounpriv {
      if (uid_from_user(owner, &uid) == -1) {
        id_t id;
        if (!parseid(owner, &id)) {
          errx(1, "unknown user %s", owner);
        }
        options.uid = id
      }
    } else {
      options.uid = nil
    }

    if let ff = options.fflags,
       !options.dounpriv {
      if (strtofflags(ff, &fset, NULL)) {
        errx(EX_USAGE, "\(fflags): invalid flag")
      }
      options.iflags |= SETFLAGS;
    }

    if let m = options.metafile {

    } else {
      options.digesttype = .NONE
    }

    if let m = options.metafile {
      if let metafp = try? FileDescriptor.open(m, .writeOnly, options: [.append] ) {
        options.metafp = metafp
      } else {
        warn("open \(m)")
      }
    }

    return options
  }


  func runCommand() async throws(CmdErr) {


    if options.dodir {
      for argv in options.args {
        install_dir(argv)
      }
      exit(EX_OK);
    }

    var to_name = options.args.last!
    var to_sb = try? FileMetadata(for: to_name)
    if to_sb != nil, to_sb!.filetype == .directory {
      if options.dolink.contains(.SYMBOLIC) {
        to_sb = try? FileMetadata(for: to_name, followSymlinks: false)
        guard let to_sb else {
          err(Int(EX_OSERR), "\(to_name) vanished")
        }
        if to_sb.filetype == .symbolicLink {
          if options.args.count != 2 {
            errc(Int(EX_CANTCREAT), ENOTDIR, to_name)
          }
          install(options.args[0], to_name, fset, iflags);
          exit(EX_OK);
        }
      }
      for argv in options.args.dropLast() {
        install(argv, to_name, fset, iflags | DIRECTORY)
      }
      exit(EX_OK);
    }

    /* can't do file1 file2 directory/file */
    if options.args.count != 2 {
      if to_sb == nil {
        warnx("target directory '\(to_name)' does not exist")
      }
      else {
        warnx("target `\(to_name)' is not a directory")
      }
      throw CmdErr(1, usage)
    }

    if to_sb != nil && options.dolink.isEmpty {
      let argv = options.args[0]
      guard let from_sb = try? FileMetadata(for: argv) else {
        err(Int(EX_OSERR), argv)
      }
      if to_sb!.filetype != .regular {
        errno = EFTYPE
        err(Int(EX_OSERR), to_name)
      }
      if to_sb!.device == from_sb.device && to_sb!.inode == from_sb.inode {
        errx(Int(EX_USAGE), "\(argv) and \(to_name) are the same file")
      }
    }
    install(argv, to_name, fset, iflags)
    exit(EX_OK)
    /* NOTREACHED */
  }

  func digest_file(_ name : String) -> [UInt8]? {
    switch options.digesttype {
      case .SHA1:
        return (SHA1_File(name, NULL));
      case .SHA256:
        return (SHA256_File(name, NULL));
      case .SHA512:
        return (SHA512_File(name, NULL));
      default:
        return nil
    }
  }

  func digest_init(_ c : DIGEST_CTX) {

    switch (digesttype) {
      case DIGEST_NONE:
        break;


      case DIGEST_SHA1:
        SHA1_Init(&(c->SHA1));
        break;
      case DIGEST_SHA256:
        SHA256_Init(&(c->SHA256));
        break;
      case DIGEST_SHA512:
        SHA512_Init(&(c->SHA512));
        break;
    }
  }

  func digest_update(_ c : DIGEST_CTX, _ data : [UInt8], _ len : size_t) {
    switch options.digesttype {
      case .NONE:
        break;


      case .SHA1:
        SHA1_Update(&(c->SHA1), data, len);
        break;
      case .SHA256:
        SHA256_Update(&(c->SHA256), data, len);
        break;
      case .SHA512:
        SHA512_Update(&(c->SHA512), data, len);
        break;
    }
  }

  func digest_end(_ c : DIGEST_CTX, _ buf : [UInt8]) -> [UInt8]? {
    switch options.digesttype {
      case .SHA1:
        return (SHA1_End(&(c->SHA1), buf));
      case .SHA256:
        return (SHA256_End(&(c->SHA256), buf));
      case .SHA512:
        return (SHA512_End(&(c->SHA512), buf));
      default:
        return nil
    }
  }

  /*
   * parseid --
   *	parse uid or gid from arg into id, returning non-zero if successful
   */
  func parseid(_ name : String) -> UInt? {
    return UInt(name)
  }

  /*
   * quiet_mktemp --
   *	mktemp implementation used mkstemp to avoid mktemp warnings.  We
   *	really do need mktemp semantics here as we will be creating a link.
   */
  func quiet_mktemp(_ template : String) -> String? {
    guard var k = strdup(template) else {
      fatalError("not enough memory to create filename")
    }
    defer { free(k) }
    let fd = mkstemp(&k)
    if fd < 0 {
      return nil
    }
    close(fd)
    if unlink(k) == -1 {
      err(Int(EX_OSERR), "unlink \(k)")
    }
    return String(cString: k)
  }

  /*
   * do_link --
   *	make a hard link, obeying dorename if set
   *	return -1 on failure
   */
  func do_link(_ from_name : String, _ to_name : String, _ target_sb : FileMetadata?) -> Int {
    char tmpl[MAXPATHLEN];
    int ret;

    if (target_sb != NULL) {
      (void)snprintf(tmpl, sizeof(tmpl), "%s.inst.XXXXXX", to_name);
      /* This usage is safe. */
      if (quiet_mktemp(tmpl) == NULL) {
        err(EX_OSERR, "%s: mktemp", tmpl);
      }
      ret = link(from_name, tmpl);
      if (ret == 0) {
        if (target_sb->st_mode & S_IFDIR && rmdir(to_name) ==
            -1) {
          unlink(tmpl);
          err(EX_OSERR, "%s", to_name);
        }

        if (target_sb->st_flags & NOCHANGEBITS) {
          (void)chflags(to_name, target_sb->st_flags &
                        ~NOCHANGEBITS);
        }

        if (verbose) {
          printf("install: link %s -> %s\n",
                 from_name, to_name);
        }
        ret = rename(tmpl, to_name);
        /*
         * If rename has posix semantics, then the temporary
         * file may still exist when from_name and to_name point
         * to the same file, so unlink it unconditionally.
         */
        (void)unlink(tmpl);
      }
      return (ret);
    } else {
      if (verbose) {
        printf("install: link %s -> %s\n",
               from_name, to_name);
      }
      return (link(from_name, to_name));
    }
  }

  /*
   * do_symlink --
   *	Make a symbolic link, obeying dorename if set. Exit on failure.
   */
  func do_symlink(_ from_name : String, _ to_name : String, _ target_sb : FileMetadata?) {
    char tmpl[MAXPATHLEN];

    if (target_sb != NULL) {
      (void)snprintf(tmpl, sizeof(tmpl), "%s.inst.XXXXXX", to_name);
      /* This usage is safe. */
      if (quiet_mktemp(tmpl) == NULL) {
        err(EX_OSERR, "%s: mktemp", tmpl);
      }

      if (symlink(from_name, tmpl) == -1) {
        err(EX_OSERR, "symlink %s -> %s", from_name, tmpl);
      }

      if (target_sb->st_mode & S_IFDIR && rmdir(to_name) == -1) {
        (void)unlink(tmpl);
        err(EX_OSERR, "%s", to_name);
      }

      if (target_sb->st_flags & NOCHANGEBITS) {
        (void)chflags(to_name, target_sb->st_flags &
                      ~NOCHANGEBITS);
      }

      if (verbose) {
        printf("install: symlink %s -> %s\n",
               from_name, to_name);
      }
      if (rename(tmpl, to_name) == -1) {
        /* Remove temporary link before exiting. */
        (void)unlink(tmpl);
        err(EX_OSERR, "%s: rename", to_name);
      }
    } else {
      if (verbose) {
        printf("install: symlink %s -> %s\n",
               from_name, to_name);
      }
      if (symlink(from_name, to_name) == -1) {
        err(EX_OSERR, "symlink %s -> %s", from_name, to_name);
      }
    }
  }

  /*
   * makelink --
   *	make a link from source to destination
   */
  func makelink(_ from_name : String, _ to_name : String, _ target_sb : FileMetadata?) {
    char src[MAXPATHLEN], dst[MAXPATHLEN], lnk[MAXPATHLEN];
    char *to_name_copy, *d, *ld, *ls, *s;
    const char *base, *dir;
    struct stat to_sb;

    /* Try hard links first. */
    if (dolink & (LN_HARD|LN_MIXED)) {
      if (do_link(from_name, to_name, target_sb) == -1) {
        if ((dolink & LN_HARD) || errno != EXDEV) {
          err(EX_OSERR, "link %s -> %s", from_name, to_name);
        }
      } else {
        if (stat(to_name, &to_sb)) {
          err(EX_OSERR, "%s: stat", to_name);
        }
        if (S_ISREG(to_sb.st_mode)) {
          /*
           * XXX: hard links to anything other than
           * plain files are not metalogged
           */
          int omode;
          const char *oowner, *ogroup;
          char *offlags;
          char *dres;

          /*
           * XXX: use underlying perms, unless
           * overridden on command line.
           */
          omode = mode;
          if (!haveopt_m) {
            mode = (to_sb.st_mode & 0777);
          }
          oowner = owner;
          if (!haveopt_o) {
            owner = NULL;
          }
          ogroup = group;
          if (!haveopt_g) {
            group = NULL;
          }
          offlags = fflags;
          if (!haveopt_f) {
            fflags = NULL;
          }
          dres = digest_file(from_name);
          metadata_log(to_name, "file", NULL, NULL,
                       dres, to_sb.st_size);
          free(dres);
          mode = omode;
          owner = oowner;
          group = ogroup;
          fflags = offlags;
        }
        return;
      }
    }

    /* Symbolic links. */
    if (dolink & LN_ABSOLUTE) {
      /* Convert source path to absolute. */
      if (realpath(from_name, src) == NULL) {
        err(EX_OSERR, "%s: realpath", from_name);
      }
      do_symlink(src, to_name, target_sb);
      /* XXX: src may point outside of destdir */
      metadata_log(to_name, "link", NULL, src, NULL, 0);
      return;
    }

    if (dolink & LN_RELATIVE) {
      if (*from_name != '/') {
        /* this is already a relative link */
        do_symlink(from_name, to_name, target_sb);
        /* XXX: from_name may point outside of destdir. */
        metadata_log(to_name, "link", NULL, from_name, NULL, 0);
        return;
      }

      /* Resolve pathnames. */
      if (realpath(from_name, src) == NULL) {
        err(EX_OSERR, "%s: realpath", from_name);
      }

      /*
       * The last component of to_name may be a symlink,
       * so use realpath to resolve only the directory.
       */
      to_name_copy = strdup(to_name);
      if (to_name_copy == NULL) {
        err(EX_OSERR, "%s: strdup", to_name);
      }
      base = basename(to_name_copy);
      if (base == to_name_copy) {
        /* destination is a file in cwd */
        (void)strlcpy(dst, "./", sizeof(dst));
      } else if (base == to_name_copy + 1) {
        /* destination is a file in the root */
        (void)strlcpy(dst, "/", sizeof(dst));
      } else {
        /* all other cases: safe to call dirname() */
        dir = dirname(to_name_copy);
        if (realpath(dir, dst) == NULL) {
          err(EX_OSERR, "%s: realpath", dir);
        }
        if (strcmp(dst, "/") != 0 &&
            strlcat(dst, "/", sizeof(dst)) >= sizeof(dst)) {
          errx(1, "resolved pathname too long");
        }
      }
      if (strlcat(dst, base, sizeof(dst)) >= sizeof(dst)) {
        errx(1, "resolved pathname too long");
      }
      free(to_name_copy);

      /* Trim common path components. */
      ls = ld = NULL;
      for (s = src, d = dst; *s == *d; ls = s, ld = d, s++, d++) {
        continue;
      }
      /*
       * If we didn't end after a directory separator, then we've
       * falsely matched the last component.  For example, if one
       * invoked install -lrs /lib/foo.so /libexec/ then the source
       * would terminate just after the separator while the
       * destination would terminate in the middle of 'libexec',
       * leading to a full directory getting falsely eaten.
       */
      if ((ls != NULL && *ls != '/') || (ld != NULL && *ld != '/')) {

        (void)s--, d--;
      }

      while (*s != '/') {
        (void)s--, d--;
      }

      /* Count the number of directories we need to backtrack. */
      for (++d, lnk[0] = '\0'; *d; d++) {
        if (*d == '/') {
          (void)strlcat(lnk, "../", sizeof(lnk));
        }
      }

      (void)strlcat(lnk, ++s, sizeof(lnk));

      do_symlink(lnk, to_name, target_sb);
      /* XXX: Link may point outside of destdir. */
      metadata_log(to_name, "link", NULL, lnk, NULL, 0);
      return;
    }

    /*
     * If absolute or relative was not specified, try the names the
     * user provided.
     */
    do_symlink(from_name, to_name, target_sb);
    /* XXX: from_name may point outside of destdir. */
    metadata_log(to_name, "link", NULL, from_name, NULL, 0);
  }

  /*
   * install --
   *	build a path name and install the file
   */
  func install(_ from_name : String, _ to_name : String, _ fset : UInt, _ flags : UInt32) {
//    struct stat from_sb, temp_sb, to_sb;
//    struct timespec tsb[2];
//    int devnull, files_match, from_fd, serrno, stripped, target;
//    int temp_fd, to_fd;
//    char backup[MAXPATHLEN], *p, pathbuf[MAXPATHLEN], tempfile[MAXPATHLEN];
//    char *digestresult;

//    digestresult = NULL;
    files_match = stripped = 0;
//    from_fd = -1;
//    to_fd = -1;

    var devnull = false

    /* If try to install NULL file to a directory, fails. */
    if 0 != (flags & DIRECTORY) || from_name != _PATH_DEVNULL {
      if !options.dolink {
        guard let from_sb = try? FileMetadata(for: from_name) else {
          err(Int(EX_OSERR), from_name)
          fatalError()
        }
        if from_sb.filetype != .regular {
          errno = EFTYPE
          err(Int(EX_OSERR), from_name)
        }
      }
      /* Build the target path. */
      if 0 != (flags & DIRECTORY) {
        let p1 = to_name.hasSuffix("/") ? "" : "/"
        let p2 = from_name.split(separator: "/").last!
        to_name = "\(to_name)\(p1)\(p2)"
      }
      devnull = false
    } else {
      devnull = true
    }
    if to_name.isEmpty {
      errx(Int(EX_USAGE), "destination cannot be an empty string")
    }

    let to_sb = try? FileMetadata(for: to_name, followSymlinks: false)

    if options.dolink.rawValue != 0 {
      makelink(from_name, to_name, to_sb)
      return;
    }

    if let to_sb, to_sb.filetype == .regular, to_sb.filetype == .symbolicLink {
      errno = EFTYPE
      err(Int(EX_CANTCREAT), to_name)
    }


    guard devnull, let from_fd = try? FileDescriptor.open(from_name, .readOnly) else {
//    if !devnull && (from_fd = open(from_name, O_RDONLY, 0)) < 0 {
      err(Int(EX_OSERR), from_name)
    }

    var files_match = false
    /* If we don't strip, we can compare first. */
    if (docompare && !dostrip && target && S_ISREG(to_sb.st_mode)) {
      if ((to_fd = open(to_name, O_RDONLY, 0)) < 0) {
        err(Int(EX_OSERR), to_name)
      }
      if (devnull) {
        files_match = to_sb.size == 0
      }
      else {
        files_match = !compare(from_fd, from_name,
                                from_sb.size, to_fd,
                                to_name, to_sb.size, &digestresult)
      }

      /* Close "to" file unless we match. */
      if !files_match {
        try? to_fd.close()
      }
    }

    if !files_match {
      to_fd = create_tempfile(to_name, tempfile, sizeof(tempfile));
      if (to_fd < 0) {
        /*
         * See rdar://138344946
         *
         * Xcode invokes us in a sandbox which only allows read access to the
         * source and write access to the destination, preventing us from
         * creating the temporary file.  We know this isn't a simple permission
         * issue on the destination directory because that would set errno to
         * EACCES instead of EPERM.  Fall back to copying directly to the
         * destination.
         */
        if (errno == EPERM) {
          warnx("sandbox detected, falling back to direct copy")
          if ((!target || unlink(to_name) == 0 || errno == ENOENT) &&
              (to_fd = open(to_name, O_RDWR|O_CREAT|O_EXCL, mode)) >= 0) {
            if (dostrip) {
              stripped = strip(to_name, to_fd, from_name,
                               &digestresult);
            }
            if (!stripped) {
              digestresult = copy(from_fd, from_name, to_fd,
                                  to_name, from_sb.st_size);
            }
            goto copied;
          }
          errno = EPERM;
          /* fall through to err() below */
        }

        err(Int(EX_OSERR), tempfile)

      }

      if !devnull {
        if options.dostrip {
          stripped = strip(tempfile, to_fd, from_name, &digestresult);
        }
        if (!stripped) {
          digestresult = copy(from_fd, from_name, to_fd, tempfile, from_sb.size)
        }
      }
    }

    if options.dostrip {
      if (!stripped) {
        strip(tempfile, to_fd, nil, &digestresult)
      }

      /*
       * Re-open our fd on the target, in case
       * we did not strip in-place.
       */
      try? to_fd.close()
      to_fd = try? FileDescriptor.open(tempfile, .readOnly)
      guard to_fd < 0 else {
        err(Int(EX_OSERR), "stripping \(to_name)")
      }
    }

    /*
     * Compare the stripped temp file with the target.
     */
    if (docompare && dostrip && target && S_ISREG(to_sb.st_mode)) {
      temp_fd = to_fd;

      /* Re-open to_fd using the real target name. */
      if ((to_fd = open(to_name, O_RDONLY, 0)) < 0) {
        err(EX_OSERR, "%s", to_name);
      }

      if (fstat(temp_fd, &temp_sb)) {
        serrno = errno;
        (void)unlink(tempfile);
        errno = serrno;
        err(EX_OSERR, "%s", tempfile);
      }

      if (compare(temp_fd, tempfile, (size_t)temp_sb.st_size, to_fd,
                  to_name, (size_t)to_sb.st_size, &digestresult)
          == 0) {
        /*
         * If target has more than one link we need to
         * replace it in order to snap the extra links.
         * Need to preserve target file times, though.
         */
        if (to_sb.st_nlink != 1) {
          tsb[0] = to_sb.st_atim;
          tsb[1] = to_sb.st_mtim;
          (void)utimensat(AT_FDCWD, tempfile, tsb, 0);
        } else {
          files_match = 1;
          (void)unlink(tempfile);
        }
        (void) close(temp_fd);
      }
    } else if options.dostrip {
      digestresult = digest_file(tempfile)
    }

    /*
     * Move the new file into place if the files are different (or
     * just not compared).
     */
    if !files_match {

      /* Try to turn off the immutable bits. */
      if (to_sb.st_flags & NOCHANGEBITS) {
        (void)chflags(to_name, to_sb.st_flags & ~NOCHANGEBITS);
      }

      if (target && dobackup) {
        if ((size_t)snprintf(backup, MAXPATHLEN, "%s%s", to_name,
                             suffix) != strlen(to_name) + strlen(suffix)) {
          unlink(tempfile);
          errx(EX_OSERR, "%s: backup filename too long",
               to_name);
        }
        if (verbose) {
          (void)printf("install: %s -> %s\n", to_name, backup);
        }
        if (unlink(backup) < 0 && errno != ENOENT) {
          serrno = errno;

          if (to_sb.st_flags & NOCHANGEBITS) {
            (void)chflags(to_name, to_sb.st_flags);
          }

          unlink(tempfile);
          errno = serrno;
          err(EX_OSERR, "unlink: %s", backup);
        }
        if (link(to_name, backup) < 0) {
          serrno = errno;
          unlink(tempfile);

          if (to_sb.st_flags & NOCHANGEBITS) {
            (void)chflags(to_name, to_sb.st_flags);
          }

          errno = serrno;
          err(EX_OSERR, "link: %s to %s", to_name,
              backup);
        }
      }
      if (verbose) {
        print("install: \(from_name) -> \(to_name)")
      }
      if (rename(tempfile, to_name) < 0) {
        serrno = errno;
        unlink(tempfile);
        errno = serrno;
        err(EX_OSERR, "rename: %s to %s",
            tempfile, to_name);
      }

      /* Re-open to_fd so we aren't hosed by the rename(2). */
      (void) close(to_fd);
      if ((to_fd = open(to_name, O_RDONLY, 0)) < 0) {
        err(EX_OSERR, "%s", to_name);
      }
    }

  copied:
    /* in case mtime is modified */
    if (!devnull && (S_ISLNK(from_sb.st_mode) || S_ISREG(from_sb.st_mode)) &&
        fcopyfile(from_fd, to_fd, NULL, COPYFILE_XATTR) < 0) {
      warn("%s: unable to copy extended attributes from %s", to_name, from_name);
    }

    /*
     * Preserve the timestamp of the source file if necessary.
     */
    if (dopreserve && !files_match && !devnull) {
      tsb[0] = from_sb.st_atim;
      tsb[1] = from_sb.st_mtim;
      (void)utimensat(AT_FDCWD, to_name, tsb, 0);
    }

    if (fstat(to_fd, &to_sb) == -1) {
      serrno = errno;
      (void)unlink(to_name);
      errno = serrno;
      err(EX_OSERR, "%s", to_name);
    }

    /*
     * Set owner, group, mode for target; do the chown first,
     * chown may lose the setuid bits.
     */
    if (!dounpriv && ((gid != (gid_t)-1 && gid != to_sb.st_gid) ||
                      (uid != (uid_t)-1 && uid != to_sb.st_uid) ||
                      (mode != (to_sb.st_mode & ALLPERMS)))) {

      /* Try to turn off the immutable bits. */
      if (to_sb.st_flags & NOCHANGEBITS) {
        (void)fchflags(to_fd, to_sb.st_flags & ~NOCHANGEBITS);
      }

    }

    if (!dounpriv && ((gid != (gid_t)-1 && gid != to_sb.st_gid) ||
                      (uid != (uid_t)-1 && uid != to_sb.st_uid))) {
      if (fchown(to_fd, uid, gid) == -1) {
        serrno = errno;
        (void)unlink(to_name);
        errno = serrno;
        err(EX_OSERR,"%s: chown/chgrp", to_name);
      }
    }
    if (mode != (to_sb.st_mode & ALLPERMS)) {
      if (fchmod(to_fd,
                 dounpriv ? mode & (S_IRWXU|S_IRWXG|S_IRWXO) : mode)) {
        serrno = errno;
        (void)unlink(to_name);
        errno = serrno;
        err(EX_OSERR, "%s: chmod", to_name);
      }
    }

    /*
     * If provided a set of flags, set them, otherwise, preserve the
     * flags, except for the dump flag.
     * NFS does not support flags.  Ignore ENOTSUP flags if we're just
     * trying to turn off UF_NODUMP.  If we're trying to set real flags,
     * then warn if the fs doesn't support it, otherwise fail.
     */
    if (!dounpriv && !devnull && (flags & SETFLAGS ||
                                  (from_sb.st_flags & ~UF_NODUMP) != to_sb.st_flags) &&
        fchflags(to_fd,
                 flags & SETFLAGS ? fset : from_sb.st_flags & ~UF_NODUMP)) {
      if (flags & SETFLAGS) {
        if (errno == ENOTSUP) {
          warn("%s: chflags", to_name);
        }
        else {
          serrno = errno;
          (void)unlink(to_name);
          errno = serrno;
          err(EX_OSERR, "%s: chflags", to_name);
        }
      }
    }


    /* the ACL could prevent credential/permission system calls later on... */
    if (!devnull && (S_ISLNK(from_sb.st_mode) || S_ISREG(from_sb.st_mode)) &&
        (fcopyfile(from_fd, to_fd, NULL, COPYFILE_ACL) < 0)) {
      warn("%s: unable to copy ACL from %s", to_name, from_name);
    }

    (void)close(to_fd);
    if (!devnull) {
      (void)close(from_fd);
    }

    metadata_log(to_name, "file", tsb, NULL, digestresult, to_sb.st_size);
    free(digestresult);
  }

  /*
   * compare --
   *	Compare two files; non-zero means files differ.
   *	Compute digest and return its address in *dresp
   *	unless it points to pre-computed digest.
   */
  func compare(_ from_fd : FileDescriptor, _ from_name : String, _ from_len : size_t,
               _ to_fd : FileDescriptor, _ to_name : String, _ to_len : size_t,
               _ dresp : inout String)
  {
    int rv;
    int do_digest;
    DIGEST_CTX ctx;

    if (from_len != to_len) {
      return 1;
    }

    do_digest = (digesttype != DIGEST_NONE && dresp != NULL &&
                 *dresp == NULL);
    if (from_len <= MAX_CMP_SIZE) {
      static char *buf, *buf1, *buf2;
      static size_t bufsize;
      int n1, n2;

      if (do_digest) {
        digest_init(&ctx);
      }

      if (buf == NULL) {
        /*
         * Note that buf and bufsize are static. If
         * malloc() fails, it will fail at the start
         * and not copy only some files.
         */
        if (sysconf(_SC_PHYS_PAGES) > PHYSPAGES_THRESHOLD) {
          bufsize = MIN(BUFSIZE_MAX, MAXPHYS * 8);
        }
        else {
          bufsize = BUFSIZE_SMALL;
        }
        buf = malloc(bufsize * 2);
        if (buf == NULL) {
          err(1, "Not enough memory");
        }
        buf1 = buf;
        buf2 = buf + bufsize;
      }
      rv = 0;
      lseek(from_fd, 0, SEEK_SET);
      lseek(to_fd, 0, SEEK_SET);
      while (rv == 0) {
        n1 = read(from_fd, buf1, bufsize);
        if (n1 == 0){
          break;		/* EOF */
        }
        else if (n1 > 0) {
          n2 = read(to_fd, buf2, n1);
          if (n2 == n1) {
            rv = memcmp(buf1, buf2, n1);
          }
          else {
            rv = 1;	/* out of sync */
          }
        } else {
          rv = 1;		/* read failure */
        }
        if (do_digest) {
          digest_update(&ctx, buf1, n1);
        }
      }
      lseek(from_fd, 0, SEEK_SET);
      lseek(to_fd, 0, SEEK_SET);
    } else {
      rv = 1;	/* don't bother in this case */
    }

    if (do_digest) {
      if (rv == 0) {
        *dresp = digest_end(&ctx, NULL);
      }
      else {
        (void)digest_end(&ctx, NULL);
      }
    }

    return rv;
  }

  /*
   * create_tempfile --
   *	create a temporary file based on path and open it
   */
  func create_tempfile(_ path : String, _ temp : String, _ tsize : size_t) {
    char *p;

    (void)strncpy(temp, path, tsize);
    temp[tsize - 1] = '\0';
    if ((p = strrchr(temp, '/')) != NULL) {
      p++;
    }
    else {
      p = temp;
    }
    (void)strncpy(p, "INS@XXXXXX", &temp[tsize - 1] - p);
    temp[tsize - 1] = '\0';
    return (mkstemp(temp));
  }

  /*
   * copy --
   *	copy from one file to another
   */
  func copy(_ from_fd : FileDescriptor, _ from_name : String, _ to_fd : FileDescriptor, _ to_name : String, _ size : off_t) -> [UInt8] {
    static char *buf = NULL;
    static size_t bufsize;
    int nr, nw;
    int serrno;
    //    #ifndef BOOTSTRAP_XINSTALL
    ssize_t ret;
    // #endif
    DIGEST_CTX ctx;

    /* Rewind file descriptors. */
    if (lseek(from_fd, 0, SEEK_SET) < 0) {
      err(EX_OSERR, "lseek: %s", from_name);
    }
    if (lseek(to_fd, 0, SEEK_SET) < 0) {
      err(EX_OSERR, "lseek: %s", to_name);
    }

    //    #ifndef BOOTSTRAP_XINSTALL
    /* Try copy_file_range() if no digest is requested */
    if (digesttype == DIGEST_NONE) {

      ret = fcopyfile(from_fd, to_fd, NULL,
                      COPYFILE_DATA | COPYFILE_DATA_SPARSE);

      if (ret == 0) {
        goto done;
      }

      if (errno != ENOTSUP) {

        serrno = errno;
        (void)unlink(to_name);
        errno = serrno;
        err(EX_OSERR, "%s", to_name);
      }
      /* Fall back */
    }
    // #endif
    digest_init(&ctx);

    if (buf == NULL) {
      /*
       * Note that buf and bufsize are static. If
       * malloc() fails, it will fail at the start
       * and not copy only some files.
       */
      if (sysconf(_SC_PHYS_PAGES) > PHYSPAGES_THRESHOLD) {
        bufsize = MIN(BUFSIZE_MAX, MAXPHYS * 8);
      }
      else {
        bufsize = BUFSIZE_SMALL;
      }
      buf = malloc(bufsize);
      if (buf == NULL) {
        err(1, "Not enough memory");
      }
    }
    while ((nr = read(from_fd, buf, bufsize)) > 0) {
      if ((nw = write(to_fd, buf, nr)) != nr) {
        serrno = errno;
        (void)unlink(to_name);
        if (nw >= 0) {
          errx(EX_OSERR,
               "short write to %s: %jd bytes written, "
               "%jd bytes asked to write",
               to_name, (uintmax_t)nw,
               (uintmax_t)size);
        } else {
          errno = serrno;
          err(EX_OSERR, "%s", to_name);
        }
      }
      digest_update(&ctx, buf, nr);
    }
    if (nr != 0) {
      serrno = errno;
      (void)unlink(to_name);
      errno = serrno;
      err(EX_OSERR, "%s", from_name);
    }
  done:
    if (safecopy && fsync(to_fd) == -1) {
      serrno = errno;
      (void)unlink(to_name);
      errno = serrno;
      err(EX_OSERR, "fsync failed for %s", to_name);
    }
    return (digest_end(&ctx, NULL));
  }

  /*
   * strip --
   *	Use strip(1) to strip the target file.
   *	Just invoke strip(1) on to_name if from_name is NULL, else try
   *	to run "strip -o to_name from_name" and return 0 on failure.
   *	Return 1 on success and assign result of digest_file(to_name)
   *	to *dresp.
   */
  func strip(_ to_name : String, _ to_fd : FileDescriptor, _ from_name : String?, _ dresp : inout String) -> Bool {
    const char *stripbin;
    const char *args[5];
    char *prefixed_from_name;
    pid_t pid;
    int error, serrno, status;

    prefixed_from_name = NULL;
    stripbin = Environment["STRIPBIN"] ?? "strip"

    args[0] = stripbin;
    if (from_name == NULL) {
      args[1] = to_name;
      args[2] = NULL;
    } else {
      args[1] = "-o";
      args[2] = to_name;

      /* Prepend './' if from_name begins with '-' */
      if (from_name[0] == '-') {
        if (asprintf(&prefixed_from_name, "./%s", from_name) == -1) {
          return (0);
        }
        args[3] = prefixed_from_name;
      } else {
        args[3] = from_name;
      }
      args[4] = NULL;
    }
    error = posix_spawnp(&pid, stripbin, NULL, NULL,
                         __DECONST(char **, args), environ);
    if (error != 0) {
      unlink(to_name)
      errc(error == EAGAIN || error == EPROCLIM || error == ENOMEM ?
           EX_TEMPFAIL : EX_OSERR, error, "spawn %s", stripbin);
    }
    free(prefixed_from_name);
    if (waitpid(pid, &status, 0) == -1) {
      error = errno;
      (void)unlink(to_name);
      errc(EX_SOFTWARE, error, "wait");
      /* NOTREACHED */
    }
    if (status != 0) {
      if let from_name {
        return false
      }
      unlink(to_name)
      errx(Int(EX_SOFTWARE), "strip command \(stripbin) failed on \(to_name)")
    }
    if let from_name, safecopy, fsync(to_fd) == -1 {
      let serrno = errno
      unlink(to_name)
      errno = serrno
      err(Int(EX_OSERR), "fsync failed for \(to_name)")
    }
    if (dresp != nil) {
      *dresp = digest_file(to_name);
    }
    return true
  }

  /*
   * install_dir --
   *	build directory hierarchy
   */
  func install_dir(_ pathx : String) {

    var path = ""
    for p in pathx.split(separator: "/") {
      var tried_mkdir = false
      path.append("/")
      path.append(contentsOf: p)
    again:
      while true {
        do {
          let sb = try FileMetadata(for: path)
          if sb.filetype == .directory {
            errx(Int(EX_OSERR), "\(path) exists but is not a directory")
          }
        } catch(let e) {
          if e.code != ENOENT || tried_mkdir {
            err(Int(EX_OSERR), "stat \(path)")
          }
          if (mkdir(path, 0o0755) < 0) {
            tried_mkdir = true
            if errno == EEXIST {
              continue again
            }
            err(Int(EX_OSERR), "mkdir \(path)")
          }
          if options.verbose != 0 {
            print("install: mkdir \(path)")
          }
        }
        break again
      }
    }

    if !options.dounpriv {
      let u = options.uid == nil ? -1 : uid_t(options.uid!)
      let g = options.gid == nil ? -1 : gid_t(options.gid!)

      if (options.gid != nil || options.uid != nil) && 0 != chown(path, u, g) {
        warn("chown \(u):\(g) \(path)")
      }
      /* XXXBED: should we do the chmod in the dounpriv case? */
      if (chmod(path, mode)) {
        warn("chmod %o \(path)", mode)
      }
    }
    metadata_log(path, "dir", nil, nil, nil, 0);
  }

  /*
   * metadata_log --
   *	if metafp is not NULL, output mtree(8) full path name and settings to
   *	metafp, to allow permissions to be set correctly by other tools,
   *	or to allow integrity checks to be performed.
   */
  func metadata_log(_ path : String, _ type : String, _ ts : timespec?,
                    _ slink : String? , _ digestresult : [UInt8]?, _ size : off_t) {
    let extra = [ " ", "\t", "\n", "\\", "#", "\0"]

    /*    const char *p;
     char *buf;
     size_t buflen, destlen;
     struct flock metalog_lock;
     */

    guard var metafp = options.metafp else {
      return
    }

    /* Buffer for strsnvis(3), used for both path and slink. */
    buflen = strlen(path);
    if (slink && strlen(slink) > buflen) {
      buflen = strlen(slink);
    }
    buflen = 4 * buflen + 1;
    if ((buf = malloc(buflen)) == NULL) {
      warn(NULL);
      return;
    }

    /* Lock log file. */
    metalog_lock.l_start = 0;
    metalog_lock.l_len = 0;
    metalog_lock.l_whence = SEEK_SET;
    metalog_lock.l_type = F_WRLCK;
    if (fcntl(fileno(metafp), F_SETLKW, &metalog_lock) == -1) {
      warn("can't lock %s", metafile);
      free(buf);
      return;
    }

    /* Remove destdir. */
    p = path;
    if (destdir) {
      destlen = strlen(destdir);
      if (strncmp(p, destdir, destlen) == 0 &&
          (p[destlen] == '/' || p[destlen] == '\0')) {
        p += destlen;
      }
    }
    while (*p && *p == '/') {
      p++;
    }
    strsnvis(buf, buflen, p, VIS_OCTAL, extra);
    p = buf;
    /* Print details. */
    fprintf(metafp, ".%s%s type=%s", *p ? "/" : "", p, type);
    if (owner) {
      fprintf(metafp, " uname=%s", owner);
    }
    if (group) {
      fprintf(metafp, " gname=%s", group);
    }
    fprintf(metafp, " mode=%#o", mode);
    if (slink) {
      strsnvis(buf, buflen, slink, VIS_CSTYLE, extra);
      fprintf(metafp, " link=%s", buf);
    }
    if (*type == 'f') { /* type=file */
      fprintf(metafp, " size=%lld", (long long)size);
    }
    if (ts != NULL && dopreserve) {
      fprintf(metafp, " time=%lld.%09ld",
              (long long)ts[1].tv_sec, ts[1].tv_nsec);
    }
    if (digestresult && digest) {
      fprintf(metafp, " \(digest)=\(digestresult)")
    }
    if (fflags) {
      fprintf(metafp, " flags=\(fflags)")
    }
    if (tags) {
      fprintf(metafp, " tags=\(tags)")
    }
    print("", to: &metafp)
    /* Flush line. */
//    fflush(metafp);

    /* Unlock log file. */
    metalog_lock.l_type = F_UNLCK;
    if (fcntl(fileno(metafp), F_SETLKW, &metalog_lock) == -1) {
      warn("can't unlock %s", metafile);
    }
    free(buf);
  }

  /*
   * usage --
   *	print a usage message and die
   */
  var usage = """
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
"""
}
