// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*
 * Copyright (c) 1989, 1993, 1994
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin
import Darwin.membership

extension chmod {

  struct ACLPermType : OptionSet {
    var rawValue : Int32

    static let DIR = Self(rawValue: 1)
    static let FILE = Self(rawValue: 2)
  }

  struct ACLPerm {
    var perm : acl_perm_t
    var flags : ACLPermType

    init(_ a : acl_perm_t, _ b : ACLPermType) {
      perm = a
      flags = b
    }
  }

  static let acl_perms : [String:ACLPerm] = [
    "read" : .init(ACL_READ_DATA, .FILE),
    "llist": .init(ACL_LIST_DIRECTORY, .DIR),
    "write": .init(ACL_WRITE_DATA, .FILE),
    "add_file" : .init(ACL_ADD_FILE, .DIR),
    "execute" : .init(ACL_EXECUTE, .FILE),
    "search" : .init(ACL_SEARCH, .DIR),
    "delete" : .init(ACL_DELETE,	[.FILE, .DIR]),
    "append" : .init(ACL_APPEND_DATA,	.FILE),
    "add_subdirectory" : .init(ACL_ADD_SUBDIRECTORY,	.DIR),
    "delete_child" : .init(ACL_DELETE_CHILD, .DIR),
    "readattr" : .init(ACL_READ_ATTRIBUTES,	[.FILE, .DIR]),
    "writeattr" : .init(ACL_WRITE_ATTRIBUTES,	[.FILE, .DIR]),
    "readextattr" : .init(ACL_READ_EXTATTRIBUTES, [.FILE, .DIR]),
    "writeextattr" : .init(ACL_WRITE_EXTATTRIBUTES, [.FILE, .DIR ] ),
    "readsecurity" : .init(ACL_READ_SECURITY,	[.FILE, .DIR]),
    "writesecurity" : .init(ACL_WRITE_SECURITY,	[.FILE, .DIR]),
    "chown" : .init(ACL_CHANGE_OWNER,	[.FILE, .DIR]),
  ]

  struct ACLFlag {
    var flag : acl_flag_t
    var flags : ACLPermType

    init(_ a : acl_flag_t, _ b : ACLPermType) {
      flag = a
      flags = b
    }
  }

  static let acl_flags : [String:ACLFlag] = [
    "inherited" : .init(ACL_ENTRY_INHERITED, [.FILE, .DIR] ),
    "file_inherit" : .init(ACL_ENTRY_FILE_INHERIT, .DIR),
    "directory_inherit" : .init(ACL_ENTRY_DIRECTORY_INHERIT,	.DIR),
    "limit_inherit" : .init(ACL_ENTRY_LIMIT_INHERIT,	[.FILE, .DIR]),
    "only_inherit" : .init(ACL_ENTRY_ONLY_INHERIT, .DIR),
]

  /* TBD - Many of these routines could potentially be considered for
   * inclusion in a library. If that is done, either avoid use of "err"
   * and implement a better fall-through strategy in case of errors,
   * or use err_set_exit() and make various structures globals.
   */

  enum NameType : Int {
    case USER = 1
    case GROUP = 2
    case EITHER = 3
  }

  /* Perform a name to uuid mapping - calls through to memberd */

  func name_to_uuid(_ tok : String, _ nametype : NameType) -> [UInt8] {
//    uuid_t *entryg = NULL;
//    size_t len = strlen(tok);

//    if ((entryg = (uuid_t *) calloc(1, sizeof(uuid_t))) == NULL) {
//      errx(1, "Unable to allocate a uuid");
//    }

    var entryg = Array(repeating: UInt8(0), count: MemoryLayout<uuid_t>.size)

    if (nametype == .USER || nametype == .EITHER) && mbr_identifier_to_uuid(ID_TYPE_USERNAME, tok, tok.count, &entryg) == 0 {
      return entryg;
    }

    if (nametype == .GROUP || nametype == .EITHER) && mbr_identifier_to_uuid(ID_TYPE_GROUPNAME, tok, tok.count, &entryg) == 0 {
      return entryg
    }

    errx(1, "Unable to translate '\(tok)' to a UUID")
    fatalError()
  }

  enum Match : Int {
    case EXACT = 2
    case PARTIAL = 1
    case NONE = -1
    case SUBSET = -2
    case SUPERSET = -3
  }

  enum ACLTag : UInt32 {
    case UNDEFINED_TAG = 0
    case EXTENDED_ALLOW = 1
    case EXTENDED_DENY = 2
  }

  /* Convert an acl entry in string form to an acl_entry_t */
  func parse_entry(_ entrybuf : String, _ newent : acl_entry_t?) {
/*    char *tok;
    char *pebuf;
    uuid_t *entryg;
*/
    var perms : acl_permset_t?
    var flags : acl_flagset_t?
    /*
    unsigned permcount = 0;
    unsigned pindex = 0;
    char *delimiter = " ";
    int nametype = NAME_EITHER;
*/
    acl_get_permset(newent, &perms);
    acl_get_flagset_np(UnsafeMutableRawPointer(newent), &flags);

    var pebuf = entrybuf
    var nametype : NameType = .EITHER

    if entrybuf.hasPrefix("user:") {
      nametype = .USER
      pebuf.removeFirst(5)
    } else if entrybuf.hasPrefix("group:") {
      nametype = .GROUP
      pebuf.removeFirst(6)
    }

    let delimiter = pebuf.contains(":") ? ":" : " "
    let tok = pebuf.split(separator: delimiter, maxSplits: 2)

    if tok[0].isEmpty {
      errx(1, "Invalid entry format -- expected user or group name")
    }

    /* parse the name into a qualifier */
    var entryg = name_to_uuid(String(tok[0]), nametype)

    if tok.count < 2 || tok[1].isEmpty {
      errx(1, "Invalid entry format -- expected allow or deny")
    }

    var tag : ACLTag = ACLTag.UNDEFINED_TAG

    /* is the verb 'allow' or 'deny'? */
    if tok[1] == "allow" {
      tag = .EXTENDED_ALLOW
    } else if tok[1] == "deny" {
      tag = .EXTENDED_DENY
    } else {
      errx(1, "Unknown tag type '\(tok[1])'")
    }

    /* parse permissions */
    var permcount = 0
    pebuf = tok.count > 2 ? String(tok[2]) : ""

    outerloop:
    for tok in pebuf.split(separator: ",", omittingEmptySubsequences: true) {
        /* is it a permission? */
      if let k = Self.acl_perms[String(tok)] {
            /* got one */
        acl_add_perm(perms, k.perm)
            permcount += 1
            continue outerloop
          }

        /* is it a flag? */

      if let k = Self.acl_flags[String(tok)] {
            /* got one */
        acl_add_flag_np(flags, k.flag)
            permcount += 1
            continue outerloop
          }
        errx(1,"Invalid permission type '\(tok)'")
//      found:
        continue;
    }
    if 0 == permcount {
      errx(1, "No permissions specified");
    }
    acl_set_tag_type(newent, acl_tag_t(tag.rawValue));
    acl_set_qualifier(newent, &entryg);
    acl_set_permset(newent, perms);
    acl_set_flagset_np(UnsafeMutableRawPointer(newent), flags);
    free(&entryg);
  }

  /* Convert one or more acl entries in string form to an acl_t */
  func parse_acl_entries(_ input : String) -> acl_t? {
/*    acl_t acl_input;
    acl_entry_t newent;
    char *inbuf;
    char *oinbuf;

    char **bufp, *entryv[ACL_MAX_ENTRIES];
*/

    let inbuf = input // strncpy(inbuf, input, MAX_ACL_TEXT_SIZE);
//    inbuf[MAX_ACL_TEXT_SIZE - 1] = '\0';

    var acl_input = acl_init(1)
    if acl_input == nil {
      err(1, "acl_init() failed")
    }

    let oinbuf = inbuf.split(separator: "\n", omittingEmptySubsequences: true)
    for bufp in oinbuf {
      var newent : acl_entry_t?
      if 0 != acl_create_entry(&acl_input, &newent) {
        err(1, "acl_create_entry() failed")
      }
      parse_entry(String(bufp), newent)
//        errx(1, "Failed parsing entry '%s'", *bufp);
//      }
    }
    return acl_input
  }

  /* XXX No Libc support for inherited entries and generation determination yet */
  func get_inheritance_level(_ entry : acl_entry_t) -> UInt {
    /* XXX to be implemented */
    return 1
  }

  /* Determine a "score" for an acl entry. The entry scores higher if it's
   * tagged ACL_EXTENDED_DENY, and non-inherited entries are ranked higher
   * than inherited entries.
   */

  func score_acl_entry(_ entry : acl_entry_t?) -> Int {
    let MINIMUM_TIER = -1000
    let INHERITANCE_TIER = -5
    var score = 0;

    guard let entry else {
      return (MINIMUM_TIER)
    }

    var tag : acl_tag_t = acl_tag_t(0)
    if acl_get_tag_type(entry, &tag) != 0 {
      err(1, "Malformed ACL entry, no tag present")
    }

    var flags : acl_flagset_t?
    if acl_get_flagset_np(UnsafeMutableRawPointer(entry), &flags) != 0 {
      err(1, "Unable to obtain flagset")
    }

    var perms : acl_permset_t?
    if acl_get_permset(entry, &perms) != 0 {
      err(1, "Malformed ACL entry, no permset present")
    }

    switch ACLTag(rawValue: tag.rawValue) {
      case .EXTENDED_ALLOW:
        break
      case .EXTENDED_DENY:
        score += 1
      default:
        errx(1, "Unknown tag type \(tag) present in ACL entry")
    }

    // FIXME: acl_flag_t
    if 0 != acl_get_flag_np(flags, acl_flag_t(UInt32(ACLEntry.ENTRY_INHERITED.rawValue))) {
      score += Int(get_inheritance_level(entry)) * INHERITANCE_TIER
    }

    return score;
  }

  func compare_acl_qualifiers(_ qa : UnsafePointer<uuid_t>, _ qb : UnsafePointer<uuid_t>) -> Int32 {
    return bcmp(qa, qb, MemoryLayout<uuid_t>.size)
  }

  /* Compare two ACL permsets.
   *  Returns :
   *  MATCH_SUBSET if bperms is a subset of aperms
   *  MATCH_SUPERSET if bperms is a superset of aperms
   *  MATCH_PARTIAL if the two permsets have a common subset
   *  MATCH_EXACT if the two permsets are identical
   *  MATCH_NONE if they are disjoint
   */

  func compare_acl_permsets(_ aperms : acl_permset_t?, _ bperms : acl_permset_t?) -> Match {
    var i = 0
    /* TBD Implement other match levels as needed */
    for (_, p) in Self.acl_perms {
      if acl_get_perm_np(aperms, p.perm) !=
          acl_get_perm_np(bperms, p.perm) {
        return .NONE
      }
      i += 1
    }
    return .EXACT
  }

  func compare_acl_flagsets(_ aflags : acl_flagset_t?, _ bflags : acl_flagset_t?) -> Match {
    var i = 0
    /* TBD Implement other match levels as needed */
    for (_, p) in Self.acl_flags {
      if acl_get_flag_np(aflags, p.flag) !=
          acl_get_flag_np(bflags, p.flag) {
        return .NONE
      }
      i += 1
    }
    return .EXACT
  }

  /* Compares two ACL entries for equality */
  func compare_acl_entries(_ a : acl_entry_t?, _ b : acl_entry_t?) -> Match {
/*    acl_tag_t atag, btag;
    acl_permset_t aperms, bperms;
    acl_flagset_t aflags, bflags;
    int pcmp = 0, fcmp = 0;
    void *aqual, *bqual;
*/
    let aqual = acl_get_qualifier(a).assumingMemoryBound(to: uuid_t.self)
    let bqual = acl_get_qualifier(b).assumingMemoryBound(to: uuid_t.self)

    let comparex = compare_acl_qualifiers(aqual, bqual)
    acl_free(aqual)
    acl_free(bqual)

    if comparex != 0 {
      return .NONE
    }

    var atag : acl_tag_t = acl_tag_t(0)
    var btag : acl_tag_t = acl_tag_t(0)

    if 0 != acl_get_tag_type(a, &atag) {
      err(1, "No tag type present in entry")
    }
    if 0 != acl_get_tag_type(b, &btag) {
      err(1, "No tag type present in entry")
    }

    if atag != btag {
      return .NONE
    }

    var aperms : acl_permset_t?
    var bperms : acl_permset_t?
    var aflags : acl_flagset_t?
    var bflags : acl_flagset_t?
    if (acl_get_permset(a, &aperms) != 0) ||
        (acl_get_flagset_np(UnsafeMutableRawPointer(a), &aflags) != 0) ||
        (acl_get_permset(b, &bperms) != 0) ||
        (acl_get_flagset_np(UnsafeMutableRawPointer(b), &bflags) != 0) {
      err(1, "error fetching permissions");
    }

    let pcmp = compare_acl_permsets(aperms, bperms);
    let fcmp = compare_acl_flagsets(aflags, bflags);

    if pcmp == Match.NONE || fcmp == .NONE {
      return .PARTIAL
    }
    else {
      return .EXACT
    }
  }

  /* Verify that an ACL is in canonical order. Currently, the canonical
   * form is:
   * local deny
   * local allow
   * inherited deny (parent)
   * inherited allow (parent)
   * inherited deny (grandparent)
   * inherited allow (grandparent)
   * ...
   */
  func is_canonical(_ acl : acl_t?) -> Bool {
    var entry : acl_entry_t?
    var next_score = 0

    /* XXX - is a zero entry ACL in canonical form? */
    if (0 != acl_get_entry(acl, ACLEntry.FIRST_ENTRY.rawValue, &entry)) {
      return true
    }

    var score = score_acl_entry(entry);
    while acl_get_entry(acl, ACLEntry.NEXT_ENTRY.rawValue, &entry) == 0 {
      next_score = score_acl_entry(entry)
        if score < next_score {
          return false
      }
      score = next_score
    }
    return true
  }


  /* Iterate through an ACL, and find the canonical position for the
   * specified entry
   */
  func find_canonical_position(_ acl : acl_t?, _ modifier : acl_entry_t) -> Int32 {
/*
    acl_entry_t entry;
    int mscore = 0;
    unsigned mpos = 0;
*/
    /* Check if there's an entry with the same qualifier
     * and tag type; if not, find the appropriate slot
     * for the score.
     */

    var entry : acl_entry_t?
    if 0 != acl_get_entry(acl, ACLEntry.FIRST_ENTRY.rawValue, &entry) {
      return 0
    }

    let mscore = score_acl_entry(modifier);

    var mpos : Int32 = 0
    while mscore < score_acl_entry(entry) {
      mpos += 1
      if 0 != acl_get_entry(acl, ACLEntry.NEXT_ENTRY.rawValue, &entry) {
        break
      }
    }
    return mpos
  }

  /* For a given acl_entry_t "modifier", find the first exact or
   * partially matching entry from the specified acl_t acl
   */

  func find_matching_entry (_ acl : acl_t?, _ modifier : acl_entry_t, _ rentryp : inout acl_entry_t?,
                            _ match_inherited : UInt) -> Match {

    var entry : acl_entry_t?
    var fcmp = Match.NONE

    while acl_get_entry(acl, (entry == nil ? ACLEntry.FIRST_ENTRY : .NEXT_ENTRY).rawValue, &entry) == 0 {
      let cmp = compare_acl_entries(entry!, modifier);
      if cmp == Match.EXACT || cmp == Match.PARTIAL {
        if 0 != match_inherited {
          var eflags : acl_flagset_t?
          var mflags : acl_flagset_t?
          if 0 != acl_get_flagset_np(UnsafeMutableRawPointer(modifier), &mflags) {
            err(1, "Unable to get flagset")
          }

          if 0 != acl_get_flagset_np(&entry, &eflags) {
            err(1, "Unable to get flagset");
          }

          if compare_acl_flagsets(mflags!, eflags!) == .EXACT {
            rentryp = entry
            fcmp = cmp
          }
        }
        else {
          rentryp = entry
          fcmp = cmp;
        }
      }
      if fcmp == .EXACT {
        break;
      }
    }
    return fcmp
  }

  /* Remove all perms specified in modifier from rentry*/
  func subtract_from_entry(_ rentry : inout acl_entry_t?, _ modifier : acl_entry_t, _ valid_perms : inout Int) {
    var rperms : acl_permset_t?
    var mperms : acl_permset_t?

    var rflags : acl_flagset_t?
    var mflags : acl_flagset_t?

    if 0 != valid_perms {
      valid_perms = 0
    }

    if ((acl_get_permset(rentry, &rperms) != 0) ||
        (acl_get_flagset_np(UnsafeMutableRawPointer(rentry), &rflags) != 0) ||
        (acl_get_permset(modifier, &mperms) != 0) ||
        (acl_get_flagset_np(UnsafeMutableRawPointer(modifier), &mflags) != 0)) {
      err(1, "error computing ACL modification");
    }

    for (_, p) in Self.acl_perms {
      if 0 != acl_get_perm_np(mperms, p.perm) {
        acl_delete_perm(rperms, p.perm)
      }
      else if (0 != valid_perms && 0 != acl_get_perm_np(rperms, p.perm)) {
        valid_perms += 1
      }
    }

    for(_, p) in Self.acl_flags {
      if 0 != acl_get_flag_np(mflags, p.flag) {
        acl_delete_flag_np(rflags, p.flag)
      }
    }
    acl_set_permset(rentry, rperms);
    acl_set_flagset_np(&rentry, rflags);
  }

  /* Add the perms specified in modifier to rentry */
  func merge_entry_perms(_ rentry : inout acl_entry_t?, _ modifier : acl_entry_t) {
    var rperms : acl_permset_t?
    var mperms : acl_permset_t?
    var rflags : acl_flagset_t?
    var mflags : acl_flagset_t?

    if ((acl_get_permset(rentry, &rperms) != 0) ||
        acl_get_flagset_np(UnsafeMutableRawPointer(rentry), &rflags) != 0 ||
        acl_get_permset(modifier, &mperms) != 0 ||
        acl_get_flagset_np(UnsafeMutableRawPointer(modifier), &mflags) != 0) {
      err(1, "error computing ACL modification");
    }

    for (_, p) in Self.acl_perms {
      if 0 != acl_get_perm_np(mperms, p.perm) {
        acl_add_perm(rperms, p.perm)
      }
    }

    for (_, p) in Self.acl_flags {
      if 0 != acl_get_flag_np(mflags, p.flag) {
        acl_add_flag_np(rflags, p.flag)
      }
    }
    acl_set_permset(rentry, rperms)
    acl_set_flagset_np(&rentry, rflags)
  }

  func modify_acl(_ oacl : inout acl_t?, _ modifierx : acl_entry_t?, _ optflags : ACLOptions,
                  _ position : Int32, _ inheritance_level : Int,
                  _ flag_new_acl : Bool, _ path : String) throws(CmdErr) -> Int {
/*
    unsigned cpos = 0;
    acl_entry_t newent = NULL;
    int dmatch = 0;
    acl_entry_t rentry = NULL;
    unsigned retval = 0;
    acl_t oacl = *oaclp;
*/

    var modifier = modifierx


    /* Add the inherited flag if requested by the user*/
    if nil != modifier && optflags.contains(.INHERIT_FLAG) {
      var mflags : acl_flagset_t?
      acl_get_flagset_np(&modifier, &mflags)
      acl_add_flag_np(mflags, acl_flag_t(UInt32(ACLEntry.ENTRY_INHERITED.rawValue)))
      acl_set_flagset_np(&modifier, mflags)
    }

    var newent : acl_entry_t?
    var retval = 0

    if optflags.contains(.SET_FLAG) {
      if (position != -1) {
        if 0 != acl_create_entry_np(&oacl, &newent, position) {
          err(1, "acl_create_entry() failed");
        }
        acl_copy_entry(newent, modifier);
      } else {
        /* If an entry exists, add the new permissions to it, else add an
         * entry in the canonical position.
         */

        var rentry : acl_entry_t?

        /* First, check for a matching entry - if one exists, merge flags */
        let dmatch = find_matching_entry(oacl, modifier!, &rentry, 1);

        if dmatch != Match.NONE {
          if dmatch == .EXACT {
            /* Nothing to be done */
            // Assign oacl?
            return retval
          }

          if dmatch == .PARTIAL {
            merge_entry_perms(&rentry, modifier!)
            // Assign oacl?
            return retval
          }
        }
        /* Insert the entry in canonical order */
        let cpos = find_canonical_position(oacl, modifier!);
        if 0 != acl_create_entry_np(&oacl, &newent, cpos) {
          err(1, "acl_create_entry() failed")
        }
        acl_copy_entry(newent, modifier);
      }
    } else if optflags.contains(.DELETE_FLAG) {
      var rentry : acl_entry_t?

      if flag_new_acl {
        warnx("No ACL present '\(path)'")
        retval = 1;
      } else if (position != -1 ) {
        if (0 != acl_get_entry(oacl, position, &rentry)) {
          warnx("Invalid entry number '\(path)'")
          retval = 1
        } else {
          acl_delete_entry(oacl, rentry);
        }
      } else {
        var match_found = 0

        while acl_get_entry(oacl, (rentry == nil ? ACLEntry.FIRST_ENTRY : .NEXT_ENTRY).rawValue, &rentry) == 0 {
          let cmp = compare_acl_entries(rentry, modifier!)
          if cmp == .EXACT || cmp == .PARTIAL {
            match_found += 1
            if cmp == .EXACT {
              acl_delete_entry(oacl, rentry)
            }
            else {
              var valid_perms = 0
              /* In the event of a partial match, remove the specified perms from the
               * entry */
              subtract_from_entry(&rentry, modifier!, &valid_perms)
              /* if no perms survived then delete the entry */
              if valid_perms == 0 {
                acl_delete_entry(oacl, rentry);
              }
            }
          }
        }
        if 0 == match_found {
          warnx("Entry not found when attempting delete '\(path)'")
          retval = 1
        }
      }
    } else if optflags.contains(.REWRITE_FLAG) {
      var rentry : acl_entry_t?

      if -1 == position {
        throw CmdErr(1)
      }
      if !flag_new_acl {
        if 0 != acl_get_entry(oacl, position, &rentry) {
          err(1, "Invalid entry number '\(path)'")
        }

        if 0 != acl_delete_entry(oacl, rentry) {
          err(1, "Unable to delete entry '\(path)'")
        }
      }
      if 0 != acl_create_entry_np(&oacl, &newent, position) {
        err(1, "acl_create_entry() failed");
      }
      acl_copy_entry(newent, modifier);
    }
//  ma_exit:
//    *oaclp = oacl;
    return retval
  }

  enum ACLEntry : Int32 {
    case FIRST_ENTRY = 0
    case NEXT_ENTRY = -1
    case LAST_ENTRY = -2
    // Nonstandard ACL / entry flags
    case FLAG_DEFER_INHERIT = 1
    case FLAG_NO_INHERIT = 0x20000
    case ENTRY_INHERITED = 0x10
    case ENTRY_FILE_INHERIT = 0x20
    case ENTRY_DIRECTORY_INHERIT = 0x40
    case ENTRY_LIMIT_INHERIT = 0x80
    case ENTRY_ONLY_INHERIT = 0x100
  }

  func modify_file_acl(_ optflags : ACLOptions, _ path : String?, _ modifier : acl_t?, _ positionx : Int, _ inheritance_level : Int, _ follow : Bool) throws(CmdErr) -> Int {
/*
    acl_t oacl = NULL;
    unsigned  flag_new_acl = 0;
    acl_entry_t newent = NULL;
    acl_entry_t entry = NULL;
    unsigned retval = 0;

    extern int fflag;
*/

    /* XXX acl_get_file() returns a zero entry ACL if an ACL was previously
     * associated with the file, and has had its entries removed.
     * However, POSIX 1003.1e states that a zero entry ACL should be
     * returned if the caller asks for ACL_TYPE_DEFAULT, and no ACL is
     * associated with the path; it
     * does not specifically state that a request for ACL_TYPE_EXTENDED
     * should not return a zero entry ACL, however.
     */

    /* Determine if we've been given a zero entry ACL, or create an ACL if
     * none exists. There are some issues to consider here: Should we create
     * a zero-entry ACL for a delete or check canonicity operation?
     */

    var retval : Int = 0
    guard let path else {
      throw CmdErr(1)
    }

    if optflags.contains(.CLEAR_FLAG) {
      guard let fsec = filesec_init() else {
        err(1, "filesec_init() failed")
        fatalError()
      }
      defer { filesec_free(fsec) }

      let _FILESEC_REMOVE_ACL = UnsafeRawPointer(bitPattern: 1)
      if (filesec_set_property(fsec, FILESEC_ACL, _FILESEC_REMOVE_ACL) != 0) {
        err(1, "filesec_set_property() failed");
      }
      if follow {
        if (chmodx_np(path, fsec) != 0) {
          if !options.fflag {
            warn("Failed to clear ACL on file \(path)")
          }
          retval = 1
        }
      } else {
        if let fd = try? FileDescriptor.open(path, .readOnly, options: .symlink) { // open( path,  O_SYMLINK   );
          if fchmodx_np(fd.rawValue, fsec) != 0 {
            if !options.fflag {
              warn("Failed to clear ACL on file \(path)")
            }
            retval = 1
          }
          try? fd.close()
        } else {
          if !options.fflag {
            warn("Failed to open file \(path)")
          }
          retval = 1
        }
      }
      return retval
    }

    var oacl : acl_t?
    var newent : acl_entry_t? = nil
    var entry : acl_entry_t? = nil
    var flag_new_acl = false
    var position = positionx

    if optflags.contains(.FROM_STDIN) {
      oacl = acl_dup(modifier);
    } else {
      if follow {
        oacl = acl_get_file(path, ACL_TYPE_EXTENDED);
      } else {
        if let fd = try? FileDescriptor.open(path, .readOnly, options: .symlink) {
          oacl = acl_get_fd_np(fd.rawValue, ACL_TYPE_EXTENDED)
          try? fd.close()
        }
      }
      if oacl == nil || acl_get_entry(oacl, ACLEntry.FIRST_ENTRY.rawValue, &newent) != 0 {
        oacl = acl_init(1)
        if oacl == nil {
          err(1, "acl_init() failed");
        }
        flag_new_acl = true
        position = 0
      }

      if !flag_new_acl && optflags.containsAny(of: [.REMOVE_INHERIT_FLAG, .REMOVE_INHERITED_ENTRIES]) {
        var facl = acl_init(1)
        if facl == nil {
          err(1, "acl_init() failed")
        }

        while acl_get_entry(oacl, (entry == nil ? ACLEntry.FIRST_ENTRY : .NEXT_ENTRY).rawValue, &entry) == 0 {
          var eflags : acl_flagset_t? = nil
          var fent : acl_entry_t? = nil
          if (acl_get_flagset_np(&entry, &eflags) != 0) {
            err(1, "Unable to obtain flagset")
          }

          // FIXME: the UInt32 gets problematic for ACL_NEXT_ENTRY and ACL_LAST_ENTRY
          if 0 != acl_get_flag_np(eflags, acl_flag_t(UInt32(ACLEntry.ENTRY_INHERITED.rawValue))) {
            if optflags.contains(.REMOVE_INHERIT_FLAG) {
              acl_delete_flag_np(eflags, acl_flag_t(UInt32(ACLEntry.ENTRY_INHERITED.rawValue)))
              acl_set_flagset_np(&entry, eflags)
              acl_create_entry(&facl, &fent)
              acl_copy_entry(fent, entry);
            }
          }
          else {
            acl_create_entry(&facl, &fent);
            acl_copy_entry(fent, entry);
          }
        }

        if oacl != nil {
          acl_free(UnsafeMutableRawPointer(oacl!))
        }
        oacl = facl
      } else if optflags.contains(.TO_STDOUT) {
        var len = 0 /* need to get printacl() from ls(1) */
        let text = acl_to_text(oacl, &len);
        puts(text)
        acl_free(text)
      } else if optflags.contains(.CHECK_CANONICITY) {
        if flag_new_acl {
          warnx("No ACL currently associated with file '\(path)'")
        }
        retval = is_canonical(oacl) ? 1 : 0
      } else if optflags.contains(.SET_FLAG) && (position == -1) && !is_canonical(oacl) {
        warnx("The specified file '\(path)' does not have an ACL in canonical order, please specify a position with +a# ")
        retval = 1
      } else if (optflags.contains(.DELETE_FLAG) && position != -1) || optflags.contains(.CHECK_CANONICITY) {
        retval = try modify_acl(&oacl, nil, optflags, Int32(position), inheritance_level, flag_new_acl, path);
      } else if optflags.containsAny(of: [.REMOVE_INHERIT_FLAG, .REMOVE_INHERITED_ENTRIES]) && flag_new_acl {
        warnx("No ACL currently associated with file '\(path)'")
        retval = 1
      } else {
        if modifier == nil { /* avoid bus error in acl_get_entry */
          errx(1, "Internal error: modifier should not be NULL");
        }
        while acl_get_entry(modifier, (entry == nil ? ACLEntry.FIRST_ENTRY : .NEXT_ENTRY).rawValue, &entry) == 0 {
          retval += try modify_acl(&oacl, entry, optflags, Int32(position), inheritance_level, flag_new_acl, path)
        }
      }
    }

    /* XXX Potential race here, since someone else could've modified or
     * read the ACL on this file (with the intention of modifying it) in
     * the interval from acl_get_file() to acl_set_file(); we can
     * minimize one aspect of this  window by comparing the original acl
     * to a fresh one from acl_get_file() but we could consider a
     * "changeset" mechanism, common locking  strategy, or kernel
     * supplied reservation mechanism to prevent this race.
     */
    if !optflags.contains(.TO_STDOUT) && !optflags.contains(.CHECK_CANONICITY) {
      var status : Int32 = -1
      if (follow) {
        status = acl_set_file(path, ACL_TYPE_EXTENDED, oacl)
      } else {
        if let fd = try? FileDescriptor.open(path, .readOnly, options: .symlink) {
          status = acl_set_fd_np(fd.rawValue, oacl, ACL_TYPE_EXTENDED);
          try? fd.close()
        }
      }
      if (status != 0) {
        if !options.fflag {
          warn("Failed to set ACL on file '\(path)'")
        }
        retval = 1;
      }
    }

    if oacl != nil {
      acl_free(UnsafeMutableRawPointer(oacl!))
    }

    return retval;
  }
}
