// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin

/*
 * Defines common to all versions of cpio
 */
let TRAILER = "TRAILER!!!"  /* name in last archive record */

/*
 * Header encoding of the different file types
 */
/*#define  C_ISDIR     040000    /* Directory */
#define  C_ISFIFO   010000    /* FIFO */
#define  C_ISREG    0100000    /* Regular file */
#define  C_ISBLK     060000    /* Block special file */
#define  C_ISCHR     020000    /* Character special file */
#define  C_ISCTG    0110000    /* Reserved for contiguous files */
#define  C_ISLNK    0120000    /* Reserved for symbolic links */
#define  C_ISOCK    0140000    /* Reserved for sockets */
#define C_IFMT    0170000    /* type of file */
*/

typealias C6 = (CChar, CChar, CChar, CChar, CChar, CChar)
typealias C11 = (CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar)
/*
 * Data Interchange Format - Extended cpio header format - POSIX 1003.1-1990
 */
struct HD_CPIO {
  var c_magic : C6  /* magic cookie */
  var c_dev : C6    /* device number */
  var c_ino : C6    /* inode number */
  var c_mode : C6   /* file type/access */
  var c_uid : C6    /* owners uid */
  var c_gid : C6    /* owners gid */
  var c_nlink : C6  /* # of links at archive creation */
  var c_rdev : C6   /* block/char major/minor # */
  var c_mtime : C11 /* modification time */
  var c_namesize : C6   /* length of pathname */
  var c_filesize : C11  /* length of file in bytes */
//#ifdef __APPLE__
}
//#else
//} HD_CPIO __aligned(1);
//#endif

let MAGIC = 0o070707    /* transportable archive id */

//#ifdef _PAX_
let AMAGIC = "070707"  /* ascii equivalent string of MAGIC */
let CPIO_MASK = 0x3ffff    /* bits valid in the dev/ino fields */
          /* used for dev/inode remaps */
// #endif /* _PAX_ */

typealias C2 = (CChar, CChar)
/*
 * Binary cpio header structure
 *
 * CAUTION! CAUTION! CAUTION!
 * Each field really represents a 16 bit short (NOT ASCII). Described as
 * an array of chars in an attempt to improve portability!!
 */
struct HD_BCPIO {
  var h_magic : C2
  var h_dev : C2
  var h_ino: C2
  var h_mode : C2
  var h_uid : C2
  var h_gid : C2
  var h_nlink : C2
  var h_rdev : C2
  var h_mtime_1 : C2
  var h_mtime_2 : C2
  var h_namesize : C2
  var h_filesize_1 : C2
  var h_filesize_2 : C2
  // #ifdef __APPLE__
}
// #else
// } HD_BCPIO __aligned(1);
// #endif

// #ifdef _PAX_
/*
 * extraction and creation macros for binary cpio
 */
#define SHRT_EXT(ch)  ((((unsigned)(ch)[0])<<8) | (((unsigned)(ch)[1])&0xff))
#define RSHRT_EXT(ch)  ((((unsigned)(ch)[1])<<8) | (((unsigned)(ch)[0])&0xff))
#define CHR_WR_0(val)  ((char)(((val) >> 24) & 0xff))
#define CHR_WR_1(val)  ((char)(((val) >> 16) & 0xff))
#define CHR_WR_2(val)  ((char)(((val) >> 8) & 0xff))
#define CHR_WR_3(val)  ((char)((val) & 0xff))

/*
 * binary cpio masks and pads
 */
#define BCPIO_PAD(x)  ((2 - ((x) & 1)) & 1)  /* pad to next 2 byte word */
#define BCPIO_MASK  0xffff      /* mask for dev/ino fields */
// #endif /* _PAX_ */

typealias C8 = (CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar)
/*
 * System VR4 cpio header structure (with/without file data crc)
 */
struct HD_VCPIO {
  var c_magic : C6  /* magic cookie */
  var c_ino : C8    /* inode number */
  var c_mode : C8   /* file type/access */
  var c_uid : C8    /* owners uid */
  var c_gid : C8    /* owners gid */
  var c_nlink : C8  /* # of links at archive creation */
  var c_mtime : C8  /* modification time */
  var c_filesize : C8 /* length of file in bytes */
  var c_maj : C8    /* block/char major # */
  var c_min : C8    /* block/char minor # */
  var c_rmaj : C8   /* special file major # */
  var c_rmin : C8   /* special file minor # */
  var c_namesize : C8 /* length of pathname */
  var c_chksum : C8   /* 0 OR CRC of bytes of FILE data */
// #ifdef __APPLE__
}
// #else
// } HD_VCPIO __aligned(1);
// #endif

let VMAGIC = 0o070701    /* sVr4 new portable archive id */
let VCMAGIC = 0o070702    /* sVr4 new portable archive id CRC */
// #ifdef _PAX_
let AVMAGIC = "070701"  /* ascii string of above */
let AVCMAGIC = "070702"  /* ascii string of above */
#define VCPIO_PAD(x)  ((4 - ((x) & 3)) & 3)  /* pad to next 4 byte word */
#define VCPIO_MASK  0xffffffff  /* mask for dev/ino fields */
// #endif /* _PAX_ */




class bcpio : pax.FSUB {
  var name: String { get { "bcpio" } set { } }
  var bsz: UInt { get { 5120 } set { } }
  var hsz: Int { get { MemoryLayout<HD_BCPIO>.size } set { } }
  var udev: UInt { get { 1 } set { } }
  var hlk: Bool { get { false } set { } }
  var blkalgn: Bool { get { false } set { } }
  var inhead: Bool { get { true } set { } }

  func trail_tar(_: [UInt8], _: inout Int) -> Bool? {
    fatalError("only for tar")
  }

  init() {  }

  /*
   * Routines which support the different cpio versions
   */

  static int swp_head;		/* binary cpio header byte swap */

  /*
   * Routines common to all versions of cpio
   */

  /*
   * cpio_strd()
   *	Fire up the hard link detection code
   * Return:
   *      0 if ok -1 otherwise (the return values of lnk_start())
   */

  func st_rd() -> Bool {  // was cpio_strd
//    return(lnk_start())
  }

  /*
   * cpio_trail()
   *	Called to determine if a header block is a valid trailer. We are
   *	passed the block, the in_sync flag (which tells us we are in resync
   *	mode; looking for a valid header), and cnt (which starts at zero)
   *	which is used to count the number of empty blocks we have seen so far.
   * Return:
   *	0 if a valid trailer, -1 if not a valid trailer,
   */

  func trail_cpio(_ arcn : pax.ARCHD) -> Bool {
    /*
     * look for trailer id in file we are about to process
     */
    if arcn.name == TRAILER && arcn.sb.size == 0 {
      return false
    }
    return true
  }

  /*
   * com_rd()
   *	operations common to all cpio read functions.
   * Return:
   *	0
   */

  private func com_rd(_ arcn : inout ARCHD) -> Bool {
    arcn.skip = 0
    arcn.pat = nil
    arcn.org_name = arcn.name
    switch arcn.sb.filetype {
      case .fifo:
        arcn.type = .FIF
      case .directory:
        arcn.type = .DIR
      case .blockDevice:
        arcn.type = .BLK
      case .characterDevice:
        arcn.type = .CHR
      case .symbolicLink:
        arcn.type = .SLK
      case .socket:
        arcn.type = .SCK
//      case C_ISCTG:  where is this set?
      case .regular:
        fallthrough
      default:
        /*
         * we have file data, set up skip (pad is set in the format
         * specific sections)
         */
        // arcn.sb.permissions = arcn.sb.permissions // |
        arcn.sb.filetype = .regular
        arcn.type = .REG
        arcn.skip = Int(arcn.sb.size)
        break;
    }

    tables.chk_lnk(arcn)
    return false
  }

  /*
   * cpio_endwr()
   *	write the special file with the name trailer in the proper format
   * Return:
   *	result of the write of the trailer from the cpio specific write func
   */

  func end_wr() -> Bool { // was cpio_endwr
    ARCHD last;

    /*
     * create a trailer request and call the proper format write function
     */
    memset(&last, 0, sizeof(last));
    last.nlen = sizeof(TRAILER) - 1;
    last.type = PAX_REG;
    last.sb.st_nlink = 1;
    (void)strlcpy(last.name, TRAILER, sizeof(last.name));
    return((*frmt->wr)(&last));
  }

  /*
   * rd_nam()
   *	read in the file name which follows the cpio header
   * Return:
   *	0 if ok, -1 otherwise
   */

  private func rd_nam(_ arcn : pax.ARCHD, _ nsz : Int) -> Bool  {
    /*
     * do not even try bogus values
     */
    if ((nsz == 0) || (nsz > (int)sizeof(arcn.name))) {
      paxwarn(1, "Cpio file name length %d is out of range", nsz);
      return(-1);
    }

    /*
     * read the name and make sure it is not empty and is \0 terminated
     */
    if ((rd_wrbuf(arcn.name,nsz) != nsz) || (arcn.name[nsz-1] != '\0') ||
        (arcn.name[0] == '\0')) {
      paxwarn(1, "Cpio file name in header is corrupted");
      return(-1);
    }
    return(0);
  }

  /*
   * rd_ln_nm()
   *	read in the link name for a file with links. The link name is stored
   *	like file data (and is NOT \0 terminated!)
   * Return:
   *	0 if ok, -1 otherwise
   */

  private func rd_ln_nm(_ arcn : pax.ARCHD) -> Bool {
    /*
     * check the length specified for bogus values
     */
    if ((arcn.sb.st_size == 0) ||
        ((size_t)arcn.sb.st_size >= sizeof(arcn.ln_name))) {
      paxwarn(1, "Cpio link name length is invalid: %ju",
              (uintmax_t)arcn.sb.st_size);
      return(-1);
    }

    /*
     * read in the link name and \0 terminate it
     */
    if (rd_wrbuf(arcn.ln_name, (int)arcn.sb.st_size) !=
        (int)arcn.sb.st_size) {
      paxwarn(1, "Cpio link name read error");
      return(-1);
    }
    arcn.ln_nlen = arcn.sb.st_size;
    arcn.ln_name[arcn.ln_nlen] = '\0';

    /*
     * watch out for those empty link names
     */
    if (arcn.ln_name[0] == '\0') {
      paxwarn(1, "Cpio link name is corrupt");
      return(-1);
    }
    return(0);
  }


  /*
   * cpio_stwr()
   *	start up the device mapping table
   * Return:
   *	0 if ok, -1 otherwise (what dev_start() returns)
   */

  func st_wr() -> Bool { // was cpio_stwr
    return(dev_start());
  }




  /*
   * Routines common to the old binary header cpio
   */

  /*
   * bcpio_id()
   *      determine if a block given to us is an old binary cpio header
   *	(with/without header byte swapping)
   * Return:
   *      0 if a valid header, -1 otherwise
   */

  func id(_ blk : [UInt8]) -> Bool { // was bcpio_id
    if (size < (int)sizeof(HD_BCPIO)) {
      return(-1);
    }

    /*
     * check both normal and byte swapped magic cookies
     */
    if (((u_short)SHRT_EXT(blk)) == MAGIC) {
      return(0);
    }
    if (((u_short)RSHRT_EXT(blk)) == MAGIC) {
      if (!swp_head) {
        ++swp_head;
      }
      return(0);
    }
    return(-1);
  }

  /*
   * bcpio_rd()
   *	determine if a buffer is an old binary archive entry. (It may have byte
   *	swapped header) convert and store the values in the ARCHD parameter.
   *	This is a very old header format and should not really be used.
   * Return:
   *	0 if a valid header, -1 otherwise.
   */

  func rd(_ buf : [UInt8]) -> ARCHD? { // was bcpio_rd
    HD_BCPIO *hd;
    int nsz;

    var arcn = ARCHD()

    /*
     * check the header
     */
    if (bcpio_id(buf, hsz) < 0) {
      return(-1);
    }

    arcn.pad = 0
    hd = (HD_BCPIO *)buf;
    if (swp_head) {
      /*
       * header has swapped bytes on 16 bit boundaries
       */
      arcn.sb.st_dev = (dev_t)(RSHRT_EXT(hd->h_dev));
      arcn.sb.st_ino = (ino_t)(RSHRT_EXT(hd->h_ino));
      arcn.sb.st_mode = (mode_t)(RSHRT_EXT(hd->h_mode));
      arcn.sb.st_uid = (uid_t)(RSHRT_EXT(hd->h_uid));
      arcn.sb.st_gid = (gid_t)(RSHRT_EXT(hd->h_gid));
      arcn.sb.st_nlink = (nlink_t)(RSHRT_EXT(hd->h_nlink));
      arcn.sb.st_rdev = (dev_t)(RSHRT_EXT(hd->h_rdev));
      arcn.sb.st_mtime = (time_t)(RSHRT_EXT(hd->h_mtime_1));
      arcn.sb.st_mtime =  (arcn.sb.st_mtime << 16) |
      ((time_t)(RSHRT_EXT(hd->h_mtime_2)));
      arcn.sb.st_size = (off_t)(RSHRT_EXT(hd->h_filesize_1));
      arcn.sb.st_size = (arcn.sb.st_size << 16) |
      ((off_t)(RSHRT_EXT(hd->h_filesize_2)));
      nsz = (int)(RSHRT_EXT(hd->h_namesize));
    } else {
      arcn.sb.st_dev = (dev_t)(SHRT_EXT(hd->h_dev));
      arcn.sb.st_ino = (ino_t)(SHRT_EXT(hd->h_ino));
      arcn.sb.st_mode = (mode_t)(SHRT_EXT(hd->h_mode));
      arcn.sb.st_uid = (uid_t)(SHRT_EXT(hd->h_uid));
      arcn.sb.st_gid = (gid_t)(SHRT_EXT(hd->h_gid));
      arcn.sb.st_nlink = (nlink_t)(SHRT_EXT(hd->h_nlink));
      arcn.sb.st_rdev = (dev_t)(SHRT_EXT(hd->h_rdev));
      arcn.sb.st_mtime = (time_t)(SHRT_EXT(hd->h_mtime_1));
      arcn.sb.st_mtime =  (arcn.sb.st_mtime << 16) |
      ((time_t)(SHRT_EXT(hd->h_mtime_2)));
      arcn.sb.st_size = (off_t)(SHRT_EXT(hd->h_filesize_1));
      arcn.sb.st_size = (arcn.sb.st_size << 16) |
      ((off_t)(SHRT_EXT(hd->h_filesize_2)));
      nsz = (int)(SHRT_EXT(hd->h_namesize));
    }
    arcn.sb.st_ctime = arcn.sb.st_atime = arcn.sb.st_mtime;

    /*
     * check the file name size, if bogus give up. otherwise read the file
     * name
     */
    if (nsz < 2) {
      return(-1);
    }
    arcn.nlen = nsz - 1;
    if (rd_nm(arcn, nsz) < 0) {
      return(-1);
    }

    /*
     * header + file name are aligned to 2 byte boundaries, skip if needed
     */
    if (rd_skip((off_t)(BCPIO_PAD(hsz + nsz))) < 0) {
      return(-1);
    }

    /*
     * if not a link (or a file with no data), calculate pad size (for
     * padding which follows the file data), clear the link name and return
     */
    if (((arcn.sb.st_mode & C_IFMT) != C_ISLNK)||(arcn.sb.st_size == 0)){
      /*
       * we have a valid header (not a link)
       */
      arcn.ln_nlen = 0;
      arcn.ln_name[0] = '\0';
      arcn.pad = BCPIO_PAD(arcn.sb.st_size);
      return(com_rd(arcn));
    }

    if ((rd_ln_nm(arcn) < 0) ||
        (rd_skip((off_t)(BCPIO_PAD(arcn.sb.st_size))) < 0)) {
      return(-1);
    }

    /*
     * we have a valid header (with a link)
     */
    return(com_rd(arcn));
  }

  /*
   * bcpio_endrd()
   *      no cleanup needed here, just return size of the trailer (for append)
   * Return:
   *      size of trailer header in this format
   */

  func end_rd() -> Int { // was bcpio_endrd
    return (hsz + sizeof(TRAILER) +
                   (BCPIO_PAD(sizeof(HD_BCPIO) + sizeof(TRAILER))));
  }

  /*
   * bcpio_wr()
   *	copy the data in the ARCHD to buffer in old binary cpio format
   *	There is a real chance of field overflow with this critter. So we
   *	always check that the conversion is ok. nobody in their right mind
   *	should write an archive in this format...
   * Return
   *      0 if file has data to be written after the header, 1 if file has NO
   *	data to write after the header, -1 if archive write failed
   */

  func wr(_ arcn : pax.ARCHD) -> Bool? { // was bcpio_wr
    HD_BCPIO *hd;
    int nsz;
    HD_BCPIO hdblk;
    off_t t_offt;
    int t_int;
    time_t t_timet;

    /*
     * check and repair truncated device and inode fields in the cpio
     * header
     */
    if (map_dev(arcn, (u_long)BCPIO_MASK, (u_long)BCPIO_MASK) < 0) {
      return(-1);
    }

    if ((arcn.type != PAX_BLK) && (arcn.type != PAX_CHR)) {
      arcn.sb.st_rdev = 0;
    }
    hd = &hdblk;

    switch arc.type {
      case .CTG, .REG, .HRG:
        /*
         * caller will copy file data to the archive. tell him how
         * much to pad.
         */
        arcn.pad = BCPIO_PAD(arcn.sb.st_size);
        hd->h_filesize_1[0] = CHR_WR_0(arcn.sb.st_size);
        hd->h_filesize_1[1] = CHR_WR_1(arcn.sb.st_size);
        hd->h_filesize_2[0] = CHR_WR_2(arcn.sb.st_size);
        hd->h_filesize_2[1] = CHR_WR_3(arcn.sb.st_size);
        t_offt = (off_t)(SHRT_EXT(hd->h_filesize_1));
        t_offt = (t_offt<<16) | ((off_t)(SHRT_EXT(hd->h_filesize_2)));
        if (arcn.sb.st_size != t_offt) {
          paxwarn(1,"File is too large for bcpio format %s",
                  arcn.org_name);
          return(1);
        }
        break;
      case .SLK:
        /*
         * no file data for the caller to process, the file data has
         * the size of the link
         */
        arcn.pad = 0L;
        hd->h_filesize_1[0] = CHR_WR_0(arcn.ln_nlen);
        hd->h_filesize_1[1] = CHR_WR_1(arcn.ln_nlen);
        hd->h_filesize_2[0] = CHR_WR_2(arcn.ln_nlen);
        hd->h_filesize_2[1] = CHR_WR_3(arcn.ln_nlen);
        t_int = (int)(SHRT_EXT(hd->h_filesize_1));
        t_int = (t_int << 16) | ((int)(SHRT_EXT(hd->h_filesize_2)));
        if (arcn.ln_nlen != t_int) {
          goto out;
        }
        break;
      default:
        /*
         * no file data for the caller to process
         */
        arcn.pad = 0L;
        hd->h_filesize_1[0] = (char)0;
        hd->h_filesize_1[1] = (char)0;
        hd->h_filesize_2[0] = (char)0;
        hd->h_filesize_2[1] = (char)0;
        break;
    }

    /*
     * build up the rest of the fields
     */
    hd->h_magic[0] = CHR_WR_2(MAGIC);
    hd->h_magic[1] = CHR_WR_3(MAGIC);
    hd->h_dev[0] = CHR_WR_2(arcn.sb.st_dev);
    hd->h_dev[1] = CHR_WR_3(arcn.sb.st_dev);
    if (arcn.sb.st_dev != (dev_t)(SHRT_EXT(hd->h_dev))) {
      goto out;
    }
    hd->h_ino[0] = CHR_WR_2(arcn.sb.st_ino);
    hd->h_ino[1] = CHR_WR_3(arcn.sb.st_ino);
    if (arcn.sb.st_ino != (ino_t)(SHRT_EXT(hd->h_ino))) {
      goto out;
    }
    hd->h_mode[0] = CHR_WR_2(arcn.sb.st_mode);
    hd->h_mode[1] = CHR_WR_3(arcn.sb.st_mode);
    if (arcn.sb.st_mode != (mode_t)(SHRT_EXT(hd->h_mode))) {
      goto out;
    }
    hd->h_uid[0] = CHR_WR_2(arcn.sb.st_uid);
    hd->h_uid[1] = CHR_WR_3(arcn.sb.st_uid);
    if (arcn.sb.st_uid != (uid_t)(SHRT_EXT(hd->h_uid))) {
      goto out;
    }
    hd->h_gid[0] = CHR_WR_2(arcn.sb.st_gid);
    hd->h_gid[1] = CHR_WR_3(arcn.sb.st_gid);
    if (arcn.sb.st_gid != (gid_t)(SHRT_EXT(hd->h_gid))) {
      goto out;
    }
    hd->h_nlink[0] = CHR_WR_2(arcn.sb.st_nlink);
    hd->h_nlink[1] = CHR_WR_3(arcn.sb.st_nlink);
    if (arcn.sb.st_nlink != (nlink_t)(SHRT_EXT(hd->h_nlink))) {
      goto out;
    }
    hd->h_rdev[0] = CHR_WR_2(arcn.sb.st_rdev);
    hd->h_rdev[1] = CHR_WR_3(arcn.sb.st_rdev);
    if (arcn.sb.st_rdev != (dev_t)(SHRT_EXT(hd->h_rdev))) {
      goto out;
    }
    hd->h_mtime_1[0] = CHR_WR_0(arcn.sb.st_mtime);
    hd->h_mtime_1[1] = CHR_WR_1(arcn.sb.st_mtime);
    hd->h_mtime_2[0] = CHR_WR_2(arcn.sb.st_mtime);
    hd->h_mtime_2[1] = CHR_WR_3(arcn.sb.st_mtime);
    t_timet = (time_t)(SHRT_EXT(hd->h_mtime_1));
    t_timet =  (t_timet << 16) | ((time_t)(SHRT_EXT(hd->h_mtime_2)));
    if (arcn.sb.st_mtime != t_timet) {
      goto out;
    }
    nsz = arcn.nlen + 1;
    hd->h_namesize[0] = CHR_WR_2(nsz);
    hd->h_namesize[1] = CHR_WR_3(nsz);
    if (nsz != (int)(SHRT_EXT(hd->h_namesize))) {
      goto out;
    }

    /*
     * write the header, the file name and padding as required.
     */
    if ((wr_rdbuf((char *)&hdblk, (int)sizeof(HD_BCPIO)) < 0) ||
        (wr_rdbuf(arcn.name, nsz) < 0) ||
        (wr_skip((off_t)(BCPIO_PAD(sizeof(HD_BCPIO) + nsz))) < 0)) {
      paxwarn(1, "Could not write bcpio header for %s", arcn.org_name);
      return(-1);
    }

    /*
     * if we have file data, tell the caller we are done
     */
    if ((arcn.type == PAX_CTG) || (arcn.type == PAX_REG) ||
        (arcn.type == PAX_HRG)) {
      return(0);
    }

    /*
     * if we are not a link, tell the caller we are done, go to next file
     */
    if (arcn.type != PAX_SLK) {
      return(1);
    }

    /*
     * write the link name, tell the caller we are done.
     */
    if ((wr_rdbuf(arcn.ln_name, arcn.ln_nlen) < 0) ||
        (wr_skip((off_t)(BCPIO_PAD(arcn.ln_nlen))) < 0)) {
      paxwarn(1,"Could not write bcpio link name for %s",arcn.org_name);
      return(-1);
    }
    return(1);

  out:
    /*
     * header field is out of range
     */
    paxwarn(1,"Bcpio header field is too small for file %s", arcn.org_name);
    return(1);
  }



  // ==============================================================================


  /*
   * bad_opt()
   *  generic routine used to complain about a format specific options
   *  when the format does not support options.
   */

  func other_options() -> Bool { // was bad_opt
    OPLIST *opt;

    if (ophead == NULL)
        return(0);
    /*
     * print all we were given
     */
    Tty.paxwarn(true,"These format options are not supported");

    while ((opt = opt_next()) != NULL) {
      if (opt->separator == SEP_EQ) {
        (void)fprintf(stderr, "\t%s = %s\n", opt->name, opt->value);
      } else if (opt->separator == SEP_COLONEQ ) {
        (void)fprintf(stderr, "\t%s := %s\n", opt->name, opt->value);
      } else {  /* SEP_NONE */
        (void)fprintf(stderr, "\t%s\n", opt->name);
      }
    }

    pax_usage();
    return(0);
  }


}
