// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin


extension pax {

  /*
   * cpio_options()
   *  look at the user specified flags. set globals as required and check if
   *  the user specified a legal set of flags. If not, complain and exit
   */

  func cpio_options() throws(CmdErr) -> CommandOptions {
    var options = CommandOptions()

/*    int c;
    size_t i;
    char *str;
    FSUB tmp;
    FILE *fp;
*/

    options.kflag = true
    options.pids = true
    options.pmode = true
    options.pmtime = false
    options.arcname = nil
    options.dflag = true
    options.act = OpModes(rawValue: 0)!
    options.nodirs = true

    let opts = "abcdfiklmoprstuvzABC:E:F:H:I:LO:SZ6"
    let go = BSDGetopt(opts)
    while let (c, v) = try go.getopt() {
      switch c {
        case "a":
          /*
           * preserve access time on files read
           */
          options.tflag = true
        case "b":
          /*
           * swap bytes and half-words when reading data
           */
          break
        case "c":
          /*
           * ASCII cpio header
           */
          options.frmt = cpio() // &(fsub[F_ACPIO]);

        case "d":
          /*
           * create directories as needed
           */
          options.nodirs = false
        case "f":
          /*
           * invert meaning of pattern list
           */
          options.cflag = true
        case "i":
          /*
           * restore an archive
           */
          options.act = .EXTRACT

        case "k":
          break
        case "l":
          /*
           * use links instead of copies when possible
           */
          options.lflag = true

        case "m":
          /*
           * preserve modification time
           */
          options.pmtime = true

        case "o":
          /*
           * create an archive
           */
          options.act = .ARCHIVE;
          options.frmt = vcpio_crc() //  &(fsub[F_CPIO]);

        case "p":
          /*
           * copy-pass mode
           */
          options.act = .COPY

        case "r":
          /*
           * interactively rename files
           */
          options.iflag = true

        case "s":
          /*
           * swap bytes after reading data
           */
          break
        case "t":
          /*
           * list contents of archive
           */
          options.act = .LIST
          options.listf = FileDescriptor.standardOutput

        case "u":
          /*
           * replace newer files
           */
          options.kflag = false

        case "v":
          /*
           * verbose operation mode
           */
          options.vflag = true

        case "z":
          /*
           * use gzip.  Non standard option.
           */
          options.gzip_program = GZIP_CMD

        case "A":
          /*
           * append mode
           */
          options.act = .APPND

        case "B":
          /*
           * Use 5120 byte block size
           */
          options.wrblksz = 5120

        case "C":
          /*
           * set block size in bytes
           */
          // FIXME: throw error for invalid Int?
          options.wrblksz = Int(v)

        case "E":
          /*
           * file with patterns to extract or list
           */
          if ((fp = fopen(optarg, "r")) == NULL) {
            paxwarn(1, "Unable to open file '%s' for read", optarg);
            cpio_usage();
          }
          while ((str = get_line(fp)) != NULL) {
            pat_add(str, NULL);
          }
          fclose(fp);
          if (get_line_error) {
            paxwarn(1, "Problem with file '%s'", optarg);
            cpio_usage();
          }

        case "F", "I", "O":
          /*
           * filename where the archive is stored
           */
          if v == "-" {
            /*
             * treat a - as stdin
             */
            options.arcname = nil
          } else {
            options.arcname = v
          }

        case "H":
          /*
           * specify an archive format on write
           */
          let fsubs = ["bcpio" : bcpio.self, "cpio" : cpio.self, "pax" : paxer.self, "sv4cpio" : vcpio.self, "sv4crc" : vcpio_crc.self, "tar" : tar.self, "ustar" : ustar.self]
          if let frmt = fsubs[v] {
            options.frmt = frmt
            break
          }

          paxwarn(true, "Unknown -H format: \(v)")
          var se = FileDescriptor.standardError
          print("cpio: Known -H formats are:", terminator: "", to: &se)
          for (i = 0; i < (sizeof(fsub)/sizeof(FSUB)); ++i) {
            (void)fprintf(stderr, " %s", fsub[i].name);
          }
          (void)fputs("\n\n", stderr);
          cpio_usage();
          break;
        case "L":
          /*
           * follow symbolic links
           */
          options.Lflag = true

        case "S":
          /*
           * swap halfwords after reading data
           */
          break
        case "Z":
          /*
           * use compress.  Non standard option.
           */
          options.gzip_program = COMPRESS_CMD

        case "6":
          /*
           * process Version 6 cpio format
           */
          options.frmt = &(fsub[F_OCPIO]);
          break;
        case "?":
        default:
          cpio_usage();
          break;
      }
      argc -= optind;
      argv += optind;

      /*
       * process the args as they are interpreted by the operation mode
       */
      switch options.act {
        case .LIST, .EXTRACT:
          while (*argv != NULL)
                  if (pat_add(*argv++, NULL) < 0)
                  cpio_usage();
          break;
        case .COPY:
          if (*argv == NULL) {
            paxwarn(0, "Destination directory was not supplied");
            cpio_usage();
          }
          dirptr = *argv;
          if (mkpath(dirptr) < 0)
              cpio_usage();
          --argc;
          ++argv;
          fallthrough
        case .ARCHIVE, .APPND:
          if (*argv != NULL)
              cpio_usage();
          /*
           * no read errors allowed on updates/append operation!
           */
          maxflt = 0;
          while ((str = get_line(stdin)) != NULL) {
            ftree_add(str, 0);
          }
          if (get_line_error) {
            paxwarn(1, "Problem while reading stdin");
            cpio_usage();
          }
          break;
        default:
          cpio_usage();
          break;
      }
    }
  }
}
