// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin

class cpio : bcpio {
  override var name: String { get { "cpio" } set { } }
  override var hsz: Int { get { MemoryLayout<HD_CPIO>.size } set { } }

  /*
   * Routines common to the extended byte oriented cpio format
   */

  /*
   * cpio_id()
   *      determine if a block given to us is a valid extended byte oriented
   *  cpio header
   * Return:
   *      0 if a valid header, -1 otherwise
   */

  override func id(_ blk : [UInt8]) -> Result { // was cpio_id
    if blk.count < hsz { return .failed }
    let b = Array(AMAGIC.utf8CString.dropLast())
    let a = blk.prefix(AMAGIC.count).map { CChar($0) }
    if a != b {
      return .failed
    }
    return .ok
  }

  /*
   * cpio_rd()
   *  determine if a buffer is a byte oriented extended cpio archive entry.
   *  convert and store the values in the ARCHD parameter.
   * Return:
   *  0 if a valid header, -1 otherwise.
   */

  override func rd(_ buf : [UInt8]) -> ARCHD? {  // was cpio_rd

    var arcn = ARCHD()

    /*
     * check that this is a valid header, if not return -1
     */
    if id(buf, hsz) {
      return nil
    }
    let hd = (HD_CPIO *)buf;

    /*
     * byte oriented cpio (posix) does not have padding! extract the octal
     * ascii fields from the header
     */
    arcn.pad = 0
    arcn.sb.device = (dev_t)asc_ul(hd->c_dev, sizeof(hd->c_dev), OCT);
    arcn.sb.inode = (ino_t)asc_ul(hd->c_ino, sizeof(hd->c_ino), OCT);
    arcn.sb.st_mode = (mode_t)asc_ul(hd->c_mode, sizeof(hd->c_mode), OCT);
    arcn.sb.userId = (uid_t)asc_ul(hd->c_uid, sizeof(hd->c_uid), OCT);
    arcn.sb.groupId = (gid_t)asc_ul(hd->c_gid, sizeof(hd->c_gid), OCT);
    arcn.sb.links = (nlink_t)asc_ul(hd->c_nlink, sizeof(hd->c_nlink),
                                        OCT);
    arcn.sb.rawDevice = (dev_t)asc_ul(hd->c_rdev, sizeof(hd->c_rdev), OCT);
    arcn.sb.lastModified = (time_t)asc_uqd(hd->c_mtime, sizeof(hd->c_mtime),
                                        OCT);
    arcn.sb.ctime = arcn.sb.lastAccessed = arcn.sb.lastModified;
    arcn.sb.size = (off_t)asc_uqd(hd->c_filesize,sizeof(hd->c_filesize),
                                      OCT);

    /*
     * check name size and if valid, read in the name of this entry (name
     * follows header in the archive)
     */
    if ((nsz = (int)asc_ul(hd->c_namesize,sizeof(hd->c_namesize),OCT)) < 2) {
      return .failed;
    }
    arcn.nlen = nsz - 1;
    if (rd_nm(arcn, nsz) < 0) {
      return .failed;
    }

    if (((arcn.sb.st_mode&C_IFMT) != C_ISLNK)||(arcn.sb.size == 0)) {
      /*
       * no link name to read for this file
       */
      arcn.ln_nlen = 0;
      arcn.ln_name[0] = '\0';
      return(com_rd(arcn));
    }

    /*
     * check link name size and read in the link name. Link names are
     * stored like file data.
     */
    if (rd_ln_nm(arcn) < 0) {
      return .failed;
    }

    /*
     * we have a valid header (with a link)
     */
    return(com_rd(arcn));
  }

  /*
   * cpio_endrd()
   *      no cleanup needed here, just return size of the trailer (for append)
   * Return:
   *      size of trailer header in this format
   */

  override func end_rd() -> Int { // was  cpio_endrd(void)
    return hsz + TRAILER.count
  }

  /*
   * cpio_wr()
   *  copy the data in the ARCHD to buffer in extended byte oriented cpio
   *  format.
   * Return
   *      0 if file has data to be written after the header, 1 if file has NO
   *  data to write after the header, -1 if archive write failed
   */

  override func wr(_ arcn: ARCHD) -> Result { // was cpio_wr(ARCHD *arcn)

    HD_CPIO *hd;
    int nsz;
    HD_CPIO hdblk;

    /*
     * check and repair truncated device and inode fields in the header
     */
    if (map_dev(arcn, CPIO_MASK, CPIO_MASK) < 0) {
      return .failed
    }

    arcn.pad = 0
    nsz = arcn.nlen + 1
    hd = &hdblk;
    if arcn.type != .BLK && arcn.type != .CHR {
      arcn.sb.rawDevice = 0
    }

    switch arcn.type {
      case .CTG, .REG, .HRG:
        /*
         * set data size for file data
         */
        if (uqd_asc((u_quad_t)arcn.sb.size, hd.c_filesize,
                    sizeof(hd.c_filesize), OCT)) {
          Tty.paxwarn(true,"File is too large for cpio format \(arcn.org_name)")
          return .partial
        }
        break;
      case .SLK:
        /*
         * set data size to hold link name
         */
        if (ul_asc((u_long)arcn.ln_nlen, hd->c_filesize,
                   sizeof(hd->c_filesize), OCT)) {
          goto out;
        }
        break;
      default:
        /*
         * all other file types have no file data
         */
        if (ul_asc((u_long)0, hd->c_filesize, sizeof(hd->c_filesize),
                   OCT)) {
          goto out;
        }
        break;
    }

    /*
     * copy the values to the header using octal ascii
     */
    if (ul_asc((u_long)MAGIC, hd.c_magic, sizeof(hd.c_magic), OCT) ||
        ul_asc((u_long)arcn.sb.device, hd.c_dev, sizeof(hd.c_dev),
               OCT) ||
        ul_asc((u_long)arcn.sb.inode, hd.c_ino, sizeof(hd.c_ino),
               OCT) ||
        ul_asc((u_long)arcn.sb.st_mode, hd.c_mode, sizeof(hd.c_mode),
               OCT) ||
        ul_asc((u_long)arcn.sb.userId, hd.c_uid, sizeof(hd.c_uid),
               OCT) ||
        ul_asc((u_long)arcn.sb.groupId, hd.c_gid, sizeof(hd.c_gid),
               OCT) ||
        ul_asc((u_long)arcn.sb.links, hd.c_nlink, sizeof(hd.c_nlink),
               OCT) ||
        ul_asc((u_long)arcn.sb.rawDevice, hd.c_rdev, sizeof(hd.c_rdev),
               OCT) ||
        ul_asc((u_long)arcn.sb.lastModified,hd.c_mtime,sizeof(hd.c_mtime),
               OCT) ||
        ul_asc((u_long)nsz, hd.c_namesize, sizeof(hd.c_namesize), OCT)) {
      goto out;
    }

    /*
     * write the file name to the archive
     */
    if ((wr_rdbuf((char *)&hdblk, hsz) < 0) ||
        (wr_rdbuf(arcn.name, nsz) < 0)) {
      Tty.paxwarn(true, "Unable to write cpio header for %s", arcn.org_name);
      return .failed
    }

    /*
     * if this file has data, we are done. The caller will write the file
     * data, if we are link tell caller we are done, go to next file
     */
    if arcn.type == .CTG || arcn.type == .REG || arcn.type == .HRG {
      return .ok
    }
    if arcn.type != .SLK {
      return .partial
    }

    /*
     * write the link name to the archive, tell the caller to go to the
     * next file as we are done.
     */
    if (wr_rdbuf(arcn.ln_name, arcn.ln_nlen) < 0) {
      Tty.paxwarn(true,"Unable to write cpio link name for \(arcn.org_name)")
      return .failed
    }
    return .partial

  out:
    /*
     * header field is out of range
     */
    Tty.paxwarn(true, "Cpio header field is too small to store file %s",
            arcn.org_name);
    return .partial
  }

}

