// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration

// FIXME: is this really a protocol?
/*
* Format Specific Routine Table
*
* The format specific routine table allows new archive formats to be quickly
* added. Overall pax operation is independent of the actual format used to
* form the archive. Only those routines which deal directly with the archive
* are tailored to the oddities of the specific format. All other routines are
* independent of the archive format. Data flow in and out of the format
* dependent routines pass pointers to ARCHD structure (described below).
*/
protocol FSUB {
  var name : String { get set }  /* name of format, this is the name the user */
  /* gives to -x option to select it. */
  var bsz : UInt { get set }    /* default block size. used when the user */
  /* does not specify a blocksize for writing */
  /* Appends continue to with the blocksize */
  /* the archive is currently using. */
  var hsz : Int { get set }   /* Header size in bytes. this is the size of */
  /* the smallest header this format supports. */
  /* Headers are assumed to fit in a BLKMULT. */
  /* If they are bigger, get_head() and */
  /* get_arc() must be adjusted */
  var udev : UInt { get set }   /* does append require unique dev/ino? some */
  /* formats use the device and inode fields */
  /* to specify hard links. when members in */
  /* the archive have the same inode/dev they */
  /* are assumed to be hard links. During */
  /* append we may have to generate unique ids */
  /* to avoid creating incorrect hard links */
  var hlk : Bool { get set }    /* does archive store hard links info? if */
  /* not, we do not bother to look for them */
  /* during archive write operations */
  var blkalgn : Bool { get set }    /* writes must be aligned to blkalgn boundary */
  var inhead : Bool { get set }    /* is the trailer encoded in a valid header? */
  /* if not, trailers are assumed to be found */
  /* in invalid headers (i.e like tar) */

  func id(_ : [UInt8]) -> Result  /* checks if a buffer is a valid header */
  /* returns 1 if it is, o.w. returns a 0 */
  func st_rd() -> Result  /* initialize routine for read. so format */
  /* can set up tables etc before it starts */
  /* reading an archive */
  func rd(_ : [UInt8]) -> ARCHD?
  /* read header routine. passed a pointer to */
  /* ARCHD. It must extract the info from the */
  /* format and store it in the ARCHD struct. */
  /* This routine is expected to fill all the */
  /* fields in the ARCHD (including stat buf) */
  /* 0 is returned when a valid header is */
  /* found. -1 when not valid. This routine */
  /* set the skip and pad fields so the format */
  /* independent routines know the amount of */
  /* padding and the number of bytes of data */
  /* which follow the header. This info is */
  /* used skip to the next file header */
  func end_rd() -> Result  /* read cleanup. Allows format to clean up */
  /* and MUST RETURN THE LENGTH OF THE TRAILER */
  /* RECORD (so append knows how many bytes */
  /* to move back to rewrite the trailer) */
  func st_wr() -> Result  /* initialize routine for write operations */
  func wr(_ : ARCHD) -> Result  /* write archive header. Passed an ARCHD */
  /* filled with the specs on the next file to */
  /* archived. Returns a 1 if no file data is */
  /* is to be stored; 0 if file data is to be */
  /* added. A -1 is returned if a write */
  /* operation to the archive failed. this */
  /* function sets the skip and pad fields so */
  /* the proper padding can be added after */
  /* file data. This routine must NEVER write */
  /* a flawed archive header. */
  func end_wr() -> Result  /* end write. write the trailer and do any */
  /* other format specific functions needed */
  /* at the end of an archive write */
  func trail_cpio(_ : ARCHD) -> Result
  func trail_tar(_ : [UInt8], _ : Bool, _ : inout Int) -> Result
  /* returns 0 if a valid trailer, -1 if not */
  /* For formats which encode the trailer */
  /* outside of a valid header, a return value */
  /* of 1 indicates that the block passed to */
  /* it can never contain a valid header (skip */
  /* this block, no point in looking at it)  */
//  func rd_data(_ : ARCHD,_ : Int,_ : inout Int) -> Result
  /* read/process file data from the archive */
//  func wr_data(_ : ARCHD,_ : FileDescriptor, _ : inout Int) -> Result
  /* write/process file data to the archive */
  func other_options() -> Result  /* process format specific options (-o) */
  func doOptions(_ : inout pax.CommandOptions) throws(CmdErr)
}


extension FSUB {
  // Possibly promote to a superclass -- everybody seems to use this one
  /*
   * rd_wrfile()
   *  extract the contents of a file from the archive. If we are unable to
   *  extract the entire file (due to failure to write the file) we return
   *  the numbers of bytes we did NOT process. This way the caller knows how
   *  many bytes to skip past to find the next archive header. If the failure
   *  was due to an archive read, we will catch that when we try to skip. If
   *  the format supplies a file data crc value, we calculate the actual crc
   *  so that it can be compared to the value stored in the header
   * NOTE:
   *  We call a special function to write the file. This function attempts to
   *  restore file holes (blocks of zeros) into the file. When files are
   *  sparse this saves space, and is a LOT faster. For non sparse files
   *  the performance hit is small. As of this writing, no archive supports
   *  information on where the file holes are.
   * Return:
   *  0 ok, -1 if archive read failure. if we cannot write the entire file,
   *  we return a 0 but "left" is set to be the amount unwritten
   */

  func rd_data(_ arcn : ARCHD, _ ofd : FileDescriptor?, _ left : inout Int) -> Result {
    var size = arcn.sb.size;
    var res = 0;
    var fnm = arcn.name
    var isem = 1

    var sz = UInt(MINFBSZ)
    var crc = UInt(0)

    /*
     * pass the blocksize of the file being written to the write routine,
     * if the size is zero, use the default MINFBSZ
     */

    if ofd == nil {
      sz = UInt(PAXPATHLEN + 1)    /* GNU tar long link/file */
    } else if let sb = try? FileMetadata(for: ofd!) {
      if sb.blockSize > 0 {
        sz = sb.blockSize
      }
    } else {
      Tty.syswarn(false,errno,"Unable to obtain block size for file \(fnm)")
    }
    var rem = sz
    left = 0

    /*
     * Copy the archive to the file the number of bytes specified. We have
     * to assume that we want to recover file holes as none of the archive
     * formats can record the location of file holes.
     */
    while (size > 0) {
      var cnt = bufend - bufpt;
      /*
       * if we get a read error, we do not want to skip, as we may
       * miss a header, so we do not set left, but if we get a write
       * error, we do want to skip over the unprocessed data.
       */
      if ((cnt <= 0) && ((cnt = buf_fill()) <= 0)) {
        break;
      }
      cnt = MIN(cnt, size);
      if ((res = file_write(ofd,bufpt,cnt,&rem,&isem,sz,fnm)) <= 0) {
        *left = size;
        break;
      }

      if options.docrc {
        /*
         * update the actual crc value
         */
        cnt = res;
        while (--cnt >= 0) {
          crc += *bufpt++ & 0xff;
        }
      } else {
        bufpt += res;
      }
      size -= res;
    }

    /*
     * if the last block has a file hole (all zero), we must make sure this
     * gets updated in the file. We force the last block of zeros to be
     * written. just closing with the file offset moved forward may not put
     * a hole at the end of the file.
     */
    if (isem && (arcn.sb.size > 0)) {
      file_flush(ofd, fnm, isem);
    }

    /*
     * if we failed from archive read, we do not want to skip
     */
    if size > 0 && left == 0 {
      return .failed
    }

    /*
     * some formats record a crc on file data. If so, then we compare the
     * calculated crc to the crc stored in the archive
     */
    if options.docrc && size == 0 && arcn.crc != crc {
      Tty.paxwarn(true,"Actual crc does not match expected crc \(arcn.name)")
    }
    return .ok
  }


  /*
   * wr_rdfile()
   *  fill write buffer with the contents of a file. We are passed an open
   *  file descriptor to the file and the archive structure that describes the
   *  file we are storing. The variable "left" is modified to contain the
   *  number of bytes of the file we were NOT able to write to the archive.
   *  it is important that we always write EXACTLY the number of bytes that
   *  the format specific write routine told us to. The file can also get
   *  bigger, so reading to the end of file would create an improper archive,
   *  we just detect this case and warn the user. We never create a bad
   *  archive if we can avoid it. Of course trying to archive files that are
   *  active is asking for trouble. It we fail, we pass back how much we
   *  could NOT copy and let the caller deal with it.
   * Return:
   *  0 ok, -1 if archive write failure. a short read of the file returns a
   *  0, but "left" is set to be greater than zero.
   */

  func wr_data(_ arcn : ARCHD, _ ifd : FileDescriptor, _ left : inout UInt) -> Result {
    var res = 0
    var size = arcn.sb.size;

    /*
     * while there are more bytes to write
     */
    while size > 0 {
      var cnt = bufend - bufpt;
      if (cnt <= 0 && ((cnt = buf_flush(blksz)) < 0)) {
        *left = size;
        return .failed;
      }
      cnt = min(cnt, size)

      if ((res = read(ifd, bufpt, cnt)) <= 0) {
        break;
      }
      size -= res;
      bufpt += res;
    }

    /*
     * better check the file did not change during this operation
     * or the file read failed.
     */
    if (res < 0) {
      Tty.syswarn(true, errno, "Read fault on \(arcn.org_name)")
    }
    else if (size != 0) {
      Tty.paxwarn(true, "File changed size during read \(arcn.org_name)")
    }
    else if let sb = try? FileMetadata(for: ifd) {
      if (arcn.sb.lastModified != sb.lastModified) {
        Tty.paxwarn(true, "File \(arcn.org_name) was modified during copy to archive")
      }
      left = size
      return .ok
    } else {
      Tty.syswarn(true, errno, "Failed stat on \(arcn.org_name)")
    }
    return .ok
  }

  /*
   * str_offt()
   *  Convert an expression of the following forms to an off_t > 0.
   *   1) A positive decimal number.
   *  2) A positive decimal number followed by a b (mult by 512).
   *  3) A positive decimal number followed by a k (mult by 1024).
   *  4) A positive decimal number followed by a m (mult by 512).
   *  5) A positive decimal number followed by a w (mult by sizeof int)
   *  6) Two or more positive decimal numbers (with/without k,b or w).
   *     separated by x (also * for backwards compatibility), specifying
   *     the product of the indicated values.
   * Return:
   *  0 for an error, a positive value o.w.
   */

  func str_offt(_ val : String) -> UInt? {

    let e = val.prefix { $0.isWholeNumber }
    guard var num = UInt(e) else { return nil }

    var expr = val.dropFirst(e.count)
    if expr.isEmpty { return num }

    switch expr.first {
      case "b":
        num *= 512
        expr.removeFirst()
      case "k":
        num *= 1024
        expr.removeFirst()
      case "m":
        num *= 1048576
        expr.removeFirst()
      case "w":
        num *= UInt(MemoryLayout<Int32>.size)
        expr.removeFirst()
      default:
        break
    }

    if expr.isEmpty { return num }
    switch expr.first {
      case "*", "x":
        guard let n2 = str_offt(String(expr.dropFirst())) else {return nil }
        num *= n2
      default:
        return nil
    }
    return num
  }

  /*
   * ustar_strd()
   *  initialization for ustar read
   * Return:
   *  0 if ok, -1 otherwise
   */

  func st_rd() -> Result {
    return .ok
  }

  /*
   * ustar_stwr()
   *  initialization for ustar write
   * Return:
   *  0 if ok, -1 otherwise
   */

  func st_wr() -> Result {
    return .ok
  }

  /*
   * tar_endwr()
   *  add the tar trailer of two null blocks
   * Return:
   *  0 if ok, -1 otherwise (what wr_skip returns)
   */

  func end_wr() -> Result {
    return wr_skip(NULLCNT*BLKMULT)
  }

  /*
   * tar_endrd()
   *  no cleanup needed here, just return size of trailer (for append)
   * Return:
   *  size of trailer (2 * BLKMULT)
   */

  func end_rd() -> Result {
    return .count(NULLCNT*BLKMULT)
  }

  func trail_cpio(_: ARCHD) -> Result {
    fatalError("not used by tar")
  }

  /*
   * tar_trail()
   *  Called to determine if a header block is a valid trailer. We are passed
   *  the block, the in_sync flag (which tells us we are in resync mode;
   *  looking for a valid header), and cnt (which starts at zero) which is
   *  used to count the number of empty blocks we have seen so far.
   * Return:
   *  0 if a valid trailer, -1 if not a valid trailer, or 1 if the block
   *  could never contain a header.
   */

  func trail_tar(_ buf : [UInt8], _ in_resync : Bool, _ cnt : inout Int) -> Result {

    /*
     * look for all zero, trailer is two consecutive blocks of zero
     */
    if let i = (buf.firstIndex { $0 != 0 }) {
      /*
       * if not all zero it is not a trailer, but MIGHT be a header.
       */
      return .failed
    }

    /*
     * When given a zero block, we must be careful!
     * If we are not in resync mode, check for the trailer. Have to watch
     * out that we do not mis-identify file data as the trailer, so we do
     * NOT try to id a trailer during resync mode. During resync mode we
     * might as well throw this block out since a valid header can NEVER be
     * a block of all 0 (we must have a valid file name).
     */

    if !in_resync {
      cnt += 1
      if cnt >= NULLCNT {
        return .ok
      }
    }
    return .partial
  }


  /*
   * ul_oct()
   *  convert an unsigned long to an octal string. many oddball field
   *  termination characters are used by the various versions of tar in the
   *  different fields. term selects which kind to use. str is '0' padded
   *  at the front to len. we are unable to use only one format as many old
   *  tar readers are very cranky about this.
   * Return:
   *  0 if the number fit into the string, -1 otherwise
   */

  func ul_oct(_ val : UInt, _ len : Int, _ term : OctalTerminator) -> String? {
    /*
     * term selects the appropriate character(s) for the end of the string
     */
    var end =
    switch term {
      case ._3:
        "\0"
      case ._2:
        "\0 "
      case ._1:
        " "
      case ._0:
        " \0"
    }

    /*
     * convert and blank pad if there is space
     */
    var str = String(val, radix: 8) + end

    if str.count > len { return nil }
    str = String(repeating: "0", count: len - str.count) + str
    return str
  }

  // ==============================================================================================
  // these two functions were in both tar and paxer -- promoted to FSUB
  // ==============================================================================================
  func expandname(_ buf : [UInt8], gnu_name: inout String?, _ name : String) -> UInt {
    if let gnu_name {
      let buf = gnu_name
      if ((nlen = strlcpy(buf, *gnu_name, len)) >= len) {
        nlen = len - 1;
      }
      free(*gnu_name);
      *gnu_name = NULL;
    } else {
      if (name_len < len) {
        /* name may not be null terminated: it might be as big as the
         field,  so copy is limited to the max size of the header field */
        let buf = name
        if ((nlen = strlcpy(buf, name, name_len+1)) >= name_len+1) {
          nlen = name_len;
        }
      } else {
        if ((nlen = strlcpy(buf, name, len)) >= len) {
          nlen = len - 1;
        }
      }
    }
    return(nlen);
  }

  /*
   * name_split()
   *  see if the name has to be split for storage in a ustar header. We try
   *  to fit the entire name in the name field without splitting if we can.
   *  The split point is always at a /
   * Return
   *  character pointer to split point (always the / that is to be removed
   *  if the split is not needed, the points is set to the start of the file
   *  name (it would violate the spec to split there). A NULL is returned if
   *  the file name is too long
   */

  func name_split(_ name : String, _ len : Int) -> String? {
    char *start;

    /*
     * check to see if the file name is small enough to fit in the name
     * field. if so just return a pointer to the name.
     */
    if (len <= TNMSZ) {
      return(name);
    }

    /*
     * The strings can fill the complete name and prefix fields
     * without a NUL terminator.
     */
    if (len > (TPFSZ + TNMSZ + 1)) {

      return nil
    }

    /*
     * we start looking at the biggest sized piece that fits in the name
     * field. We walk forward looking for a slash to split at. The idea is
     * to find the biggest piece to fit in the name field (or the smallest
     * prefix we can find)
     */

    /*
     * the -1 is correct the biggest piece would
     * include the slash between the two parts that gets thrown away
     */
    start = name + len - TNMSZ - 1;
    if ((*start == "/") && (start == name)) {
      ++start;  /* 101 byte paths with leading "/" are dinged otherwise */
    }

    while ((*start != "\0") && (*start != "/")) {
      ++start;
    }

    /*
     * if we hit the end of the string, this name cannot be split, so we
     * cannot store this file.
     */
    if (*start == "\0") {
      return nil
    }
    len = start - name;

    /*
     * NOTE: /str where the length of str == TNMSZ can not be stored under
     * the p1003.1-1990 spec for ustar. We could force a prefix of / and
     * the file would then expand on extract to //str. The len == 0 below
     * makes this special case follow the spec to the letter.
     */
    if ((len > TPFSZ) || (len == 0)) {
      return nil
    }

    /*
     * ok have a split point, return it to the caller
     */
    return start
  }


}
