// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin
import VIS

struct Gen {

  /*
   * a collection of general purpose subroutines used by pax
   */


  static let NAME_WIDTH = 8


  /*
   * ls_list()
   *	list the members of an archive in ls format
   */

  static func ls_list(_ arcn : ARCHD, _ now : DateTime, _ fp : inout FileDescriptor) {
/*    struct stat *sbp;
    char f_mode[MODELEN];
    char f_date[DATELEN];
    const char *timefrmt;
*/

    let term = zeroflag ? "\0" : "\n"  /* path termination character */

    /*
     * if not verbose, just print the file name
     */
    if vflag == 0 {
      if (zeroflag) {
        print(arcn.name, terminator: term, to: &fp)
      }
      else {
        safe_print(arcn.name, terminator: term, to: &fp)
      }
      return
    }

    if pax_list_opt_format {
      pax_format_list_output(arcn, now, fp, term);
      return;
    }

    /*
     * user wants long mode
     */
    let sbp = arcn.sb
    let fmode = strmode(sbp.filetype, sbp.permissions)

    /*
     * time format based on age compared to the time pax was started.
     */
    let timefrmt : String
    if (sbp.lastModified + SIXMONTHS) <= now || sbp.lastModified > now {
      timefrmt = d_first ? OLDFRMTD : OLDFRMTM
    }
    else {
      timefrmt = d_first ? CURFRMTD : CURFRMTM
    }

    /*
     * print file mode, link count, uid, gid and time
     */
    if (strftime(f_date,DATELEN,timefrmt,localtime(&(sbp.lastModified))) == 0) {
      f_date[0] = '\0';
    }

    let UT_NAMESIZE = 8
    print( "%s%2u %-*.*s %-*.*s ", f_mode, sbp.links,
                  NAME_WIDTH, UT_NAMESIZE, name_uid(sbp.userId, 1),
           NAME_WIDTH, UT_NAMESIZE, name_gid(sbp.groupId, 1), to: &fp);

    /*
     * print device id's for devices, or sizes for other nodes
     */
    if arcn.type == .CHR || arcn.type == .BLK {
      print( "%4lu,%4lu ", MAJOR(sbp.rawDevice), MINOR(sbp.rawDevice), to: &fp);
    }
    else {

      /*
       * UNIX compliance fix: printing filename length for soft links
       * from arcn.ln_nlen instead of sbp->st_size, which is 0.
       */
      var nlen : Int
      if arcn.type == .SLK {
        nlen = arcn.ln_name.count
      } else {
        nlen = Int(sbp.size)
      }
      print( cFormat("%9ju", nlen), terminator: " ", to: &fp)
    }

    /*
     * print name and link info for hard and soft links
     */

    print(f_date, terminator: " ", to: &fp)
    safe_print(arcn.name, fp)
    if arcn.type == .HLK || arcn.type == .HRG {
      print(" == ", terminator: "", to: &fp)
      safe_print(arcn.ln_name, fp)
    } else if arcn.type == .SLK {
      print(" -> ", terminator: "", to: &fp)
      safe_print(arcn.ln_name, fp);
    }
    (void)putc(term, fp);

    (void)fflush(fp);
    return;
  }

  /*
   * l_strncpy()
   *	copy src to dest up to len chars (stopping at first '\0').
   *	when src is shorter than len, pads to len with '\0'.
   * Return:
   *	number of chars copied. (Note this is a real performance win over
   *	doing a strncpy(), a strlen(), and then a possible memset())
   */

  /*
  int
  l_strncpy(char *dest, const char *src, int len)
  {
    char *stop;
    char *start;

    stop = dest + len;
    start = dest;
    while ((dest < stop) && (*src != '\0')) {
      *dest++ = *src++;
    }
    len = dest - start;
    while (dest < stop) {
      *dest++ = '\0';
    }
    return(len);
  }
*/

  static func safe_print(_ str : String, terminator term: String, to fp : inout FileDescriptor) {
    /*
     * if printing to a tty, use strvis(3) to print special characters.
     */
    if 0 != isatty(fp.rawValue) {
      /*
       * The size of visbuf must be four times the number
       * of bytes encoded from str (plus one for the NUL).
       */
      let visbuflen = 4 * str.utf8.count + 1

      let visbuf = withUnsafeTemporaryAllocation(byteCount: visbuflen, alignment: 8) { visbuf in
        /*
         * using strvis(3) instead of vis(3) to account for multibyte
         * characters
         */
        strnvis(visbuf.baseAddress!, visbuf.count, str, VIS_CSTYLE)
        return String(decoding: visbuf, as: UTF8.self)
      }
      print(visbuf, terminator: term, to: &fp)
    } else {
      print(str, terminator: term, to: &fp)
    }
  }

  static let asc_ul = asc_uqd

  /*
   * asc_uqd()
   *	convert hex/octal character string into a u_quad_t. We do not have to
   *	check for overflow! (the headers in all supported formats are not large
   *	enough to create an overflow).
   *	NOTE: strings passed to us are NOT TERMINATED.
   * Return:
   *	u_quad_t value
   */

  static func asc_uqd(_ str : String, _ base : Int) -> UInt? {
    let x = UInt(str, radix: base)
    return x
  }

  static let ul_asc = uqd_asc

  /*
   * uqd_asc()
   *	convert an u_quad_t into a hex/oct ascii string. pads with LEADING
   *	ascii 0's to fill string completely
   *	NOTE: the string created is NOT TERMINATED.
   */

  static func uqd_asc(_ val : UInt, _ len : Int, _ base : Int) -> String {
    let a = String(val, radix: base)
    let b = String(repeating: "0", count: len - a.count) + a
    /*
     * WARNING str is not '\0' terminated by this routine
     */
    return b
  }

  func pax_format_list_output(_ arcn : ARCHD, _ now : DateTime, _ fp : FileDescriptor, _ term : Character) {
    /* parse specified listopt format */
 /*   char *nextpercent, *nextchar;
    char buf[4*1024];
    int pos, cpylen;
    char *fname;
*/

    guard let pax_list_opt_format, var nextpercent = pax_list_opt_format.firstIndex(of: "%") else {
      /* Strange case: no specifiers? */
      safe_print(pax_list_opt_format, fp)
      putc(term, fp);
      flush(fp);
      return
    }
//    pos = nextpercent-pax_list_opt_format;
    var buf = pax_list_opt_format[pax_list_opt_format.startIndex..<nextpercent]
    while true {
      nextpercent = pax_list_opt_format.index(after: nextpercent)
      switch pax_list_opt_format[nextpercent] {
        case "F":
          buf += arcn.name
        case "D", "T", "M", "L":
          fallthrough
        default:
          Tty.paxwarn(true, "Unimplemented listopt format: \(pax_list_opt_format[nextpercent])")
      }
      nextpercent++;
      if (*nextpercent=='\0') {
        break;
      }
      nextchar = nextpercent;
      nextpercent = strchr(nextpercent,"%");
      if (nextpercent==NULL) {
        cpylen = strlen(nextchar);
      } else {
        cpylen = nextpercent - nextchar;
      }
      memcpy(&buf[pos],nextchar, cpylen);
      pos += cpylen;
    }
    safe_print(&buf[0], fp);
    (void)putc(term, fp);
    (void)fflush(fp);
    return;
  }
}
