// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *  The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration

let  MAXBLK = 64512  /* MAX blocksize supported (posix SPEC) */
        /* WARNING: increasing MAXBLK past 32256 */
        /* will violate posix spec. */
let MAXBLK_POSIX = 32256  /* MAX blocksize supported as per POSIX */
let BLKMULT = 512  /* blocksize must be even mult of 512 bytes */
        /* Don't even think of changing this */
let DEVBLK = 8192  /* default read blksize for devices */
let PAXPATHLEN = 3072  /* maximum path length for pax. MUST be */
        /* longer than the system PATH_MAX */

let MINFBSZ = 512    /* default block size for hole detect */
let MAXFLT = 10    /* default media read error limit */
let NULLCNT = 2    /* number of null blocks in trailer */

let GZIP_CMD = "gzip"    /* command to run as gzip */
let COMPRESS_CMD = "compress"  /* command to run as compress */
let BZIP2_CMD = "bzip2"    /* command to run as bzip2 */


let NM_TAR = "tar"
let NM_CPIO = "cpio"
let NM_PAX = "pax"

let NONE = "none"

let TNMSZ = 100    /* size of name field */
let TPFSZ =  155

typealias C6 = (CChar, CChar, CChar, CChar, CChar, CChar)
typealias C8 = (CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar)
typealias C11 = (CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar)
typealias C12 = (UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8 )
typealias C32 = (
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8
)

typealias C100 = (
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8
)

typealias C155 = (
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8,
  UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8
)

enum TarFileType : Character {
  case REGTYPE =    "0"    /* Regular File */
  case AREGTYPE =  "\0"    /* Regular File */
  case LNKTYPE =    "1"    /* Link */
  case SYMTYPE =    "2"    /* Symlink */
  case CHRTYPE =    "3"    /* Character Special File */
  case BLKTYPE =    "4"    /* Block Special File */
  case DIRTYPE =    "5"    /* Directory */
  case FIFOTYPE =  "6"    /* FIFO */
  case CONTTYPE =  "7"    /* high perf file */

  case PAXXTYPE =  "x"    /* pax format extended header */
  case PAXGTYPE =  "g"    /* pax format global extended header */

  /*
   * GNU tar compatibility;
   */
  case LONGLINKTYPE =  "K"    /* Long Symlink */
  case LONGNAMETYPE =  "L"    /* Long File */
}

struct HD_USTAR {
  var name : C100    /* name of entry */
  var mode : C8       /* mode */
  var uid : C8       /* uid */
  var gid : C8      /* gid */
  var size : C12      /* size */
  var mtime : C12      /* modification time */
  var chksum : C8    /* checksum */
  var typeflag : UInt8     /* type of file. */
  var linkname : C100      /* linked to name */
  var magic : C6           /* magic cookie */
  var version : (UInt8, UInt8)  /* version */
  var uname : C32      /* ascii owner name */
  var gname : C32      /* ascii group name */
  var devmajor : C8    /* major device number */
  var devminor : C8    /* minor device number */
  var prefix : C155    /* linked to name */

  init() {
    let a = UnsafeMutablePointer<HD_USTAR>.allocate(capacity: 1)
    self = a.pointee
  }
}

enum OctalTerminator : Int {
  case _0, _1, _2, _3
}


// FIXME: put me back
// nonisolated(unsafe) let ar_io = Ar_io()
nonisolated(unsafe) let cache = Cache()
nonisolated(unsafe) let tty = Tty()

nonisolated(unsafe) var pax_invalid_action = false
nonisolated(unsafe) var exit_val : Int32 = 0   /* exit value */
nonisolated(unsafe) var vflag : Int = 0  /* produce verbose output */
nonisolated(unsafe) var vfpart = false      /* is partial verbose output in progress */
nonisolated(unsafe) var cwdfd : FileDescriptor? = nil      /* starting cwd */
nonisolated(unsafe) let tables = Tables.shared
nonisolated(unsafe) var listf = FileDescriptor.standardError       /* file pointer to print file list to */
nonisolated(unsafe) var programName : String = "pax"
nonisolated(unsafe) var chdname : String?


