// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin

struct PaxPatFlags : OptionSet {
  init(rawValue: UInt) {
    self.rawValue = rawValue
  }
  
  var rawValue = UInt(0)

  static let PRNT = Self.init(rawValue: 0x1)
  static let GLOB = Self.init(rawValue: 0x2)
}
/*
 * data structure for storing user supplied replacement strings (-s)
 */
struct REPLACE {
  var nstr : String  /* the new string we will substitute with */
  var rcmp : Regex<AnyRegexOutput>?   /* compiled regular expression used to match */
  var flgs : PaxPatFlags  /* print conversions? global in operation?  */
}

class paxPattern {

  /*
   * routines to handle pattern matching, name modification (regular expression
   * substitution and interactive renames), and destination name modification for
   * copy (-rw). Both file name and link names are adjusted as required in these
   * routines.
   */

  let MAXSUBEXP	= 10		/* max subexpressions, DO NOT CHANGE */
  var pathead : [PATTERN] = []		/* file pattern match list head */
  var rephead : [REPLACE] = []		/* replacement string list head */


  /*
   * rep_add()
   *	parses the -s replacement string; compiles the regular expression
   *	and stores the compiled value and it's replacement string together in
   *	replacement string list. Input to this function is of the form:
   *		/old/new/pg
   *	The first char in the string specifies the delimiter used by this
   *	replacement string. "Old" is a regular expression in "ed" format which
   *	is compiled by regcomp() and is applied to filenames. "new" is the
   *	substitution string; p and g are options flags for printing and global
   *	replacement (over the single filename)
   * Return:
   *	0 if a proper replacement string and regular expression was added to
   *	the list of replacement patterns; -1 otherwise.
   */

  func rep_add(_ str : String) -> Result {
/*    char *pt1;
    char *pt2;
    REPLACE *rep;
    int res;
    char rebuf[BUFSIZ];
*/

    // throw out the bad parameters
    if str.isEmpty {
      Tty.paxwarn(true, "Empty replacement string")
      return .failed
    }

    // first character in the string specifies what the delimiter is for this expression
    var pt1 = str.dropFirst()
    var pt3 = Substring("")
    while !pt1.isEmpty {
      let c = pt1.removeFirst()
      if c == "\\" {
        pt3.append(c)
        pt3.append(pt1.removeFirst())
        continue
      }
      if c == str.first {
        break
      }
      pt3.append(c)
    }
    if pt1.isEmpty {
      Tty.paxwarn(true, "Invalid replacement string \(str)")
      return .failed
    }

    var rcmp : Regex<AnyRegexOutput>

    do {
      rcmp = try Regex(String(pt3))  // variant for using regcomp ?
    } catch(let e) {
//      regerror(res, &(rep->rcmp), rebuf, sizeof(rebuf));
      Tty.paxwarn(true, "\(e) while compiling regular expression \(str)")
      return .failed;
    }

    /*
     * put the delimiter back in case we need an error message and
     * locate the delimiter at the end of the replacement string
     * we then point the node at the new substitution string
     */

    var pt2 = pt1
    var pt4 = Substring("")

    while !pt2.isEmpty {
      let c = pt2.removeFirst()
      if c == "\\" {
        pt4.append(c)
        pt4.append(pt2.removeFirst())
        continue
      }
      if c == str.first {
        break
      }
    }
    if pt2.isEmpty {
      Tty.paxwarn(true, "Invalid replacement string \(str)")
      return .failed;
    }

    var nstr = pt4
    var rflgs : PaxPatFlags = []
    /*
     * set the options if any
     */
    while !pt2.isEmpty {
      switch pt2.removeFirst() {
        case "g", "G":
          rflgs.insert(.GLOB)
        case "p", "P":
          rflgs.insert(.PRNT)
        default:
          Tty.paxwarn(true, "Invalid replacement string option \(str)")
          return .failed;
      }
    }

    /*
     * all done, link it in at the end
     */
    let rep = REPLACE.init(nstr: String(nstr), rcmp: rcmp, flgs: rflgs)
    rephead.append(rep)
    return .ok
  }

  /*
   * pat_add()
   *	add a pattern match to the pattern match list. Pattern matches are used
   *	to select which archive members are extracted. (They appear as
   *	arguments to pax in the list and read modes). If no patterns are
   *	supplied to pax, all members in the archive will be selected (and the
   *	pattern match list is empty).
   * Return:
   *	0 if the pattern was added to the list, -1 otherwise
   */

  func pat_add(_ str : String, _ chdnam : String ) -> Result {

    /*
     * throw out the junk
     */
    if str.isEmpty {
      Tty.paxwarn(true, "Empty pattern string")
      return .failed
    }

    let pt = PATTERN.init(pstr: str, chdname: chdnam, flgs: [])
    pathead.append(pt)
    return .ok
  }

  /*
   * pat_chk()
   *	complain if any the user supplied pattern did not result in a match to
   *	a selected archive member.
   */

  func pat_chk() {
    var warned = false
    var se = FileDescriptor.standardError

    /*
     * walk down the list checking the flags to make sure MTCH was set,
     * if not complain
     */
    for pt in pathead {
      if pt.flgs.contains(.MTCH) {
        continue
      }
      if !warned {
        Tty.paxwarn(true, "WARNING! These patterns were not matched:");
        warned = true
      }

      print(pt.pstr, to: &se)
    }
  }

  /*
   * pat_sel()
   *	the archive member which matches a pattern was selected. Mark the
   *	pattern as having selected an archive member. arcn.pat points at the
   *	pattern that was matched. arcn.pat is set in pat_match()
   *
   *	NOTE: When the -c option is used, we are called when there was no match
   *	by pat_match() (that means we did match before the inverted sense of
   *	the logic). Now this seems really strange at first, but with -c  we
   *	need to keep track of those patterns that cause an archive member to NOT
   *	be selected (it found an archive member with a specified pattern)
   * Return:
   *	0 if the pattern pointed at by arcn.pat was tagged as creating a
   *	match, -1 otherwise.
   */

  func pat_sel(_ arcn : ARCHD) -> Result {
    PATTERN *pt;
    PATTERN **ppt;
    int len;

    /*
     * if no patterns just return
     */
    if ((pathead == NULL) || ((pt = arcn.pat) == NULL)) {
      return(0);
    }

    /*
     * when we are NOT limited to a single match per pattern mark the
     * pattern and return
     */
    if (!nflag) {
      pt->flgs |= MTCH;
      return(0);
    }

    /*
     * we reach this point only when we allow a single selected match per
     * pattern, if the pattern matches a directory and we do not have -d
     * (dflag) we are done with this pattern. We may also be handed a file
     * in the subtree of a directory. in that case when we are operating
     * with -d, this pattern was already selected and we are done
     */
    if (pt->flgs & DIR_MTCH) {
      return(0);
    }

    if (!dflag && ((pt->pend != NULL) || (arcn.type == PAX_DIR))) {
      /*
       * ok we matched a directory and we are allowing
       * subtree matches but because of the -n only its children will
       * match. This is tagged as a DIR_MTCH type.
       * WATCH IT, the code assumes that pt->pend points
       * into arcn.name and arcn.name has not been modified.
       * If not we will have a big mess. Yup this is another kludge
       */

      /*
       * if this was a prefix match, remove trailing part of path
       * so we can copy it. Future matches will be exact prefix match
       */
      if (pt->pend != NULL) {
        *pt->pend = '\0';
      }

      if ((pt->pstr = strdup(arcn.name)) == NULL) {
        Tty.paxwarn(true, "Pattern select out of memory");
        if (pt->pend != NULL) {
          *pt->pend = '/';
        }
        pt->pend = NULL;
        return .failed;
      }

      /*
       * put the trailing / back in the source string
       */
      if (pt->pend != NULL) {
        *pt->pend = '/';
        pt->pend = NULL;
      }
      pt->plen = strlen(pt->pstr);

      /*
       * strip off any trailing /, this should really never happen
       */
      len = pt->plen - 1;
      if (*(pt->pstr + len) == '/') {
        *(pt->pstr + len) = '\0';
        pt->plen = len;
      }
      pt->flgs = DIR_MTCH | MTCH;
      arcn.pat = pt;
      return(0);
    }

    /*
     * we are then done with this pattern, so we delete it from the list
     * because it can never be used for another match.
     * Seems kind of strange to do for a -c, but the pax spec is really
     * vague on the interaction of -c -n and -d. We assume that when -c
     * and the pattern rejects a member (i.e. it matched it) it is done.
     * In effect we place the order of the flags as having -c last.
     */
    pt = pathead;
    ppt = &pathead;
    while ((pt != NULL) && (pt != arcn.pat)) {
      ppt = &(pt->fow);
      pt = pt->fow;
    }

    if (pt == NULL) {
      /*
       * should never happen....
       */
      Tty.paxwarn(true, "Pattern list inconsistent");
      return .failed;
    }
    *ppt = pt->fow;
    free(pt);
    arcn.pat = NULL;
    return(0);
  }

  /*
   * pat_match()
   *	see if this archive member matches any supplied pattern, if a match
   *	is found, arcn.pat is set to point at the potential pattern. Later if
   *	this archive member is "selected" we process and mark the pattern as
   *	one which matched a selected archive member (see pat_sel())
   * Return:
   *	0 if this archive member should be processed, 1 if it should be
   *	skipped and -1 if we are done with all patterns (and pax should quit
   *	looking for more members)
   */

  func pat_match(_ arcn : ARCHD) -> Result {
    PATTERN *pt;

    arcn.pat = NULL;

    /*
     * if there are no more patterns and we have -n (and not -c) we are
     * done. otherwise with no patterns to match, matches all
     */
    if (pathead == NULL) {
      if (nflag && !cflag) {
        return .failed;
      }
      return(0);
    }

    /*
     * have to search down the list one at a time looking for a match.
     */
    pt = pathead;
    while (pt != NULL) {
      /*
       * check for a file name match unless we have DIR_MTCH set in
       * this pattern then we want a prefix match
       */
      if (pt->flgs & DIR_MTCH) {
        /*
         * this pattern was matched before to a directory
         * as we must have -n set for this (but not -d). We can
         * only match CHILDREN of that directory so we must use
         * an exact prefix match (no wildcards).
         */
        if ((arcn.name[pt->plen] == '/') &&
            (strncmp(pt->pstr, arcn.name, pt->plen) == 0)) {
          break;
        }
      } else if (fn_match(pt->pstr, arcn.name, &pt->pend) == 0) {
        break;
      }
      pt = pt->fow;
    }

    /*
     * return the result, remember that cflag (-c) inverts the sense of a
     * match
     */
    if (pt == NULL) {
      return(cflag ? 0 : 1);
    }

    /*
     * We had a match, now when we invert the sense (-c) we reject this
     * member. However we have to tag the pattern a being successful, (in a
     * match, not in selecting an archive member) so we call pat_sel() here.
     */
    arcn.pat = pt;
    if (!cflag) {
      return(0);
    }

    if (pat_sel(arcn) < 0) {
      return .failed;
    }
    arcn.pat = NULL;
    return(1);
  }

  /*
   * fn_match()
   * Return:
   *	0 if this archive member should be processed, 1 if it should be
   *	skipped and -1 if we are done with all patterns (and pax should quit
   *	looking for more members)
   *	Note: *pend may be changed to show where the prefix ends.
   */

  func fn_match(_ pattern : String, _ string: String, _ pend : inout String) -> Result {
    char c;
    char test;

    char *equiv_pat;
    char *pat_pend = NULL;

    *pend = NULL;
    for (;;) {
      switch (c = *pattern++) {
        case '\0':
          /*
           * Ok we found an exact match
           */
          if (*string == '\0') {
            return(0);
          }

          /*
           * Check if it is a prefix match
           */
          if ((dflag == 1) || (*string != '/')) {
            return .failed;
          }

          /*
           * It is a prefix match, remember where the trailing
           * / is located
           */
          *pend = string;
          return(0);
        case '?':
          if ((test = *string++) == '\0') {
            return (-1);
          }
          break;
        case '*':
          c = *pattern;
          /*
           * Collapse multiple *'s.
           */
          while (c == '*') {
            c = *++pattern;
          }

          /*
           * Optimized hack for pattern with a * at the end
           */
          if (c == '\0') {
            return (0);
          }

          /*
           * General case, use recursion.
           */
          while ((test = *string) != '\0') {
            if (!fn_match(pattern, string, pend)) {
              return (0);
            }
            ++string;
          }
          return (-1);
        case '[':
                  /*
                   * range match
                   */

                /*
                 * Check for equivalence class and use regex_match to
                 * handle this case. Note pattern should include the
                 * opening bracket '['
                 */
                equiv_pat = extract_equiv_pat(pattern-1, &pat_pend);
                if (equiv_pat) {
          if (regex_match(equiv_pat, string, &string) == -1) {
            free (equiv_pat);
            return (-1);
          }

          free(equiv_pat);

          /*
           * Update the pattern string
           */
          pattern = pat_pend;
          break;
        }

                if (((test = *string++) == '\0') ||
                    ((pattern = range_match(pattern, test)) == NULL)) {
          return (-1);
        }
                break;
                case '\\':
                  default:
                  if (c != *string++) {
          return (-1);
        }
                break;
      }
    }
    /* NOTREACHED */
  }

  func extract_equiv_pat(_ patterh : String, _ pend : inout String) -> String {
    int pat_len = 2;
    int found = 0;
    int is_double_bracket = 0;
    char* equiv_pat = NULL;

    if (*pattern == '\0' || pattern[1] == '\0' || pattern[2] == '\0')
        return NULL;

    /*
     * check if the pattern is
     * "[= =]", "[[= =][= =]]", "[: :]", or "[[: :][: :]]"
     * note that the full "pattern" string needs to be passed in
     */
    is_double_bracket = (*pattern == '[' && pattern[1] == '[');
    if (!(*pattern == '[') && !is_double_bracket) {
      return NULL;
    }

    pattern ++;

    if (is_double_bracket) {
      pattern ++;
      pat_len ++;
    }

    if (!(*pattern == ':') && !(*pattern == '=')) {
      return NULL;
    }

    pattern ++;


    for(; *pattern != '\0'; pat_len++, pattern++) {
      if (!is_double_bracket) {
        if ((*pattern == '=' || *pattern == ':')
            && pattern[1] == ']') {
          found = 1;
          pattern += 2;
          pat_len += 2;
          break;
        }

      } else {
        if ((*pattern == '=' || *pattern == ':')
            && pattern[1] == ']' && pattern[2] == ']') {
          found = 1;
          pattern += 3;
          pat_len += 3;
          break;
        }

      }
    }

    if (!found) {
      return NULL;
    }

    equiv_pat = strndup(pattern-pat_len, pat_len);

    if (equiv_pat == NULL) {
      Tty.paxwarn(true, "Out of memory");
      return NULL;
    }

    /*
     * set pend to the remaining pattern to be matched
     */
    if (pend != NULL) {
      *pend = pattern;
    }

    return equiv_pat;
  }

  func regex_match(_ pattern : String, _ string : String, _ pend : inout String) -> Result {
    int res;
    regex_t preg;
    regmatch_t pmatch;
    char rebuf[BUFSIZ];

    if ((res = regcomp(&(preg), pattern, REG_EXTENDED)) != 0) {
      regerror(res, &(preg), rebuf, sizeof(rebuf));
      Tty.paxwarn(true, "%s while compiling pattern %s", rebuf, pattern);
      return .failed;
    }

    if (regexec(&(preg), string, 1, &(pmatch), 0) != 0) {
      regfree(&(preg));
      return .failed;
    }

    regfree(&(preg));

    /*
     * starting position of the match must be 0
     */
    if (pmatch.rm_so != 0) {
      return .failed;
    }

    /*
     * set pend to the remaining string to be matched
     */
    if (pend != NULL) {
      *pend = string + pmatch.rm_eo;
    }

    return(0);
  }

  func range_match(_ pattern : String, _ test : Int) -> String {
    char c;
    char c2;
    int negate;
    int ok = 0;

    if ((negate = (*pattern == '!')) != 0)
        ++pattern;

    while ((c = *pattern++) != ']') {
      /*
       * Illegal pattern
       */
      if (c == '\0')
          return (NULL);

      if ((*pattern == '-') && ((c2 = pattern[1]) != '\0') &&
          (c2 != ']')) {
        if ((c <= test) && (test <= c2))
            ok = 1;
        pattern += 2;
      } else if (c == test)
                  ok = 1;
    }
    return (ok == negate ? NULL : pattern);
  }

}
