// Generated by Robert M. Lefkowitz <r0ml@liberally.net> in 2025 using ChatGPT
// from a file containing the following notice:

/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1992 Keith Muller.
 * Copyright (c) 1992, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Keith Muller of the University of California, San Diego.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

import CMigration
import Darwin

class Tables {

  /*
   * Routines for controlling the contents of all the different databases pax
   * keeps. Tables are dynamically created only when they are needed. The
   * goal was speed and the ability to work with HUGE archives. The databases
   * were kept simple, but do have complex rules for when the contents change.
   * As of this writing, the POSIX library functions were more complex than
   * needed for this application (pax databases have very short lifetimes and
   * do not survive after pax is finished). Pax is required to handle very
   * large archives. These database routines carefully combine memory usage and
   * temporary file storage in ways which will not significantly impact runtime
   * performance while allowing the largest possible archives to be handled.
   * Trying to force the fit to the POSIX database routines was not considered
   * time well spent.
   */


  /*
   * data structures and constants used by the different databases kept by pax
   */

  /*
   * Hash Table Sizes MUST BE PRIME, if set too small performance suffers.
   * Probably safe to expect 500000 inodes per tape. Assuming good key
   * distribution (inodes) chains of under 50 long (worse case) is ok.
   */
  let L_TAB_SZ = 2503    /* hard link hash table size */
  let F_TAB_SZ = 50503    /* file time hash table size */
  let N_TAB_SZ = 541    /* interactive rename hash table */
  let D_TAB_SZ = 317    /* unique device mapping table */
  let A_TAB_SZ = 317    /* ftree dir access time reset table */
  let MAXKEYLEN = 64    /* max number of chars for hash */

  let DIRP_SIZE = 64    /* initial size of created dir table */

  let _TFILE_BASE = "paxXXXXXXXXXX"

  /*
   * file hard link structure (hashed by dev/ino and chained) used to find the
   * hard links in a file system or with some archive formats (cpio)
   */
  struct HRDLNK {
    var name : String  /* name of first file seen with this ino/dev */
    var dev : UInt    /* files device number */
    var ino : UInt    /* files inode number */
    var nlink : UInt   /* expected link count */
    // fow -> ptr to next HRDLNK
  }

  /*
   * Archive write update file time table (the -u, -C flag), hashed by filename.
   * Filenames are stored in a scratch file at seek offset into the file. The
   * file time (mod time) and the file name length (for a quick check) are
   * stored in a hash table node. We were forced to use a scratch file because
   * with -u, the mtime for every node in the archive must always be available
   * to compare against (and this data can get REALLY large with big archives).
   * By being careful to read only when we have a good chance of a match, the
   * performance loss is not measurable (and the size of the archive we can
   * handle is greatly increased).
   */
  struct FTM {
    //    var namelen : Int   /* file name length */
    var mtime : DateTime  /* files last modification time */
    //    var seek : off_t    /* location in scratch file */
    // fow -> ptr to next FTM
  }

  /*
   * Interactive rename table (-i flag), hashed by orig filename.
   * We assume this will not be a large table as this mapping data can only be
   * obtained through interactive input by the user. Nobody is going to type in
   * changes for 500000 files? We use chaining to resolve collisions.
   */

  /*  struct NAMT {
   var oname : String    /* old name */
   var nname : String     /* new name typed in by the user */
   // fow -> ptr to next NAMT
   }
   */

  /*
   * Unique device mapping tables. Some protocols (e.g. cpio) require that the
   * <c_dev,c_ino> pair will uniquely identify a file in an archive unless they
   * are links to the same file. Appending to archives can break this. For those
   * protocols that have this requirement we map c_dev to a unique value not seen
   * in the archive when we append. We also try to handle inode truncation with
   * this table. (When the inode field in the archive header are too small, we
   * remap the dev on writes to remove accidental collisions).
   *
   * The list is hashed by device number using chain collision resolution. Off of
   * each DEVT are linked the various remaps for this device based on those bits
   * in the inode which were truncated. For example if we are just remapping to
   * avoid a device number during an update append, off the DEVT we would have
   * only a single DLIST that has a truncation id of 0 (no inode bits were
   * stripped for this device so far). When we spot inode truncation we create
   * a new mapping based on the set of bits in the inode which were stripped off.
   * so if the top four bits of the inode are stripped and they have a pattern of
   * 0110...... (where . are those bits not truncated) we would have a mapping
   * assigned for all inodes that has the same 0110.... pattern (with this dev
   * number of course). This keeps the mapping sparse and should be able to store
   * close to the limit of files which can be represented by the optimal
   * combination of dev and inode bits, and without creating a fouled up archive.
   * Note we also remap truncated devs in the same way (an exercise for the
   * dedicated reader; always wanted to say that...:)
   */

  struct DLIST {
    var trunc_bits : UInt   /* truncation pattern for a specific map */
    var dev : UInt          /* the new device id we use */
    // struct dlist *fow;
  }

  /*
   * ftree directory access time reset table. When we are done with with a
   * subtree we reset the access and mod time of the directory when the tflag is
   * set. Not really explicitly specified in the pax spec, but easy and fast to
   * do (and this may have even been intended in the spec, it is not clear).
   * table is hashed by inode with chaining.
   */

  struct ATDIR {
    var name : String  /* name of directory to reset */
    var dev : UInt     /* dev and inode for fast lookup */
    var ino : UInt
    var mtime : DateTime /* access and mod time to reset to */
    var atime : DateTime
  }

  struct DevInode : Hashable {
    var dev : UInt
    var ino : UInt
  }

  /*
   * created directory time and mode storage entry. After pax is finished during
   * extraction or copy, we must reset directory access modes and times that
   * may have been modified after creation (they no longer have the specified
   * times and/or modes). We must reset time in the reverse order of creation,
   * because entries are added  from the top of the file tree to the bottom.
   * We MUST reset times from leaf to root (it will not work the other
   * direction).  Entries are recorded into a spool file to make reverse
   * reading faster.
   */

  struct DIRDATA {

    var name : String  /* file name */

    var npos : off_t = 0 /* position in file where this dir name starts */
    var mode : FilePermissions /* file mode to restore */
    var mtime : DateTime       /* mtime to set */

    //    var mtime_nsec : time_t  /* mtime to set (nanoseconds component) */

    var atime : DateTime       /* atime to set */

    //    var atime_nsec : time_t  /* atime to set (nanoseconds component) */

    var frc_mode : Bool  /* do we force mode settings? */
  }





  var ltab : [UInt : HRDLNK] = [:] 	/* hard link table for detecting hard links */
  var ftab : [String : FTM] = [:]             /* file time table for updating arch */
  var ntab : [String : String] = [:]  /* interactive rename storage table */
  var dtab : [UInt : [DLIST] ] = [:]            /* device/inode mapping tables */
  var atab : [DevInode : ATDIR] = [:]           /* file tree directory time reset table */

  var dirp : [DIRDATA] = []      /* storage for setting created dir time/mode */
  //  var dirsize : Int         /* size of dirp table */

  //  var dircnt : UInt         /* entries in dir time/mode storage */
  var ffd : FileDescriptor? /* tmp file for file time table name storage */

  /*
   * hard link table routines
   *
   * The hard link table tries to detect hard links to files using the device and
   * inode values. We do this when writing an archive, so we can tell the format
   * write routine that this file is a hard link to another file. The format
   * write routine then can store this file in whatever way it wants (as a hard
   * link if the format supports that like tar, or ignore this info like cpio).
   * (Actually a field in the format driver table tells us if the format wants
   * hard link info. if not, we do not waste time looking for them). We also use
   * the same table when reading an archive. In that situation, this table is
   * used by the format read routine to detect hard links from stored dev and
   * inode numbers (like cpio). This will allow pax to create a link when one
   * can be detected by the archive format.
   */


  init() {}

  /*
   * lnk_start
   *	Creates the hard link table.
   * Return:
   *	0 if created, -1 if failure
   */

  /*
   func lnk_start() -> Bool {
   if (ltab != NULL) {
   return false
   }
   if ((ltab = (HRDLNK **)calloc(L_TAB_SZ, sizeof(HRDLNK *))) == NULL) {
   Tty.paxwarn(true, "Cannot allocate memory for hard link table");
   return .failed;
   }
   return(0);
   }
   */

  /*
   * chk_lnk()
   *	Looks up entry in hard link hash table. If found, it copies the name
   *	of the file it is linked to (we already saw that file) into ln_name.
   *	lnkcnt is decremented and if goes to 1 the node is deleted from the
   *	database. (We have seen all the links to this file). If not found,
   *	we add the file to the database if it has the potential for having
   *	hard links to other files we may process (it has a link count > 1)
   * Return:
   *	if found returns 1; if not found returns 0; -1 on error
   */

  func chk_lnk(_ arcn : inout ARCHD) {

    /*
     * ignore those nodes that cannot have hard links
     */
    if arcn.type == .DIR || arcn.sb.links <= 1 {
      return
    }

    /*
     * hash inode number and look for this file
     */
    if let pt = ltab[arcn.sb.inode] {
      /*
       * found a link. set the node type and copy in the
       * name of the file it is to link to. we need to
       * handle hardlinks to regular files differently than
       * other links.
       */
      arcn.ln_name = pt.name
      /* XXX truncate? */
      if arcn.type == .REG {
        arcn.type = .HRG
      } else {
        arcn.type = .HLK
      }

      /*
       * if we have found all the links to this file, remove
       * it from the database
       */
      ltab[arcn.sb.inode]?.nlink -= 1
      if ltab[arcn.sb.inode]!.nlink <= 1 {
        ltab[arcn.sb.inode] = nil
      }
    } else {

      /*
       * we never saw this file before. It has links so we add it to the
       * front of this hash chain
       */
      let pt = HRDLNK(name: arcn.name, dev: arcn.sb.device, ino: arcn.sb.inode, nlink: arcn.sb.links)
      ltab[arcn.sb.inode] = pt
    }
  }

  /*
   * purg_lnk
   *	remove reference for a file that we may have added to the data base as
   *	a potential source for hard links. We ended up not using the file, so
   *	we do not want to accidentally point another file at it later on.
   */

  func purg_lnk(_ arcn : ARCHD) {
    /*
     * do not bother to look if it could not be in the database
     */
    if arcn.sb.links <= 1 || arcn.type == .DIR || arcn.type == .HLK || arcn.type == .HRG {
      return
    }

    ltab[arcn.sb.inode] = nil
  }

  /*
   * lnk_end()
   *	Pull apart an existing link table so we can reuse it. We do this between
   *	read and write phases of append with update. (The format may have
   *	used the link table, and we need to start with a fresh table for the
   *	write phase).
   */

  func lnk_end() {
    ltab = [:]
  }

  /*
   * modification time table routines
   *
   * The modification time table keeps track of last modification times for all
   * files stored in an archive during a write phase when -u is set. We only
   * add a file to the archive if it is newer than a file with the same name
   * already stored on the archive (if there is no other file with the same
   * name on the archive it is added). This applies to writes and appends.
   * An append with an -u must read the archive and store the modification time
   * for every file on that archive before starting the write phase. It is clear
   * that this is one HUGE database. To save memory space, the actual file names
   * are stored in a scratch file and indexed by an in memory hash table. The
   * hash table is indexed by hashing the file path. The nodes in the table store
   * the length of the filename and the lseek offset within the scratch file
   * where the actual name is stored. Since there are never any deletions from
   * this table, fragmentation of the scratch file is never an issue. Lookups
   * seem to not exhibit any locality at all (files in the database are rarely
   * looked up more than once...). So caching is just a waste of memory. The
   * only limitation is the amount of scratch file space available to store the
   * path names.
   */


  /*
   * chk_ftime()
   *	looks up entry in file time hash table. If not found, the file is
   *	added to the hash table and the file named stored in the scratch file.
   *	If a file with the same name is found, the file times are compared and
   *	the most recent file time is retained. If the new file was younger (or
   *	was not in the database) the new file is selected for storage.
   * Return:
   *	0 if file should be added to the archive, 1 if it should be skipped,
   *	-1 on error

   * changed to assume that the table can be in memory because we have virtual memory
   */

  func chk_ftime(_ arcn : ARCHD) -> Int {
    /*    FTM *pt;
     int namelen;
     u_int indx;
     char ckname[PAXPATHLEN+1];
     */
    /*
     * hash the pathname and look up in table
     */
    if let pt = ftab[arcn.name] {

      /*
       * found the file, compare the times, save the newer
       */
      if (arcn.sb.lastWrite > pt.mtime) {
        /*
         * file is newer
         */
        ftab[arcn.name]?.mtime = arcn.sb.lastWrite
        return 0
      }
      /*
       * file is older
       */
      return 1
    }

    /*
     * not in table, add it
     */
    ftab[arcn.name] = FTM(mtime: arcn.sb.lastWrite)
    return 0
  }

  /*
   * Interactive rename table routines
   *
   * The interactive rename table keeps track of the new names that the user
   * assigns to files from tty input. Since this map is unique for each file
   * we must store it in case there is a reference to the file later in archive
   * (a link). Otherwise we will be unable to find the file we know was
   * extracted. The remapping of these files is stored in a memory based hash
   * table (it is assumed since input must come from /dev/tty, it is unlikely to
   * be a very large table).
   */

  /*
   * name_start()
   *	create the interactive rename table
   * Return:
   *	0 if successful, -1 otherwise
   */

  /*  func name_start() -> Bool {
   }
   */

  /*
   * add_name()
   *	add the new name to old name mapping just created by the user.
   *	If an old name mapping is found (there may be duplicate names on an
   *	archive) only the most recent is kept.
   * Return:
   *	0 if added, -1 otherwise
   */

  func add_name(_ oname : String, _ nname : String) -> Bool {
    ntab[oname]=nname
  }

  /*
   * sub_name()
   *	look up a link name to see if it points at a file that has been
   *	remapped by the user. If found, the link is adjusted to contain the
   *	new name (oname is the link to name)
   */

  func sub_name(_ oname : String) -> String {
    /*
     * look the name up in the hash table
     */
    return ntab[oname] ?? oname
  }

  /*
   * device/inode mapping table routines
   * (used with formats that store device and inodes fields)
   *
   * device/inode mapping tables remap the device field in an archive header. The
   * device/inode fields are used to determine when files are hard links to each
   * other. However these values have very little meaning outside of that. This
   * database is used to solve one of two different problems.
   *
   * 1) when files are appended to an archive, while the new files may have hard
   * links to each other, you cannot determine if they have hard links to any
   * file already stored on the archive from a prior run of pax. We must assume
   * that these inode/device pairs are unique only within a SINGLE run of pax
   * (which adds a set of files to an archive). So we have to make sure the
   * inode/dev pairs we add each time are always unique. We do this by observing
   * while the inode field is very dense, the use of the dev field is fairly
   * sparse. Within each run of pax, we remap any device number of a new archive
   * member that has a device number used in a prior run and already stored in a
   * file on the archive. During the read phase of the append, we store the
   * device numbers used and mark them to not be used by any file during the
   * write phase. If during write we go to use one of those old device numbers,
   * we remap it to a new value.
   *
   * 2) Often the fields in the archive header used to store these values are
   * too small to store the entire value. The result is an inode or device value
   * which can be truncated. This really can foul up an archive. With truncation
   * we end up creating links between files that are really not links (after
   * truncation the inodes are the same value). We address that by detecting
   * truncation and forcing a remap of the device field to split truncated
   * inodes away from each other. Each truncation creates a pattern of bits that
   * are removed. We use this pattern of truncated bits to partition the inodes
   * on a single device to many different devices (each one represented by the
   * truncated bit pattern). All inodes on the same device that have the same
   * truncation pattern are mapped to the same new device. Two inodes that
   * truncate to the same value clearly will always have different truncation
   * bit patterns, so they will be split from away each other. When we spot
   * device truncation we remap the device number to a non truncated value.
   * (for more info see table.h for the data structures involved).
   */


  /*
   * add_dev()
   *	add a device number to the table. this will force the device to be
   *	remapped to a new value if it be used during a write phase. This
   *	function is called during the read phase of an append to prohibit the
   *	use of any device number already in the archive.
   * Return:
   *	0 if added ok, -1 otherwise
   */

  func add_dev(_ arcn : ARCHD) -> Result {
    guard let _ = chk_dev(arcn.sb.device, true) else {
      return .failed
    }
    return .ok
  }

  /*
   * chk_dev()
   *	check for a device value in the device table. If not found and the add
   *	flag is set, it is added. This does NOT assign any mapping values, just
   *	adds the device number as one that need to be remapped. If this device
   *	is already mapped, just return with a pointer to that entry.
   * Return:
   *	pointer to the entry for this device in the device map table. Null
   *	if the add flag is not set and the device is not in the table (it is
   *	not been seen yet). If add is set and the device cannot be added, null
   *	is returned (indicates an error).
   */

  private func chk_dev(_ dev : UInt, _ add : Bool) -> [DLIST]? {

    /*
     * look to see if this device is already in the table
     */
    if let pt = dtab[dev] {
      return pt
    }

    /*
     * not in table, we add it only if told to as this may just be a check
     * to see if a device number is being used.
     */
    if !add {
      return nil
    }

    /*
     * allocate a node for this device and add it to the front of the hash
     * chain. Note we do not assign remaps values here, so the pt->list
     * list must be NULL.
     */
    let pt = [DLIST]()
    dtab[dev] = pt
    return pt
  }

  /*
   * map_dev()
   *	given an inode and device storage mask (the mask has a 1 for each bit
   *	the archive format is able to store in a header), we check for inode
   *	and device truncation and remap the device as required. Device mapping
   *	can also occur when during the read phase of append a device number was
   *	seen (and was marked as do not use during the write phase). WE ASSUME
   *	that unsigned longs are the same size or bigger than the fields used
   *	for ino_t and dev_t. If not the types will have to be changed.
   * Return:
   *	0 if all ok, -1 otherwise.
   */

  func map_dev(_ arcn : inout ARCHD, _ dev_mask : UInt, _ ino_mask : UInt) -> Result {
/*    DEVT *pt;
 */
//    var dpt : DLIST?

//    static dev_t lastdev = 0;	/* next device number to try */

    var trc_ino = false
    var trc_dev = false

    var trunc_bits = UInt(0)

    /*
     * check for device and inode truncation, and extract the truncated
     * bit pattern.
     */
    if (arcn.sb.device & dev_mask) != arcn.sb.device {
      trc_dev = true
    }
    let nino = arcn.sb.inode & ino_mask
        if nino != arcn.sb.inode {
          trc_ino = true
          trunc_bits = arcn.sb.inode & ~ino_mask
    }

        /*
         * see if this device is already being mapped, look up the device
         * then find the truncation bit pattern which applies
         */
    if let pt = chk_dev(arcn.sb.device, false) {
      /*
       * this device is already marked to be remapped
       */
      if let dpx = pt.first(where: { $0.trunc_bits == trunc_bits }) {
        /*
         * we are being remapped for this device and pattern
         * change the device number to be stored and return
         */
        arcn.sb.device = dpx.dev
        arcn.sb.inode = nino
        return .ok
      }
    } else {
      /*
       * this device is not being remapped YET. if we do not have any
       * form of truncation, we do not need a remap
       */
      if !trc_ino && !trc_dev {
        return .ok
      }

      /*
       * we have truncation, have to add this as a device to remap
       */
      if ((pt = chk_dev(arcn.sb.device, true)) == NULL) {
        goto bad;
      }

      /*
       * if we just have a truncated inode, we have to make sure that
       * all future inodes that do not truncate (they have the
       * truncation pattern of all 0's) continue to map to the same
       * device number. We probably have already written inodes with
       * this device number to the archive with the truncation
       * pattern of all 0's. So we add the mapping for all 0's to the
       * same device number.
       */
      if !trc_dev && trunc_bits != 0 {
        let dpt = DLIST(trunc_bits: 0, dev: arcn.sb.device)
        dtab[arcn.sb.device] = dtab[arcn.sb.device]! + [dpt]
      }
    }

        /*
         * look for a device number not being used. We must watch for wrap
         * around on lastdev (so we do not get stuck looking forever!)
         */
        while (++lastdev > 0) {
      if (chk_dev(lastdev, 0) != NULL) {
        continue;
      }
      /*
       * found an unused value. If we have reached truncation point
       * for this format we are hosed, so we give up. Otherwise we
       * mark it as being used.
       */
      if (((lastdev & ((dev_t)dev_mask)) != lastdev) ||
          (chk_dev(lastdev, 1) == NULL)) {
        goto bad;
      }
      break;
    }

        if lastdev <= 0  {
      goto bad;
    }

        /*
         * got a new device number, store it under this truncation pattern.
         * change the device number this file is being stored with.
         */
    let dpt = DLIST(trunc_bits: trunc_bits, dev: lastdev)
    dtab[arcn.sb.device] = dtab[arcn.sb.device]! + [dpt]
        arcn.sb.device = lastdev
        arcn.sb.inode = nino
        return .ok

        bad:
          Tty.paxwarn(true, "Unable to fix truncated inode/device field when storing \(arcn.name)")
        Tty.paxwarn(false, "Archive may create improper hard links when extracted");
        return .ok
  }

  /*
   * directory access/mod time reset table routines (for directories READ by pax)
   *
   * The pax -t flag requires that access times of archive files be the same
   * before being read by pax. For regular files, access time is restored after
   * the file has been copied. This database provides the same functionality for
   * directories read during file tree traversal. Restoring directory access time
   * is more complex than files since directories may be read several times until
   * all the descendants in their subtree are visited by fts. Directory access
   * and modification times are stored during the fts pre-order visit (done
   * before any descendants in the subtree are visited) and restored after the
   * fts post-order visit (after all the descendants have been visited). In the
   * case of premature exit from a subtree (like from the effects of -n), any
   * directory entries left in this database are reset during final cleanup
   * operations of pax. Entries are hashed by inode number for fast lookup.
   */


  /*
   * atdir_end()
   *	walk through the directory access time table and reset the access time
   *	of any directory who still has an entry left in the database. These
   *	entries are for directories READ by pax
   */

  func atdir_end() {

    /*
     * for each non-empty hash table entry reset all the directories
     * chained there.
     */
    for var (k, v) in atab {
      set_ftime(v.name, v.mtime, v.atime, 1)
    }
  }

    /*
     * add_atdir()
     *	add a directory to the directory access time table. Table is hashed
     *	and chained by inode number. This is for directories READ by pax
     */

    func add_atdir(_ fname : String, _ dev : UInt, _ ino : UInt, _ mtime : DateTime, _ atime : DateTime) -> ATDIR {

      /*
       * make sure this directory is not already in the table, if so just
       * return (the older entry always has the correct time). The only
       * way this will happen is when the same subtree can be traversed by
       * different args to pax and the -n option is aborting fts out of a
       * subtree before all the post-order visits have been made.
       */
      if let pt = atab[DevInode(dev: dev, ino: ino)] {
        return pt
      }

      let pt = ATDIR(name: fname, dev: dev, ino: ino, mtime: mtime, atime: atime)
      atab[DevInode(dev: dev, ino: ino)] = pt
      return pt
    }

  /*
   * get_atdir()
   *	look up a directory by inode and device number to obtain the access
   *	and modification time you want to set to. If found, the modification
   *	and access time parameters are set and the entry is removed from the
   *	table (as it is no longer needed). These are for directories READ by
   *	pax
   * Return:
   *	0 if found, -1 if not found.
   */

  func get_atdir(_ dev : UInt, _ ino : UInt, _ mtime : inout DateTime, _ atime : inout DateTime) -> Result {
    guard let pt = atab[DevInode(dev: dev, ino: ino)] else {
      return .failed;
    }
    /*
     * found it. return the times and remove the entry from the table.
     */
    mtime = pt.mtime
    atime = pt.atime
    atab.removeValue(forKey: DevInode(dev: dev, ino: ino) )
    return .ok
  }

  /*
   * directory access mode and time storage routines (for directories CREATED
   * by pax).
   *
   * Pax requires that extracted directories, by default, have their access/mod
   * times and permissions set to the values specified in the archive. During the
   * actions of extracting (and creating the destination subtree during -rw copy)
   * directories extracted may be modified after being created. Even worse is
   * that these directories may have been created with file permissions which
   * prohibits any descendants of these directories from being extracted. When
   * directories are created by pax, access rights may be added to permit the
   * creation of files in their subtree. Every time pax creates a directory, the
   * times and file permissions specified by the archive are stored. After all
   * files have been extracted (or copied), these directories have their times
   * and file modes reset to the stored values. The directory info is restored in
   * reverse order as entries were added to the data file from root to leaf. To
   * restore atime properly, we must go backwards. The data file consists of
   * records with two parts, the file name followed by a DIRDATA trailer. The
   * fixed sized trailer contains the size of the name plus the off_t location in
   * the file. To restore we work backwards through the file reading the trailer
   * then the file name.
   */

  /*
   * add_dir()
   *	add the mode and times for a newly CREATED directory
   *	name is name of the directory, psb the stat buffer with the data in it,
   *	frc_mode is a flag that says whether to force the setting of the mode
   *	(ignoring the user set values for preserving file mode). Frc_mode is
   *	for the case where we created a file and found that the resulting
   *	directory was not writeable and the user asked for file modes to NOT
   *	be preserved. (we have to preserve what was created by default, so we
   *	have to force the setting at the end. this is stated explicitly in the
   *	pax spec)
   */

  func add_dir(_ name : String, _ psb : FileMetadata, _ frc_mode : Bool) {
    char realname[MAXPATHLEN], *rp;

    if (havechd && *name != '/') {
      if ((rp = realpath(name, realname)) == NULL) {
        Tty.paxwarn(true, "Cannot canonicalize %s", name);
        return;
      }
      name = rp;
    }

    dirp.append( DIRDATA(name: name, mode: psb.permissions, mtime: psb.lastWrite, atime: psb.lastAccess, frc_mode: frc_mode) )
  }

  /*
   * proc_dir()
   *	process all file modes and times stored for directories CREATED
   *	by pax
   */

  func proc_dir(_ options: pax.CommandOptions) {

    /*
     * read backwards through the file and process each directory
     */
    for dblk in dirp.reversed() {

      /*
       * read the trailer, then the file name, if this fails
       * just give up.
       */


      /*
       * frc_mode set, make sure we set the file modes even if
       * the user didn't ask for it (see file_subs.c for more info)
       */

      if options.pmode || dblk.frc_mode {
        set_pmode(dblk.name, dblk.mode)
      }

      if options.patime || options.pmtime {

        set_ftime(dblk.name, dblk.mtime, dblk.atime, false)
      }
    }

    dirp.removeAll()
  }

}
